### ISSUE TITLE
Transports Randomly Get Stuck

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#121]
For some reason Transports randomly get stuck on the shore, resulting them unable to move ever again. I think it might have something to do with ordering a unit to get into it, and having the Transport pull away at the last second. It was very difficult to reproduce, but I managed to catch this in a replay. Fast forward about half way through if possible.
- WarCraft 2 Battle.net Edition
- Stratagus version 2.3.0 (latest)
- Wargus version 2.2.7 (latest)
- Windows 7

---

Imported from Launchpad using lp2gh.
- date created: 2015-04-07T02:45:22Z
- owner: enkerzan
- the launchpad url was https://bugs.launchpad.net/bugs/1440956

**Comment by timfel** [comment]
(by enkerzan)

**Comment by DinkyDyeAussie** [comment]
I still see this bug on level 4 of the ToD human campagin.

**Comment by SimoneStarace** [comment]
This bug is still present in 3.0.0

I tested in one of my own maps and this it only happens when the transport is unable to unload every unit inside the ship but as soon it finds a free space it moves slower and then it remains stuck in place forever.

**Comment by Bomfunk** [comment]
Just confirming that this is still happening in 3.1.2.
It seems that this might have something to do with the transport not having enough space to unload the units. If 3-6 transports will be sent to unload all in one place, some of them will be moving very slowly while unloading, and then get stuck. This is pretty easily reproducible.

**Comment by Bomfunk** [comment]
Another observation that might give a clue - the stuck transport seems to be stuck specifically at the unloading action.
The reason I think so is because I tried to load units back into it (the stuck transport), but it immediately unloads them back.

I actually managed to get it unstuck somehow by moving the units around, trying to load them into the transport several times, and trying to give the transport orders to move around. And I reproduced this several times, as well.

**Comment by smuckola** [comment]
I just started Stratagus. Two of my three transports got stuck. I had to build that third one, lol
[smuckola_frozen_transport.sav.gz](https://github.com/Wargus/wargus/files/8139490/smuckola_frozen_transport.sav.gz)
!

**Comment by katastic** [comment]
I've had this multiple times through my playthrough of the Alliance campaign. Had to resort to cheating on one level because I had 3+ transports get stuck.

**Comment by katastic** [comment]
Shooting your own transports will not unstick them (as they attempt to flee, they wont flee). I've had no luck with putting units back in. I don't know the underlying code but it seems like transports script almost appears crashed / stuck / broken and is no longer responding to events.
