### ISSUE TITLE
don't gzip ogg video

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#129]
Hi,

The version of wartool I have will create .ogg.gz files.

.ogg files are already compressed, trying to compress those with gzip won't help.

Can you please verify this behaviour is still current ?

I'm trying to integrate Wartool into Debian's game-data-packager to create a proper .deb with all the extracted data.

Greetings,

---

Imported from Launchpad using lp2gh.
- date created: 2015-05-06T08:05:43Z
- owner: alexandre-detiste
- the launchpad url was https://bugs.launchpad.net/bugs/1452159

**Comment by timfel** [comment]
(by pali)
> The version of wartool I have will create .ogg.gz files.
> 
> .ogg files are already compressed, trying to compress those with gzip
> won't help.
> 

Yes, it make sense to not compress ogg/ogv with gzip.

> Can you please verify this behaviour is still current ?
> 
> I'm trying to integrate Wartool into Debian's game-data-packager to
> create a proper .deb with all the extracted data.
> 

License of external data does not allow to do something like that :-(
This is reason why we do not provide extracted data, but rather program
for extracting them...

**Comment by timfel** [comment]
(by alexandre-detiste)
> License of external data does not allow to do something like that :-(

Of course !

That's game-data-packager whole point too:

identify needed game data on zip, rar, exe, arj, ace, GOG.com archives,
audio cd tracks and package it in a .deb only for _local_ use
to play Doom1|2|3, Quake1|2|3, scummvm games, whatever...

When I move from a PC to a new one, it's easier to move 1 .deb
than to try to identify what are the 100-something files
that where generated by wartool.

game-data-packager already has a plugin system that
enable to call one-game-off extraction engines,
like lgc-pg for panzer general.

wartool could fit there nicely too.

**Comment by a-detiste** [comment]
Nice to see this project moved to GitHub :smile: . This is still on my todo.

**Comment by timfel** [comment]
We're not gripping ogg video anymore for some time
