### ISSUE TITLE
Cannot start single player games, or Campaign games

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#130]
I have an issue, under Wargus I cannot start a Single player game, nor can I start a Campaign game. I can start and play a Multiplayer game solo however. I extracted it using Wargus 2.3. If I click on Single player Standard game, or campaign game, I get the error: Error in Error handling on the console, and I am presented with a blank screen with no missions.

---

Imported from Launchpad using lp2gh.
- date created: 2015-05-07T09:21:08Z
- owner: zombie-ryushu
- the launchpad url was https://bugs.launchpad.net/bugs/1452637

**Comment by sheepo99** [comment]
I have this same issue on Windows 10. When I install the game it seems to play fine, but as soon as I attempt to start a single player game it crashes permanently. I am completely unable to even restart wargus afterwards unless i reinstall.

**Comment by timfel** [comment]
I cannot reproduce this. Where did you install it? Are you running the game as administrator? Are there any log files (stderr.txt, stdout.txt) inside the Stratagus or Wargus folder?

**Comment by timfel** [comment]
Also, did you install from the latest installer postet on Github? Or did you build your own?

**Comment by Kintobor** [comment]
If you move Stratagus.exe to the Wargus directory, it should start. Previously Cyber and I decided that the next version would ship with the binary in the Wargus folder.

Wargus no longer works with AT assets, something has changed it Stratagus. The two AT campaigns are broken.

**Comment by timfel** [comment]
Hm, thats strange, because it works on my machines when installing Stratagus and Wargus each in their own folder, and AT assets also work.

**Comment by timfel** [comment]
(this was when installing it on a Windows 10 machine that has never had Stratagus or Wargus installed before. The only thing I had to do was launch as Afministrator)

**Comment by Kintobor** [comment]
If that is the case it may be old configuration files causing the issue.

**Comment by sheepo99** [comment]
Thank you for the tip! It turns out it was because I wasn't running the game in admin mode!
