### ISSUE TITLE
Target finding on 256by256 maps causes delay

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#131]
AiAttackWithForce causes the game to lag when on 256 by 256. If an enemy isn't in the first 128by128 section the Ai will fail to find him, and the game will freeze for a second.

---

Imported from Launchpad using lp2gh.
- date created: 2015-09-15T06:45:13Z
- owner: erstmap
- the launchpad url was https://bugs.launchpad.net/bugs/1495818

**Comment by Kintobor** [comment]
Last I checked this was present on the Socotra test map.

**Comment by timfel** [comment]
Pathfinding was improved by porting things from Wyrmgus
