### ISSUE TITLE
A sponsored feature request: start multiplayer game from command line

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#132]
I am willing to donate 10 Euro to a developer willing to add this feature to wargus/stratagus: for all multiplayer participants have the preparation room skipped and start the game directly from command line. It could work in this manner:
-m <map>
-r <race>
-s <server addr>

a) on the server: wargus -m map.smp -r orc
b) on the clients: wargus -s 192.168.100.1 -r human

**Comment by timfel** [comment]
I'm working on something that will enable this use case

**Comment by mimooh** [comment]
> I'm working on something that will enable this use case
That's great! I am still willing to sponsor this feature in wargus.


-- 
Karol Kreński

**Comment by timfel** [comment]
Feel free to close this issue if you can confirm the merged solution works for you

**Comment by KroArtem** [comment]
If you still want to spend your time on this issue, you can add some words about new option in documentation/man ;)

**Comment by timfel** [comment]
I have edited the man page to show document these options.
