### ISSUE TITLE
Wargus build error: cannot find mods

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#133]
fresh wargus from github:

-- Installing:
/home/mimooh/wargus/debian/wargus/usr/share/games/stratagus/wargus/maps/ftm/(2)nicks-duel.smp
CMake Error at cmake_install.cmake:108 (FILE):
  file INSTALL cannot find "/home/mimooh/wargus/mods".

**Comment by timfel** [comment]
It should work now, the empty mods directory is gone. Things like that should happen less in the future, we now compile on each commit: https://travis-ci.org/Wargus/wargus/jobs/92762845 :)

**Comment by mimooh** [comment]
> It should work now, the empty mods directory is gone. Things like that should happen less in the future, we now compile on each commit: https://travis-ci.org/Wargus/wargus/jobs/92762845 :)
Glad to hear, however...  :)

/home/mimooh/wargus/debian/wargus/usr/share/games/stratagus/wargus/graphics/ui/score.png
make[1]: Leaving directory `/home/mimooh/wargus/obj-x86_64-linux-gnu'
debian/rules override_dh_install
make[1]: Entering directory `/home/mimooh/wargus'
dh_install
convert wargus.png -resize 32x32
debian/wargus/usr/share/pixmaps/wargus.xpm
find debian/wargus/usr/share/games/stratagus/wargus/maps -name
"*.pud*" -exec rm {} ';'
make[1]: Leaving directory `/home/mimooh/wargus'
dh_installdocs
cp: cannot stat 'README': No such file or directory
dh_installdocs: cp -a README debian/wargus/usr/share/doc/wargus
returned exit code 1
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error
exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed
	  

-- 
Karol Kreński

**Comment by timfel** [comment]
Ahh, you're building the debian package. I hadn't tried that at all...

**Comment by mimooh** [comment]
The fix is:

cd wargus/
cp README.md README

works.

-- 
Karol Kreński

**Comment by mimooh** [comment]
And thanks for very quick support! :)

-- 
Karol Kreński

**Comment by timfel** [comment]
Yeah, but I just renamed README the other way ;) I changed the definition for the debian package, it includes the README.md file now, and I was able to build a package locally.

**Comment by mimooh** [comment]
Fine. Wargus is built and installed, but more scarry news comming. Who the hell is Lucas Kage? :)

s2:wargus$ wargus 
Can't open file: No such file or directory
Can't load the graphic `characters/Lucas Kage/char_kaminari_full.png'

[log.txt](https://github.com/Wargus/wargus/files/42078/log.txt)

**Comment by timfel** [comment]
Yeah, I saw that too. Unfortunately, I have no idea what those things are about, Kyran has been working on that codebase adding stuff which I have no idea about (I really just care about the Blizzard RTS). I'll take a look tomorrow

**Comment by timfel** [comment]
I've added @Kintobor to this organization, he was the last person to touch that code, he may be able to help.

**Comment by timfel** [comment]
Ok, I've pushed a temporary fix. It should start now :)

**Comment by mimooh** [comment]
> Ok, I've pushed a temporary fix. It should start now :)
It works! :) I will inspect it closer within a week. Thanks for all your
contribution to this great project!

-- 
Karol Kreński

**Comment by Kintobor** [comment]
The database.lua file deals with animated mission briefings. I was testing it with graphics that weren't uploaded to Launchpad.

**Comment by timfel** [comment]
I'll close this for now, the graphics are still referenced, but the game works.
