### ISSUE TITLE
Stratagus is v2.4.0 now. Perhaps wargus could much this version too.

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#138]
Stratagus is v2.4.0 now. Perhaps wargus could much this version too.

**Comment by timfel** [comment]
Yes, I have updated the version number yesterday. The current debian and windows packages are already the new version

**Comment by Kintobor** [comment]
Why a new major version? It took us five years to go from 2.2.5 to 2.3.

**Comment by timfel** [comment]
Because we broke compatibility with the games.
