### ISSUE TITLE
ubuntu 15.04 stratagus/wargus unmet dependencies

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#139]
Just tried to install the packages:
$ sudo add-apt-repository ppa:stratagus
$ sudo apt-get update

solidarny:~$ apt-get install stratagus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  wargus war1gus stargus stratagus-data
The following NEW packages will be installed:
  stratagus
0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.
Need to get 0 B/961 kB of archives.
After this operation, 4320 kB of additional disk space will be used.
Selecting previously unselected package stratagus.
(Reading database ... 275827 files and directories currently installed.)
Preparing to unpack .../stratagus_2.4.0-0~9094~ubuntu15.04.1_amd64.deb ...
Unpacking stratagus (2.4.0-0~9094~ubuntu15.04.1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up stratagus (2.4.0-0~9094~ubuntu15.04.1) ...
solidarny:~$ apt-get install wargus   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wargus : Depends: stratagus (>= 2.4.0) but 2.4.0-0~9094~ubuntu15.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.

solidarny:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

**Comment by timfel** [comment]
Is it just me or should 2.4.0-0~9094 be indeed >= 2.4.0? How come it thinks it isn't?

**Comment by a-detiste** [comment]
I guess comparing native package version vs non-native ones is not supported expected.

the ultimate reference is playing around with `dpkg --compare-versions`

by the way, I used to run a FrankenDebian (baaad) with this PPA enabled;
but now in Ubuntu there's libmng2 while Debian still has libmng1;
so I'll really need to build it myself this time.

**Comment by mimooh** [comment]
> Is it just me or should 2.4.0-0~9094 be indeed >= 2.4.0? How come it thinks it isn't?
Hahaha, my reasoning is the same as yours :) 

I tried to file a bug to apt-get or ubuntu, but the process of bug
reporting there looks like they are all against receiving any bug
reports. 

If no resolution comes to your mind let me know and I'll help with
resolving this issue.

-- 
Karol Kreński

**Comment by mimooh** [comment]
Perhaps wargus
Depends: stratagus (>= 2.4.0) 
should be changed into:
Depends: stratagus (>= 2.4.0~1) 


Based on the results from dpkg (thanks a-detiste):

g201:~$ dpkg --compare-versions '2.4.0-0~1' '>=' '2.4.0'; echo $?
Nope

g201:~$ dpkg --compare-versions '2.4.0-0~1' '>=' '2.4.0~999'; echo $?
Yes

g201:~$ dpkg --compare-versions '2.4.0-0~9999' '>=' '2.4.0~999'; echo $?
Yes
