### ISSUE TITLE
Question: Checksum / Hashes?

### ISSUE THREAD

**Issue by CanadianJeff** [Wargus/wargus#142]
is there a way to verify CRC32, MD5, SHA1 hashes of warcraft 2 files?

from inside WAR2DAT.MPQ?

**Comment by a-detiste** [comment]
Hi,

That's the purpose of the `game-data-packager` tool I'm working on...

http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/tree/data/warcraft2.wip
But I have dubbed French version, so most files won't match.

**Comment by CanadianJeff** [comment]
this is what I have right now.... this is a patched version 2.02 (USA)

```
root@xubuntu:/home/jefferyw/.wine/drive_c/Program Files (x86)/Warcraft II BNE# sha1sum *.mpq
76cf76672a7af8b8b93d5e386ad208fa7ba2cf66  War2Dat.mpq
3e786d6fd16b538b5b45ab971b6612970bd7ed6c  War2Patch.mpq
root@xubuntu:/home/jefferyw/.wine/drive_c/Program Files (x86)/Warcraft II BNE# sha1sum *.dll
d85bc8a2aec0eafa35f59baa1cc9293661c7b618  Smackw32.dll
a8d7f56fd81976e98e7dadf0efae4625f6749b84  storm.dll
e1f1485fcf3a35b23dc3d226521d2510ce693f5c  W2Local.dll
root@xubuntu:/home/jefferyw/.wine/drive_c/Program Files (x86)/Warcraft II BNE# sha1sum *.exe
df28b0cbbd2645d95df18790b997f8965df7dd6c  BNUpdate.exe
acfa1ad7ec34dfdf6ec326a77a4dd9c685616b26  Warcraft II BNE.exe
e4423464c978874dae5e43338d33e69dc58e48ac  Warcraft II Map Editor.exe
```

**Comment by a-detiste** [comment]
my hashes are from the DOS version, originaly the only version that was supported by wargus

**Comment by CanadianJeff** [comment]
oh I just saw the readme that BNE is not supported I am sad now and I doubt blizzard will offer advice if these hashes are correct or not because the game is so old now

**Comment by CanadianJeff** [comment]
closing this as its not related to wargus

**Comment by a-detiste** [comment]
well I have the BNE edition too

**Comment by a-detiste** [comment]
will check that tomorrow

**Comment by CanadianJeff** [comment]
your copy is probley not from (USA) or from the warcraft 2 battle chest so the hashes probley will not match

**Comment by timfel** [comment]
I think the README must be updated (and the binaries), because BNE is supported, as far as i know, as long as wartool is compiled with StormLib.
