### ISSUE TITLE
copyrighted assests in provided .deb ?!

### ISSUE THREAD

**Issue by a-detiste** [Wargus/wargus#145]
Hi, I can't upgrade to 2.4 because it clash with my .deb that provides the output of wartool.
On other systems, wartool output would have been silently replaced.

`debdiff ~/Downloads/wargus_2.2.7-1ubuntu1-quantal_amd64.deb
/var/cache/apt-cacher-ng/ppa.launchpad.net/stratagus/ppa/ubuntu/pool/main/w/wargus/wargus_2.4.0-0~1940~ubuntu16.04.1_amd64.deb`

```
Files in second .deb but not in first
-------------------------------------
...
/usr/share/games/stratagus/wargus/graphics/missiles/death_and_decay.png
/usr/share/games/stratagus/wargus/graphics/missiles/dragon_breath.png
/usr/share/games/stratagus/wargus/graphics/missiles/exorcism.png
...

Files in first .deb but not in second
-------------------------------------
/usr/share/games/stratagus/wargus/maps/multi/  -> 20-some maps
/usr/share/games/stratagus/wargus/maps/multi/(2)blick-nach-oben*
/usr/share/games/stratagus/wargus/maps/multi/(2)east-west-conflict*
```

**Comment by a-detiste** [comment]
```
dpkg -S graphics/missiles/exorcism.png | sortfcmp: /usr/share/games/freecraft/fcmp/graphics/missiles/exorcism.png
fcmp: /usr/share/games/freecraft/fcmp/graphics/missiles/exorcism.png.txt
warcraft2-fr-data: /usr/share/games/stratagus/wargus/graphics/missiles/exorcism.png
```

A visual comparaison tell me that this exocism.png is the same as the one form FreeCraft;
the ancien package still available in Debian https://packages.qa.debian.org/f/freecraft.html

**Comment by a-detiste** [comment]
If you really want to ship those, please provide a `wargus-free-data` that conflicts with `warcraft2-data`.

**Comment by timfel** [comment]
hm, okay, so the right option would be to generate two deb files, one called wargus, and one called aleonas-tales (or something) that provides the free data?

**Comment by a-detiste** [comment]
Yup, and both package would conflict on the other one

**Comment by a-detiste** [comment]
Well, the best would be that Warcraft II & Aleonas Tales would use two different namespaces (directories ?) and be co-installable.

**Comment by timfel** [comment]
Aleonas Tales was removed some time ago
