### ISSUE TITLE
Main Menu Music

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#147]
The main menu music is wrong. "I'm a Medieval Man" was a bonus track on the CD. Can we please have the main menu music back to it's original tune?

**Comment by Kintobor** [comment]
Dinky isn't a Medieval Man.

**Comment by timfel** [comment]
Um... I've just installed it again on a clean machine, and the correct main menu music is playing. The code also says that "Main Menu.mid" should be played. Do you have that file in your wargus/music folder?

**Comment by DinkyDyeAussie** [comment]
in stratagus.lua it has a line that says:

wargus.playlist = { "music/Main Menu" .. wargus.music_extension }

That's it. There is a "Main Menu.mid" in my music directory, and that is the correct music for the menu, but the "Main Menu.ogg" is wrong, but maybe if wartool was modified to extract the correct CD Main Menu music (which is higher quality than the midi version).

It used to be the proper high quality music. That's all :)

**Comment by timfel** [comment]
On what platform are you? Wartool can extract the CD music, but on you'll have to tell it to. The debian package gives you the option, not sure about the Windows installer.

**Comment by Kintobor** [comment]
After we released 2.3 I told Cyber about this issue. He seemed concerned, but I thought it was great.

**Comment by Insidious611** [comment]
The issue basically seems to be that wartool makes wrong assumptions about the audio track structure of the Expansion CD. The same issue happened to me. Specifically, it seems to assume that the Expansion CD has 19 tracks, that after its data track, it has 5 human tracks, a human briefing track, a human victory track, a human defeat track, 5 orc tracks, an orc briefing track, victory track, and defeat track, and then the main menu music and *then* I'm A Medieval Man. When in reality, my Beyond the Dark Portal disk and every other one I can find on eg cddb or so, only has *18* tracks, *lacking* a Main Menu track and with I'm A Medieval Man being the 18th, not the 19th, track. I would assume Wartool was just running the same CD audio extraction on both disks, if it weren't for the fact that when given the Expansion disk it actually asks for a 19th track, whereas it does not do this for the original disk.

**Comment by DinkyDyeAussie** [comment]
I see. So if I use the tod cd to extract the music I should get the starndard menu music :)

**Comment by timfel** [comment]
Now a replaced by #345 which is a wider issue
