### ISSUE TITLE
What version is Wargus and Stratagus based off?

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#148]
So the newest version of both Wargus and Stratagus is built upon 2.3 right? I checked the changelog file and it goes straight from 2.2.7 to 2.4. Did we leave 2.3 back on Launchpad? Why isn't it listed in the Changelog file?

**Comment by timfel** [comment]
The code was moved from launchpad, and the debian changelog at least does have 2.3.
