### ISSUE TITLE
windows installation problem

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#151]
OS: windows7 and windows10 (3 separate machines):

Stratagus from nightly builds installs fine.
Wargus from nightly builds (https://github.com/Wargus/wargus/releases/tag/master-builds) complains:

1. Error opening file for writing: c:\Program Files (x86)\Wargus\music\TimGM6mb.sf2
2. wartool.exe: cannot run because MSVCP140.dll is missing.
3. wargus.exe: cannot run because VCRUNTIME140.dll is missing.

**Comment by DinkyDyeAussie** [comment]
download the individual dlls (MSVCP140.dll and VCRUNTIME140.dll) by doing a google  search, then place them in your windows/system32 folder. TimGM6mb.sf2 needs the wargus install to work properly in order to be created. It will be created if you download and install the dlls. I know as I had this issue and I did this and I have wargus installed now.

**Comment by timfel** [comment]
Sorry, I meant to add the VC redist to the installer but lost track. I'll do that now

**Comment by timfel** [comment]
The nightly builds are built on a "Visual Studio 14 2015", so the redistributable that has the required dlls is here: https://www.microsoft.com/de-de/download/details.aspx?id=48145. This is what I'm bundling in the installer now, I find it preferable over chugging dlls in there that got downloaded off some random location :)

**Comment by timfel** [comment]
Ok, the new installer is up, @mimooh if you want you can try it, it should install the required dlls automatically

**Comment by mimooh** [comment]
> Ok, the new installer is up, @mimooh if you want you can try it, it should install the required dlls automatically
I will gladly have it checked within a week or so. Thanks Tim!

-- 
Karol Kreński

**Comment by mimooh** [comment]
Tried under win7@virtualbox. Installs and works after some MS package
gets autoinstalled. Good work Tim! However, prior to installing the dlls
the TimGM6mb.sf2 error pops up. Probably the sequence is wrong - first
the dlls, then TimGM6mb.sf2:

"TimGM6mb.sf2 needs the wargus install to work properly in order to be
created. It will be created if you download and install the dlls."

**Comment by mimooh** [comment]
Yesterday I installed on windows, and again the installer was complaining that TimGM6mb.sf2 is missing. Not a big issue for anyone probably (you just press 'ignore' button in the installer), but there is this problem.

**Comment by timfel** [comment]
I just pushed a new change that I hope might help.

**Comment by timfel** [comment]
This should be fixed.
