### ISSUE TITLE
Videos, sound stuttering.

### ISSUE THREAD

**Issue by Insidious611** [Wargus/wargus#156]
Hi. I just installed Wargus using the data from my Warcraft 2 Tides of Darkness and Beyond the Dark Portal CDs. It seems to have gone relatively well, but I have two (probably related so I grouped them together) problems. 

The audio in both the videos and the ingame voice and occasionally music is stuttering/lagging randomly. I know it's not a problem with my game data because I played back one of the ogv files that the wargus package created in mplayer and it played just fine, but when I'm ingame "The mighty armies" in the intro becomes "Th-th-tht-the m-m-m-m-mighty armies". The same thing happens with voiceovers in the mission descriptions, and occasionally the extracted CD audio music sounds as though it's playing too slowly. 

I don't have this issue with any other games, except maybe Quake 4 which doesn't play nicely with pulseaudio. I thought maybe this might be a similar issue, but running Wargus with pasuspender (which is what I do to get quake 4 running properly) just leads to no sound whatsoever.

My setup, for reference:

Running Debian Jessie
Intel HDA Codec audio (snd-hda-intel)
Pulseaudio 7.1
Linux 3.16.0-4-amd64
nVidia proprietary drivers 352.55

Compiled packages from source for my system using apt-get source --build, using the sources from the PPA. (followed this tutorial: https://wiki.debian.org/CreatePackageFromPPA).

Hardware specs:

Intel Core i5-4570
nVidia GeForce GTX 960 1GB
8GB DDR3-1600 RAM

**Comment by timfel** [comment]
Hm, I wonder if that has something to do with our audio thread. I also have occasional sound stuttering on the raspberry pi, but that may be due to actual inefficiencies combined with the slow processor.

**Comment by mathgamain** [comment]
Happened to me on version 2.4.1 and is still a problem on the latest git commit.

**Comment by timfel** [comment]
We now switched to SDL2 for audio instead of using our own code, that should fix it
