### ISSUE TITLE
Fix or remove russian lables in installer

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#158]
As @Mistranger mentioned, the russian labels in the installer are broken/incomplete.

Unless someone steps up to do translations, I'd say we can just remove all russian labels. (Although that might just be me personally. I tend to use pretty much everything in the language it was created in originally and in english, otherwise)

**Comment by mimooh** [comment]
Even if the messages were translated, there will still be the sounds in English, right? Kind of weird. English as a language becomes more and more less foreign, so people should get used to. I am a minimalist, so I won't cry if the translations are thrown away :)

**Comment by Mistranger** [comment]
So, I've fixed it: https://github.com/Wargus/wargus/commit/0b4cb7c69aa45fc6353e8dfbc332acb37a15282f
use unicode version of nsis to build it properly http://www.scratchpaper.com/

**Comment by timfel** [comment]
Ok, so we'll need to update the CI script to install the Unicode NSIS port. I think they moved here: https://github.com/jimpark/unsis

**Comment by timfel** [comment]
I've updated the CI script to use Unicode NSIS.
