### ISSUE TITLE
Wargus is not a proper windows application

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#160]
This error pops up under windows xp. I assisted a friend with the installation over a telephone and I'd say wargus was installed in a proper way. Is this enough information to figure out what the problem is? I can find more details if it is required.

**Comment by timfel** [comment]
Hm, might e that we have to configure Visual Studio to build an XP compatible binary.

**Comment by timfel** [comment]
It's definitely that we compile the binaries for Vista+ only, and no support for Windows XP. That'll require rebuilding the dependencies with XP support, too.

**Comment by timfel** [comment]
Can you try the current installer? I have rebuilt all dependencies with XP compat and am building the binaries XP-compatible now, so this should work, but I have no XP to test.
