### ISSUE TITLE
Wargus required admin to start

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#161]
I observed this on at least one windows machine: double click on wargus results in a clepsydra icon for around 10 seconds, then normal icon without any error - wargus won't start. Wargus is started when I right click on wargus and run as administrator.

**Comment by timfel** [comment]
Can you try with the current build? This should be fixed, stdout and stderr should now go to the user directory (previously they were written to the install dir, which requires admin)

**Comment by timfel** [comment]
This should finally be fixed now. Just tried on a fresh Win10 machine.
