### ISSUE TITLE
windowsXP: stratagus cannot be found 

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#164]
I have just installed the new wargus under winXP. The installer seems to not require stratagus, so I guess stratagus binary is inside wargus installer. Then I clicked wargus icon and got the error that stratagus cannot be found. So I installed stratagus manually from git, but wargus still cannot find it. I'd say that stratagus is on a path that wargus cannot find.

**Comment by timfel** [comment]
Can you check that the stratagus.exe is in the install folder?

**Comment by timfel** [comment]
it should have been put there by the installer, including some dlls (glib, gthread, fluidsynth, lua51)

**Comment by mimooh** [comment]
I am pretty much sure I saw stratagus.exe in wargus directory. I will
have it checked tommorrow. 

-- 
Karol Kreński

**Comment by timfel** [comment]
If you check it, try running it directly, because that should work, too.

**Comment by mimooh** [comment]
> If you check it, try running it directly, because that should work, too.
I will try in windows console:
	cd wargus/
	stratagus.exe [-d path]
if that's what you mean.

And where is wargus expecting to find stratagus.exe anyway? 
I'd say the current dir should be fine, right?:

CMakeLists.txt:
	find_package(Stratagus)
	if(NOT STRATAGUS_FOUND)
		# Just means we won't build the launcher ...
		set(STRATAGUS_INCLUDE_DIR ".")
	endif()

Anyway, distributing that 2MB stratagus binary in a 60MB wargus package
is a good thing. Auto installation of windows dependencies is great
also, thanks Tim! 


-- 
Karol Kreński

**Comment by timfel** [comment]
wargus is now searching for stratagus.exe in the current directory and through the registry in the installation folder. you can ignore the CMakelist, the code for finding the exe is not related to that.

**Comment by mimooh** [comment]
![runningstratagus](https://cloud.githubusercontent.com/assets/14321180/13807083/9eed0a3c-eb5f-11e5-96db-053fff90c2aa.jpg)
![runningwargus](https://cloud.githubusercontent.com/assets/14321180/13807082/9eeb6a38-eb5f-11e5-804e-3380456c849e.jpg)

**Comment by mimooh** [comment]
Under win7 wargus does't complain about missing stratagus, so the path is fine. But nothing happens. Nothing also happens in win7 console: 
cd wargus/
stratagus (no results)
stratagus -h (no results)

**Comment by timfel** [comment]
In windows, stdout and stderr are both written to user home AppData/Roaming/stratagus

**Comment by mimooh** [comment]
I will check tomorrow then - here at home I only have linux. This
weekend I am meeting an old friend and we hope to have a wargus
deathmatch under winXP. You know, it MUST be fixed by then! :)

-- 
Karol Kreński

**Comment by mimooh** [comment]
No stratagus/ under AppData/Roaming/ in win7. In winXP there's no such thing in user directory either. Seems like a problem with ucrtbase.dll:
![error1](https://cloud.githubusercontent.com/assets/14321180/13845858/0bc978b4-ec43-11e5-838a-c5faea557108.png)
![error2](https://cloud.githubusercontent.com/assets/14321180/13845860/0f175a04-ec43-11e5-9901-4e6dedb1b184.png)

[Report.txt](https://github.com/Wargus/wargus/files/177817/Report.txt)

**Comment by mimooh** [comment]
Hi @timfel, have you managed to do anything about the installer? I have windows10 at home now, so I can test like hell! :)

**Comment by timfel** [comment]
I havent had time, and I likely won't have any for the next two weeks still. Also, Windows 10 should work, that's what I test on. I do think XP should work, too, I am compiling everything with the xp compatible compiler. It may be I misconfigured something in the appveyor.yml, though, either for Stratagus, Wargus, or the bat file in the win32 libs project. I just have no time to set up an XP VM and investigate. Obe question that occurred to me: Does the XP machine you're running on have all updates and service packs installed? I'm pretty sure the compiler generates binaries that are only compatible with the very latest stuff.

**Comment by mimooh** [comment]
Let's leave it for now then, no hurry. Meanwhile I'll check again under
win7 and win10. I don't know if that winXP had service packs installed.

-- 
Karol Kreński

**Comment by mimooh** [comment]
wargus installs but fails to launch. I cd to where it is installed and from the console I run stratagus (exits without errors) and wargus (the busy cursor shows for a while, but also exits without errors).

**Comment by prilutsky** [comment]
I have the same problems in Windows XP. And totally fault in Windows 8.1 (64 bit). 

The Ubuntu version is working (almost) good.

**Comment by timfel** [comment]
Sorry, I just have zero time to debug into this right now. All I can say is that I tried it here on different Win7, Win8, and Win10 boxes from co-workers and it runs out of the box. So I'll have to investigate.

**Comment by prilutsky** [comment]
Error in Win8.1 (64 bit Russian)

Сигнатура проблемы:
  Имя события проблемы:	BEX
  Имя приложения:	stratagus.exe
  Версия приложения:	2.4.0.0
  Отметка времени приложения:	56e7ac52
  Имя модуля с ошибкой:	ucrtbase.DLL
  Версия модуля с ошибкой:	10.0.10240.16390
  Отметка времени модуля с ошибкой:	55a5bf73
  Смещение исключения:	0007c3a2
  Код исключения:	c0000409
  Данные исключения:	00000005
  Версия ОС:	6.3.9600.2.0.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	efcb
  Дополнительные сведения 2:	efcb8c90539722756ff354d9fac7cf8a
  Дополнительные сведения 3:	fc2d
  Дополнительные сведения 4:	fc2d9d6d5afd13e08816192cca92ac08

**Comment by mimooh** [comment]
On one windows10 machine, where wargus was previously installed and run, wargus installs and runs. On the other window10 machine, where it was never installed before it installs but dies with no error.

**Comment by mimooh** [comment]
@timfel, perhaps we could have the latest changes reverted for now? Wargus used to install fine under windows, but it is broken since these winxp fixes.

**Comment by timfel** [comment]
@mimooh Sorry for falling of the grid for so long. I found one issue that prevented startup on a clean install. See my comment here for a temporary workaround until new builds are uploaded: https://github.com/Wargus/wargus/issues/167

**Comment by mimooh** [comment]
Great news. Thanks Tim!

-- 
Karol Kreński

**Comment by timfel** [comment]
I just tested on a fresh Win10 and a fresh WinXP and installating and running works now. XP does have some issues (e.g. you have to start the stratagus.exe directly and manually install the VS 2015 redist), but I'm just going to put that into the readme.
