### ISSUE TITLE
Windows 8.1: Wargus crashes without logfile after fresh install

### ISSUE THREAD

**Issue by micronizerbattheend** [Wargus/wargus#165]
Hello
I had trouble with friends trying to get wargus to run, because of missing dependencies (DLLs).
So I decided I would format my computer to try and install windows 8.1 and wargus from zero, to be able to diagnose the problem.
Upon finishing the installer (Wargus-2.4.exe, latest build), trying to run the game only results in a generic windows error message: "Stratagus has stopped working". I can't find a logfile in the game directory.
I tried running the program (either wargus.exe or stratagus.exe) with administrator privileges, with the same result.
The game is installed in a "c:\games\wargus\" directory.

Thanks!

**Comment by timfel** [comment]
Sorry for falling of the grid for so long. I found one issue that prevented startup on a clean install. See my comment here for a temporary workaround until new builds are uploaded: https://github.com/Wargus/wargus/issues/167

**Comment by timfel** [comment]
I just tested on a fresh Win10 and a fresh WinXP and installating and running works now. XP does have some issues (e.g. you have to start the stratagus.exe directly and manually install the VS 2015 redist), but I'm just going to put that into the readme.
