### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by phobos2077** [Wargus/wargus#167]
Installed the game via installer (using original Warcraft 2 CD image). When try to launch, it says that **libfluidsynth.dll** is missing. Tried DLL with this name from 2.3, but it crashes on launch instead.

**Comment by phobos2077** [comment]
Ok, it was my antivirus that didn't liked this DLL. I disabled it, re-installed the game and now it just crashes on startup...

**Comment by micronizerbattheend** [comment]
Did it input any kind of error logfile? Or an error message? This may be the same issue affecting me #165  
I will try disabling my antivirus like you did to see if it helps in my case.

**Comment by phobos2077** [comment]
No I wasn't able to find any log output of the crash. Had to revert back to last-year version to finally finish my Orc campaign playthrough :)

**Comment by timfel** [comment]
Sorry about that, I finally got around to fixing a startup issue that I introduced when I forced writing of stderr.txt and stdout.txt to %APPDATA%\Roaming\Stratagus when that directory did not exist, yet. I have pushed the fix, but Github is having issues right now, so a new build will take a while longer. You can work around on your machine by simply creating the appdata directory manually and launching the game. Output files will be in that directory.

**Comment by timfel** [comment]
I just tested on a fresh Win10 and a fresh WinXP and installating and running works now. XP does have some issues (e.g. you have to start the stratagus.exe directly and manually install the VS 2015 redist), but I'm just going to put that into the readme.

**Comment by phobos2077** [comment]
That's awesome, thanks.
