### ISSUE TITLE
Some cheats do NOT work please guide me (Warcraft II Wargus 2.3)

### ISSUE THREAD

**Issue by mojucet666** [Wargus/wargus#168]
Hello, I want to skip/jump some campaign levels but it does not work. I have Warcraft II Wargus 2.3

How do I use other cheats like "Tigerlily" to jump levels ? 
or "There can be only one" for campaign victory.
  I'm trying all googling, checking cheats.lua - it's not there.. why would you not enable some cheats whilst you did so amazing remake of whole game... aww. So how to do it ???

**Comment by Kintobor** [comment]
Unite the clans!

**Comment by mojucet666** [comment]
thanks, 
but none for level jumping ? ^^

**Comment by mojucet666** [comment]
thanks,
but none for level jumping ? ^^ or i would also appreciate a readable list of cheats )

**Comment by mojucet666** [comment]
also "on screen" doesn't work to fully reveal map :/

**Comment by mojucet666** [comment]
oki I found out this should be full list of cheats available in Warcraft 2 Wargus:

hatchet
glittering prizes
on screen
showpath
fow on
fow off
fast debug
normal debug
make it so
unite the clans
you pitiful worm
it is a good day to die
fill mana
disco
