### ISSUE TITLE
Crash to Desktop when starting a campaign.

### ISSUE THREAD

**Issue by GeneralMasterCylinder** [Wargus/wargus#169]
Installed using the archive.org files found here:
https://archive.org/details/msdos_Warcraft_II_-_Tides_of_Darkness_1995

Loaded wargus and tried to start the campaign "beachhead"

Crashes to desktop, nothing in the windows logs.  Does wargus not come with some form of logging under windows? Let me know if there is anything I need to check to troubleshoot this.

War1gus works with files from the archive.

OS Details  - Windows 7 (64bit), Core i5 6600, 16Gb RAM

Thanks for the good work!

**Comment by timfel** [comment]
There should be logs in you user folder AppData\Roaming\Stratagus

**Comment by timfel** [comment]
That campaign was removed (since it's not an original campaign)
