### ISSUE TITLE
Glitch Present In Map Editor Involving Walls

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#17]
When using the map editor, the wall sections create other texture pallets that are glitched, resulting anything within a certain radius getting overwritten when you attempt to remove the placed wall section from the map. To reproduce this, simply place some walls on the field and overlap it with a tree or something and watch what happens. This also applies to Stratagus.
- WarCraft 2 Battle.net Edition
- Stratagus version 2.3.0 (latest)
- Wargus version 2.2.7 (latest)
- Windows 7

---

Imported from Launchpad using lp2gh.
- date created: 2015-04-07T02:35:22Z
- owner: enkerzan
- the launchpad url was https://bugs.launchpad.net/bugs/1440951

**Comment by timfel** [comment]
(by enkerzan)
I also discovered that a similar glitch will occur when you overlap dark water pallets with land pallets. If you attempt this on a map filled with dark water, it will cause Stratagus to lock up, forcing you to terminate the program manually.

**Comment by abenedic** [comment]
Is this still currently an issue? With the latest build from master? I can't currently test except through wine.

**Comment by timfel** [comment]
![wargus-editor-bug](https://user-images.githubusercontent.com/46235/142725970-cc0799c9-6665-45d4-b13a-cf931aad3fef.gif)

Looks like it's still an issue (although I would argue not the most pressing one :-) )

**Comment by timfel** [comment]
Fixed on master
