### ISSUE TITLE
Tyr's Hand map: rebels not attacking.

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#170]
On Tyr's Hand map the rebel peasants should be attacking. Instead, they either run to some nearby Orcs, who apparently are not on the same side despite being on the same side, and slaughter them, or they start chopping/mining (might depend on difficulty option). Either way, they should be attacking the player and the rescue-able faction.

BTW, please confirm if this is where Wargus is currently being developed... it seems you've moved quite a lot in the past and there are a lot of Wargus locations now! :)

**Comment by timfel** [comment]
The fix for this shouldn't be too hard, we'll just have to make them a separate unit type ("attack peasants"). I'll try to find time.

**Comment by Kintobor** [comment]
Attack peasants already exist. The unit just needs to be changed so it isn't a coward and doesn't gather resources.

**Comment by timfel** [comment]
Fixed
