### ISSUE TITLE
Main building upgrade fails: "upgrade to keep cancelled"

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#172]
Sometimes upgrading Hall->Keep or Keep->Castle fails. The resources are consumed, the upgrade bar finishes, but the building is unchanged and you can try again (and fail again). There's also a message, "upgrade to keep cancelled". It's kinda rare, happened twice so far for me per roughly 15 finished games. Including a savegame which always does it for me.

[buggy hall upgrade.sav.gz](https://github.com/Wargus/wargus/files/344484/buggy.hall.upgrade.sav.gz)

**Comment by mimooh** [comment]
This happens to me occassionaly, I confirm. I believe that in
multiplayer game some players see Castle and others see Keep as a result
:)

And answering your other question, yes, this is the place where Wargus
is currently developed.

-- 
Karol Kreński

**Comment by MarkusRamikin** [comment]
Good to know :)

**Comment by Go-rom** [comment]
Hello,

i'm encountering the same issue with the Great Hall. Did you find a workaround ?

Thank you

**Comment by Go-rom** [comment]
Hello,
here's a kind of workaround : build a second Great Hall then upgrade it, it should be ok.

**Comment by katastic** [comment]
I'm getting this bug in single player, alliance campaign, near end of campaign, where you rescue mages and peasants and take them back to your base to start building.

**Comment by katastic** [comment]
Building a new Keep fixed it. THANK YOU
