### ISSUE TITLE
[Bug? Feature request? You decide.] Spell autocasting during attack-move

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#175]
Spell autocasting doesn't work during attack-move, like it does in Warcraft III.

At this time autocasting seems to only happen when units are stopped, which is great for the defender, but less useful when you're attacking, or pretty much doing anything at all. Having mages cast Slow when attacking, whenever they see an appropriate target in range, would be great! Like Sorceresses did in Warcraft III.

**Comment by timfel** [comment]
Fixed.
