### ISSUE TITLE
Buggy transports

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#178]
A transport can become bugged, where it won't move and will immediately eject any passengers that board it. 

No idea how it happens, but I'm including a savegame. 3 out of 4 transports in that one are buggy! Also including replay, although it quickly gets out of sync for me.

[buggy transport.sav.gz](https://github.com/Wargus/wargus/files/344500/buggy.transport.sav.gz)
[transport bug.zip](https://github.com/Wargus/wargus/files/344502/transport.bug.zip)

**Comment by SimoneStarace** [comment]
#121 The bug is still present.

**Comment by timfel** [comment]
Duplicate of #121
