### ISSUE TITLE
RegenerationRate speed

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#19]
I noticed a little bug in RegenerationRate. It doesn't break the game, but make a big difference with Warcraft 2.
The RegenerationRate seems too fast. In the original WC 2 the berserkers regenerate 1 health every 2/3 second, here the minimum regeneration is 1 hp each second.

---

Imported from Launchpad using lp2gh.
- date created: 2011-03-15T23:25:22Z
- owner: rocadeier
- the launchpad url was https://bugs.launchpad.net/bugs/735816

**Comment by timfel** [comment]
(by pali)
It is only in last version 2.2.5.5 or in all old version too?

**Comment by timfel** [comment]
(by rocadeier)
In all versions.

**Comment by abenedic** [comment]
Is this still present? It maybe sounds like an int vs. float issue.

**Comment by timfel** [comment]
Fixed with https://github.com/Wargus/wargus/commit/45798240d1ab6ddfd04362d2f549bcc2cd3a10b7
