### ISSUE TITLE
Interface woes

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#191]
Main issue: you can't see the results when you're trying to use up/down arrows to select a savegame, or map. You're moving up or down the list, but there's no indication of that! At least until you tab out of that part of the interface, or move the mouse near it - it's kinda weird. 

More generally, if you're the sort of a person who prefers to mostly use the keyboard rather than mouse to navigate an interface, Wargus can be a pain in the ass.

While I'm here, gonna list all the little trivial things I noticed because they're not really worth seperate issues:
- can't choose things, e.g. load savegames or maps, by double clicking them
- can't just navigate to a savegame or map with arrows, then press Enter to load it
- can't use Escape to get out of menus
- would be nice to have Savegames listed latest-on-top, like in the original game
- would be nice if you could just hit F11, Enter, Enter in order to quickly save, like in the original game. 
- F11 then just start typing the new save game name.
- F11 then down arrow to start scrolling through saves. 
- can't save buildings as groups with control-#. Instead, there's some weird mechanic where produced units join a group, but it's less useful than it could be because it overrides existing groups instead of adding the newly produced units to an existing group (if it exists).

I imagine there are engine limitations behind at least some of this stuff, and yeah, it's mostly trivial. Just mentioning in case it's equally trivial to fix, since it's a good thing when a recode of an old game doesn't deviate from expectations if it doesn't need to.

**Comment by pasildan** [comment]
My friend I Just noticed the same problem about control + # . Once you have selected a building (for example town hall) and you select control + # then you have to press alt + # in order to access that building. It's really annoying because in any other RTS you can just press the selected number and boom, you got the building to make units, etc. I hope it can be fixed soon.

**Comment by timfel** [comment]
> can't choose things, e.g. load savegames or maps, by double clicking them

fixed

> can't use Escape to get out of menus

fixed

> would be nice if you could just hit F11, Enter, Enter in order to quickly save, like in the original game.

fixed

> F11 then just start typing the new save game name.

fixed

**Comment by timfel** [comment]
The group assignment thing was actually fixed in september 2016 with https://github.com/Wargus/stratagus/commit/d988d86b50cfeab9bcf2ba037a82f4e9f8b80654
