### ISSUE TITLE
Crash to Desktop on Assault on Blackrock Spire

### ISSUE THREAD

**Issue by MarkusRamikin** [Wargus/wargus#195]
No idea what causes it. It seems to happen just as an enemy transport touches a shore. Dunno if it matters that I managed to save Lothar. (Which, cough, shouldn't be possible.)

In this savegame the crash happens a few seconds after loading:
[crash to desktop.sav.gz](https://github.com/Wargus/wargus/files/344964/crash.to.desktop.sav.gz)

This is an earlier savegame from the same game, dunno if it'll be useful:
[h14hard a Lothar alive!.sav.gz](https://github.com/Wargus/wargus/files/344969/h14hard.a.Lothar.alive.sav.gz)

EDIT: 
Seems I can't finish this map no matter what, even if I don't try to save Lothar.
[ctd blackrock spire again.sav.gz](https://github.com/Wargus/wargus/files/346067/ctd.blackrock.spire.again.sav.gz)
[stdout.zip](https://github.com/Wargus/wargus/files/346076/stdout.zip) - should I be providing stdout.txt as well? (stderr.txt is empty)

Tentative guess that it might have something to do with transports, since there were enemy ones coming to shores like last time.

Can't progress the campaign, so I'm pretty much done for now.

**Comment by timfel** [comment]
The workaround I put in for saving Lothar is that the computer will now target him more aggressively than the normal knights, and all their HP are reduced immediately at the start of the game when they're being attacked, so they have little chance to escape
