### ISSUE TITLE
rip_music_unix.cpp fails to find the proper device when using actual cd

### ISSUE THREAD

**Issue by hanetzer** [Wargus/wargus#197]
Distro: archlinux (up to date as of 2016-07-11)
Installed via [stratagus-git](https://aur.archlinux.org/packages/stratagus-git) && [wargus-git](https://aur.archlinux.org/packages/wargus-git)

Real cd is in disk drive, but when using wartool to rip music it consistently tries to use `/dev/loop0` instead of `/dev/sr0` when calling cdparanoia; hardcoding line 263 to look at `/dev/sr0` does work, but it is a rather ugly hack.

Also, ffmpeg2theora fails on converting each ripped audio (wav) and vidio (smk) file for whatever reason, which leaves empty files in the videos folder, rendering the game unplayable until deleted.

**Comment by ntzrmtthihu777** [comment]
Seems the ffmpeg2theora bit is the same as #163 so I suppose that can be ignored for now, though I'd like to know how I can extract the smk files for the sake of testing and possbly helping fix the ffmpeg2theora issue upstream.

**Comment by timfel** [comment]
Re ffmpeg2theora: If you comment the removal of the smk files (see https://github.com/Wargus/wargus/issues/163#issuecomment-192681264) you can try to convert them by some other means.

**Comment by ntzrmtthihu777** [comment]
not worried about bugging you here about the ffmpeg2theora bit, that's beyond your control atm, but as I said, the above named file (`rip_music_unix.cpp`) consistently finds the wrong device to use cdparanoia on. Perhaps it would be best to be able to pass an explicit device name to wartool instead of attempting to auto-find the device.

**Comment by pali** [comment]
You need to specify path for extracting to real CD, not loop device. Code from rip_music_unix.cpp will read from device on which is path passed to wartool...

**Comment by ntzrmtthihu777** [comment]
As in, path to mount location? or, path to /dev/sr0? because I'm not finding that info anywhere.

**Comment by pali** [comment]
You should pass path to mounted location of /dev/sr0. From that path are read war files and also that path is converted to /dev/* device and from it is ripped audio CD.

**Comment by ntzrmtthihu777** [comment]
Which I have done, `sudo wartool -r -v /mnt/data /usr/share/games/stratagus/wargus` with `/dev/sr0` mounted at `/mnt` and yet it consistently tries to use cdparanoia on `/dev/loop0`

**Comment by pali** [comment]
Then there is bug either in find_mnt_dir or find_dev

**Comment by ntzrmtthihu777** [comment]
yep. which is what I've been saying. its finding the wrong device.

**Comment by timfel** [comment]
@ntzrmtthihu777 did `wartool -r -v /mnt` not work? it should look into the data subdir by itself

**Comment by pali** [comment]
Provide output of file /etc/mtab and mount command

**Comment by timfel** [comment]
Because I think find_dev definitely won't be able to find the correct device if you pass a subdir - https://github.com/Wargus/wargus/blob/master/rip_music_unix.cpp#L167 seems to compare the entire path for the mount

**Comment by ntzrmtthihu777** [comment]
https://gist.github.com/ntzrmtthihu777/ae159a372aea04d43110b69ade3be560

**Comment by ntzrmtthihu777** [comment]
huh. wartool without the data dir works, it seems. still gonna wait on that bit, but looks like it is working.

**Comment by ntzrmtthihu777** [comment]
Yep, that seemed to work. Now if we could get ffmpeg2theora to fix its issues that would be nice :)
I'd suggest an update to the readme

**Comment by pali** [comment]
@timfel find_mnt_dir is suppose to provide correct mount location, see: https://github.com/Wargus/wargus/blob/master/rip_music_unix.cpp#L101

So looks like bug is in find_mnt_dir function.

**Comment by ntzrmtthihu777** [comment]
Also, when attempting to extract against a BNE install (I have one from years back, but lack the cd anymore) I get the following: https://gist.github.com/ntzrmtthihu777/232d1c95c207a7000b4b16d328ed9e3f

**Comment by timfel** [comment]
@ntzrmtthihu777 i also get lots of such error messages with BNE CD, but it works afterwards. not the case for you?

**Comment by timfel** [comment]
@pali thank for the pointer, I will try to find time to fix this

**Comment by ntzrmtthihu777** [comment]
@timfel seems to be fine. On that note, is there any benefit of using BNE vs the classic dos? or is the end result the same?

**Comment by timfel** [comment]
@ntzrmtthihu777 the bne edition comes with both the ToD and BtDP campaigns. If you use the DOS CDs, you will have to extract twice to the same location (first ToD, then BtDP). The dpkg package should actually ask you for both cds if you select you have the dos cds including expansion.

**Comment by timfel** [comment]
Since this is working with the top dir, and the new launchers that we've had for a couple of years now pass that directory, it should "just work" now. the ffmpeg issue has been fixed by using plain ffmpeg and not ffmpeg2theora anymore
