### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by akien-mga** [Wargus/wargus#199]
It looks like there is now a 2.4 release of Wargus, but there is no tag/release in the GitHub repo, nor source tarball on the official website: https://wargus.github.io/

As I'd like to update my wargus Mageia package from 2.3.0 to 2.4, I'd like to have such an official release - unless 2.4 is still in development and the version number on the website just lacks a "-dev" suffix of some sort :)

As a side note, it's not easy to come by the "actual" infos of wargus, since the first match on Google is outdated: http://wargus.sourceforge.net/index.shtml

**Comment by mimooh** [comment]
@akien-mga, well, stable vs unstable releases are still to be sorted out. Currently we provide the unstable builds rather :( Except windows builds, which are properly tagged (see wargus.github.io). We are working on it.

wargus.sf.net and other places are still present, yes. We tried to reach admins of those sites to redirect to wargus.github.io which is the most current.

**Comment by timfel** [comment]
We're tagging releases on github, and I'm switching to adding a -dev postfix and version bump as the next commit, so the nightly names don't get confusing.
