### ISSUE TITLE
It's not clear how to use pudconvert correctly

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#200]
Hello, I'm using wargus 2.4, and when I try to convert a pud, it gives the error "smp file cannot created", and I cannot convert the puds.

**Comment by timfel** [comment]
Pudconvert is a bit obscure to use, I'll update the help text

**Comment by SpiReCZ** [comment]
this.. please

**Comment by timfel** [comment]
It's simply `./pudconvert path/to/pudfile.pud`. That'll create the stratagus map in the current directory. It doesn't work on Windows for some reason, but I'm sure we can fix that.

**Comment by SpiReCZ** [comment]
ah.. thanks, i remember it not working on windows a few years ago, but i thought i just don't know how to use it.

**Comment by SpiReCZ** [comment]
@timfel On windows 10 it does not work if the path is absolute. 

This example shows, that first two work and third doesn't.
powershell:
```powershell
C:\Users\user\Desktop\warcraft_ii\pud_convert> .\pudconvert.exe '.\Ant Trails BNE.pud'
C:\Users\user\Desktop\warcraft_ii\pud_convert> .\pudconvert.exe '.\maps\All You Need BNE.pud'
C:\Users\user\Desktop\warcraft_ii\pud_convert> .\pudconvert.exe 'C:\Users\user\Desktop\warcraft_ii\pud_convert\Ant Trails BNE.pud'
cannot open smpfile
```

**Comment by timfel** [comment]
@SpiReCZ ah, thanks for testing that out! That was the hint i needed. I pushed a fix. Now pudconvert will also print how to use it when you give it `-h` or `--help` or `/?` as only argument
