### ISSUE TITLE
Game crash on beyond the dark portal orc campaign mission #8

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#201]
I'm pretty sure that it has something to do with AI tables on that mission, but after a certain amount of cycles, the game just crashes without a single prompt. Removing certain AI schedules seem to speed up the time when the crash happens, so I'm pretty sure by now that the crash happens because of mission 8 AI table reasons. I just cannot find the thing that causes it. I've read on this github that some other campaign missions might be suffering from a similar bug as well.

I've fixed quite a few bugs about the mission triggers by myself, and I'm willing to share them if the creator of this wargus project wishes so.
Is there no one working on this project anymore btw? I don't see many activity here.

**Comment by timfel** [comment]
We'd be very happy to include your fixes if you want to share them. There
is not much activity, mostly because time is so limited and other work gets
in the way :(

**Comment by Erenussocrates** [comment]
Okay, I would gladly help in this, even though they are just mission triggers, and I'm not very experienced in helping with the hardcode. I'm new to github, how can I contribute my changes?

**Comment by timfel** [comment]
Are you familiar with the Github workflow? The core idea would be to fork the project (using the button on the top right) and the clone your fork. You make and commit your changes locally using git and then open a pull request using the button on the landing page of the repository.

Or, if you want you can just browse to the files you want to edit through the browser and edit them directly. It will automatically create a fork, commit your edits to that fork, and then open a pull request.

**Comment by Erenussocrates** [comment]
Okay, I'm committing somethings. But I feel like .sms files in campaign folder are missing. Can I make some changes. But I am unable to upload new files from my computer unfortunately. It says "Uploads are disabled.
File uploads require push access to this repository."

**Comment by eregimbald** [comment]
I'm running into the same issue. Is there something I can do?

**Comment by Erenussocrates** [comment]
I've solved the problem. You must remove the ballistaupgrade3 (ballista upgrade 3 doesn't exist) on _c.sms file of that mission.
