### ISSUE TITLE
Orc Campaign Briefing Music is wrong

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#208]
I do not know what you guys have been doing with the code that extracts the music and videos but I am having issues with the extraction process and the game.

Everytime I go to install Wargus now, ffmpeg2theora crashes when trying to extract every single video file. And in Wargus the music for the Orc Briefing is "I'm a Medievil Man" and not the normal "Orc Briefing" music.

And seriously Kintobor save the line you have mentioned in all my posts prior about this. It's lame. I just want this fixed like others do.

**Comment by Erenussocrates** [comment]
Go to > scripts > menus > campaign.lua file, and open it with notepad++ (the game will crash if you do it with regular notepad) 

So just at the beginning of the file, there will be this line: 
"wargus.playlist = {}
  if (CurrentCampaignRace == "human") then
    Load("scripts/human/ui.lua")
  elseif (CurrentCampaignRace == "orc") then
    Load("scripts/orc/ui.lua")
  else
    StopMusic()
  end
  PlayMusic("music/Human Briefing" .. wargus.music_extension) "

So, when you find that quote, just replace everything in the quotes with this one in the quotes: 

" wargus.playlist = {}
  if (CurrentCampaignRace == "human") then
    Load("scripts/human/ui.lua")
	PlayMusic("music/Human Briefing" .. wargus.music_extension)
  elseif (CurrentCampaignRace == "orc") then
    Load("scripts/orc/ui.lua")
	PlayMusic("music/Main Menu" .. wargus.music_extension)
  else
    StopMusic()
  end "

In order for this to work, your Main Menu music must be existent and working, ofcourse. Btw, I'm developing a mod for wargus and I've restored all the music and movies to the game, including beyond the dark portal cutscenes.

**Comment by DinkyDyeAussie** [comment]
The 'Main Menu" music is correct in the MIDI file version, but in the CD Music version it is "I'm a Medievil Man" Instead of the "Orc Briefing" music. Also my 'campaign.lua' file already contains the changes you have mentioned.

It is something in wartool that has been changed and is preventing the extraction process from working correctly and therefore stopping the music from being properly extracted. Namely 'Orc Briefing' is missing from my wargus music directory.

I will try and extract the music again and comment back on it.

**Comment by Erenussocrates** [comment]
My extraction didn't go wrong for some reason. (I actually forgot how I did it) You can also download the warcraft soundtrack from youtube (or any soundtrack that you want for that matter), change their format to .ogg online (without needing any additional software) , rename them and replace the soundtrack in wargus. That way, you can have correct soundtrack, and also would be able to put whatever you like.
I changed the ui_pandora.lua files in my wargus and added a few musics from warcraft 3 without replacing the original musics, for example.  

I think the reason why there is no orc briefing is because the original orc briefing music is actually exactly the same as the Main Menu music. That's why, I think.

**Comment by DinkyDyeAussie** [comment]
I was using the battlenet edition of warcraft 2 to do the extraction. I think I'll go back to the DOS  cds and donit again. Orc Briefing and the Main Menu music were both extracted a few versions ago. It's only recently that they changed the code to extract only the Main Menu music and that's wrong....as you already know.

**Comment by Erenussocrates** [comment]
Are you using wargus 2.4 ? BNE works perfectly on Wargus 2.4, I use both 2.4 and BNE, and they worked perfectly.

**Comment by DinkyDyeAussie** [comment]
Yep using the latest github version. Maybe I should erase everything stratagus and wargus? And start clean and fresh. I just want this stuff to work dammit!

**Comment by DinkyDyeAussie** [comment]
Tried a complete wipe of the game and re-downloaded the wargus2.4.exe file and tried reinstalling it. The extraction process on my PC is completely BROKEN. I cannot extract any videos except "logo.ogv" and then it says the ffmpeg2theora a has crashed and I click on close instead of debug and then it refuses to extract any more video files.

No music is extracted either. This sucks. Where did the process go so wrong? Erenussocrates please tell me how I can fix this up...

**Comment by Erenussocrates** [comment]
Just do what I did, get all the music and video files from internet and convert them to .ogg or .ogv respectively, so stratagus can open them ingame. That way, it works.

**Comment by DinkyDyeAussie** [comment]
No need. I changed stuff in the master branch and now it all works. Problem was wartool was creating a "Main Menu.ogg" twice. Once for the 'Orc Briefing' and another again for 'I'm a Medevil Man' so I edited the rip_music.h file and a few lua files and now it works as it should. Plus the extraction process works 100% now. At least for me. I'm happy now.
