### ISSUE TITLE
Unable to edit game files on the repository

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#209]
I tried today to edit some files in my bid to fix the main menu music issue - I have done so successfully on my own PC - but on Github it tells me that " you have to be a member to make or request changes to this file"

I thought I was? I seem to be able to change source-code files but not scripts? How do I "become a member" so I can make changes?

**Comment by timfel** [comment]
Sorry @DinkyDyeAussie, seems the permissions for the team weren't set correctly, should work now?

**Comment by DinkyDyeAussie** [comment]
All good now mate thanks. Sorry for the late reply too.
