### ISSUE TITLE
A question about creating my own spell

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#210]
Hello, I tried to create my own "Capture/Charm" spell that makes the target unit your own unit when you cast it.

http://pastebin.com/hSK3KZtw

this is an excerpt from magic.html inside stratagus/docs/scripts destination. Using that capture tag, I'm trying to create my own capture spell in wargus, but it seems to be not working. Here's what I wrote for creating the spell: 
http://pastebin.com/z8x9VbTN

I don't know why it doesn't work, but the game does not even open.﻿ If you have any idea about how this spell should work, could you tell me how to fix it?

**Comment by Mistranger** [comment]
Look at my Doom Wars, there is "Zombifie" spell, which allows Phantoms to zombify marine corpses by captufing them

**Comment by Erenussocrates** [comment]
@Mistranger, hello, thanks for showing your example of spell script to me. I've also downloaded and played Doom Wars as well, and took a look at the spells scripts. It was well done. Though, I can say, I didn't understand some of the tags in zombify spell. Though, I did my best to modify and change my spell as best as I could from the references I've taken, but the game still does not open I'm afraid, so I think I was still not successful.

Here's my new script for the spell:
http://pastebin.com/T3QWfFUh

Could you tell me what's specifically wrong with my script?

**Comment by Kintobor** [comment]
I think this is the problem:
     "action", {
        "capture", "spawn-missile", "missile", "missile-exorcism",
            "start-point", {"base", "target"}},

**Comment by Erenussocrates** [comment]
Okay, how should I write it as? I thought that the "capture" tag would do the trick by itself since it was documented in magic.html inside the stratagus documentation. I really don't know what to do other than that, I tried putting it inside a separate block, but it didn't work again :( Sorry, I'm new in this

**Comment by Erenussocrates** [comment]
The thing that I've asked is specifically which part of my code was wrong and had prevented to do what I've wanted it to do, but even though it should be a simple thing to explain or correct a single block in a single .lua file -provided that you are actually knowledgable about it- no one extends an actual helping hand about this in 2 days, even though it's literally about a single block in a single .lua file. 
This is not even the only instance of this lack of communication/aid. I've experienced this thing firsthand many more times before as well, and they only answer to the problems that are utmost simplest to solve.
This is the reason why stratagus modding/developing is frustrating me.

**Comment by DinkyDyeAussie** [comment]
The forum had more answers. Github is good though as it allows direct editing of the lua scripts, but it's not frequented much.

I found the same issue too. I'll have a look and see if I can help.

**Comment by Kintobor** [comment]
One day the forum will work again. One day.

**Comment by DinkyDyeAussie** [comment]
What files have you modified in your quest to write your own spell, Erenussocrates? I've been in the code and the scripts tonight and I am trying to figure this stuff out to try and help but I could use some pointers myself.

**Comment by Erenussocrates** [comment]
@DinkyDyeAussie , I modified scripts/spells.lua . and I modified scripts/orc/buttons.lua, and scripts/human/units.lua. I could have left buttons.lua out since I'm giving this spell to an enemy unit, but I just wanted to test the spell out so that's why.

Here's the block I've added in spells.lua : http://pastebin.com/CuQh0dHE 
I make constant changes in that in hopes to make it work but it won't.

Here's the block I've added in units.lua : http://pastebin.com/j37biNVC
Here's the block I've added in buttons.lua: http://pastebin.com/JkWjH5QU
Disregard the commented out lines, the game is supposed to run even with the commented out lines. But as long as the spell is not commented out/not fixed to work properly, the game will not open.

Btw, thank you DinkyDyeAussie

**Comment by Erenussocrates** [comment]
I used the "capture" tag because it is defined inside magic.html documentation of stratagus, but there are no examples about it. I lookt at Mistranger's code, and tried to copy a part of it (especially the capture tag and the tag that comes with it) but it obviously had some custom-made parameters, so I couldn't make the spell work that way. This is the excerpt from the magic.html that mentions about "capture" function:

" 
"capture", tag, ...
This will convert the target unit to the casters side. Very useful for capturing enemy buildings and controling enemy units. None of these tags need to be specified.
"damage", number
The amount of damage the unit takes before it is converted. Usually used with percent below
"percent", number
The precent of the target's total HP it has to be reduced below before it will be converted.
"sacrifice"
If this tag is given the caster will die after casting the spell.
 "

**Comment by timfel** [comment]
@Erenussocrates sorry for not being helpful, I understand your frustration, but real life gets in the way and such... 

Anyway, the first thing when the game doesn't even open is to check stdout and stderr. If you're on Windows, these should be in files in %appdata%\stratagus. On linux and osx, launch the binary from the command line to see the output. If it is syntax errors or some logical errors, there should be info in stderr.

**Comment by Erenussocrates** [comment]
@timfel I just checked stderr, and this is what it writes:

```
incorrect argument
stack traceback:
	[C]: in function 'DefineSpell'
	[string "scripts/spells.lua"]:659: in main chunk
	[C]: in function 'Load'
	[string "scripts/stratagus.lua"]:485: in main chunk
```

And this is what it writes in stdout:

C:\projects\stratagus\src\spell\script_spell.cpp:70: CclSpellAction: incorrect argument

**Comment by timfel** [comment]
Ok, looking at script_spell.cpp the error is that it expects a table as each element in the action description, not strings. The error message could be better.

If you look at the other spells, anything inside the table that comes after the "action" keyword is itself also a table. Often there is only one table, with "spawn-missile" and then the arguments for that. For your spell, you'll want two (compare e.g. the raise-dead spell). The first table will just say capture (you don't need the extra arguments) and the second table is your spawn missile.

```lua
DefineSpell("spell-charm",
            "showname", _("charm"),
            "manacost", 50,
            "range", 10,
            "target", "unit",
            "condition", {
               "opponent", "only",
                         },
            "action", {
               {"capture"},
               {"spawn-missile", "missile", "missile-exorcism", "start-point", {"base", "target"}}
            },
            "sound-when-cast", "exorcism",

            "autocast", {"range", 10, "condition", {"organic", "only", "opponent", "only"}, "position-autocast", SpellDeathCoil},
            "ai-cast", {"range", 10, "condition", {"opponent", "only"}, "position-autocast", SpellDeathCoil}
)
```

**Comment by timfel** [comment]
I changed the error message on master to tell you that it expected a table of tables for spell action.

**Comment by timfel** [comment]
Honestly, the entire custom DSL stuff in the spell definitions really isn't too great. There is an action "lua-callback" that just takes any lua function as argument. Back in the day (this is a *really old* codebase) calling back into lua for everything may have been prohibitive, but nowadays I find it is easiest to just put callbacks everywhere, and thus move all the game- or mod-specific stuff into the lua scripts. The nice thing about that is that you can even go and change the scripts while the game is running, by dynamically re-loading the lua scripts.

**Comment by timfel** [comment]
(I just realized I never posted this anywhere, so I'm putting it here before I forget).

To reload something dynamically (doesn't always work, but is often good enough), I just added this to cheats.lua:

```lua
  elseif (string.find(str, ".lua")) then
     AddMessage("Reloading " .. str)
     Load("scripts/" .. str)
  elseif (string.find(str, "eval") == 1) then
     local code = str:gsub("^eval%s", "")
     AddMessage("Running: " .. code)
     local result = loadstring(code)
     AddMessage(" => " .. tostring(result))
```

This way you can type a script path (under scripts/, without the scripts/-bit), and it will just reload that. Sometimes you'll have to reload multiple scripts (e.g. the spells and then the buttons that bind the spells), but you'll have to figure that out on your own. Reloading scripts that change the UI or the game loop might crash the game. Eval is useful to just run some lua code, e.g. to check the value of some game variable and such.

**Comment by Erenussocrates** [comment]
@timfel thank you very much. Now I've really made the spell work thanks to you. I didn't know that the alignment of the lines had mattered. But now, there's a new problem. The units that are cast charm do convert to your player. But oftenly they don't do anything at all. You can select them and hear their unit sounds, but they don't do anything and you cannot issue any order to them. Even the captured archers in shooting range of enemy don't do anything. Neither they do anything when an enemy attacks them. This happens very oftenly with the units that you capture using that spell, and you can issue orders to only a few random ones. This is also true for when the enemy captures your units. The captured units literally just stand there like statue and are not able to do anything at all. I wonder why? Do you have any idea about this issue?

**Comment by Erenussocrates** [comment]
Edit: I've found out that this is true for the units that have been issued an order before they were captured. Meaning, if there was an archer just standing there motionless and if you captured them, you can control them and issue orders to them just fine. But if they were on the move before you captured them (like moving, or about to attack you), you cannot control them after capturing them. They just stay wherever they are like statues. This situation is true for both human or computer players. If your unit was just staying there when the computer captures your unit(s), those units can attack your units when you get close to them. But if your units were on the move to attack them or on the way to somewhere before they get captured, computer's captured units just stay like statues as well. This is the issue.

**Comment by timfel** [comment]
@Erenussocrates no, alignment does not matter, the number of braces does. I may have confused you by mentioning the table datatype? It's a basic Lua data structure (delimited by curly braces), not an alignment thing.

About the capturing/commands issue, I'll see if I have time to look into it.

**Comment by Erenussocrates** [comment]
Okay, thank you very much. I will wait

**Comment by Erenussocrates** [comment]
@timfel any news?

**Comment by timfel** [comment]
Only that I couldn't reproduce the issue yet, but I only had about an hour
to spend on this. There's another project that's getting late for me, so I
don't think I'll have time until end of October at the earliest

Erenussocrates <notifications@github.com> schrieb am Sa., 24. Sep. 2016,
16:27:

**Comment by Erenussocrates** [comment]
so you mean, in your version the units who were charmed are not completely disabled if they were charmed during performing an action?

**Comment by Erenussocrates** [comment]
@timfel could you look at my issue yet? Please, I need help in this.

**Comment by Erenussocrates** [comment]
Please .

**Comment by timfel** [comment]
I have not been able to reproduce your issue. But if your bug report is correct, and it really only applies to units that are currently not standing still, you could try this:
```lua
local function OrderUnitStop(spell, caster, x, y, target)
   if target ~= -1 then
      local unitowner = GetUnitVariable(target, "Player")
      local unittype = GetUnitVariable(target, "Ident")
      OrderUnit(unitowner, unittype, {x, y}, {x, y}, "move")
   end
   return false
end

DefineSpell("spell-charm",
            "showname", _("charm"),
            "manacost", 50,
            "range", 10,
            "target", "unit",
            "condition", {"opponent", "only"},
            "action", {
               {"lua-callback", OrderUnitStop},
               {"capture"},
               {"spawn-missile", "missile", "missile-exorcism", "start-point", {"base", "target"}}},
            "sound-when-cast", "exorcism",
            "autocast", {"range", 10, "condition", {"organic", "only", "opponent", "only"}, "position-autocast", SpellDeathCoil},
            "ai-cast", {"range", 10, "condition", {"opponent", "only"}, "position-autocast", SpellDeathCoil}
)
```

This should definitely clear the unit orders and order the targeted unit to move to it's current position, that is, it should stop.

If all else fails, you might be successful with a hammer:
```lua
local function ChangeUnitOwner(spell, caster, x, y, target)
   if target ~= -1 then
      SetUnitVariable(target, "Player", GetUnitVariable(caster, "Player"))
   end
   return false
end

DefineSpell("spell-charm",
            "showname", _("charm"),
            "manacost", 50,
            "range", 10,
            "target", "unit",
            "condition", {"opponent", "only"},
            "action", {
               {"lua-callback", ChangeUnitOwner},
               {"spawn-missile", "missile", "missile-exorcism", "start-point", {"base", "target"}}},
            "sound-when-cast", "exorcism",
            "autocast", {"range", 10, "condition", {"organic", "only", "opponent", "only"}, "position-autocast", SpellDeathCoil},
            "ai-cast", {"range", 10, "condition", {"opponent", "only"}, "position-autocast", SpellDeathCoil}
)
```

Or, in the worst piece of code (and that is a low bar in these three):
```lua
local function ChangeUnitOwner(spell, caster, x, y, target)
   if target ~= -1 then
      local hp = GetUnitVariable(target, "HitPoints")
      local id = GetUnitVariable(target, "Ident")
      RemoveUnit(target)
      local newunit = CreateUnit(id, GetUnitVariable(caster, "Player"), {x, y})
      SetUnitVariable(newunit, "HitPoints" hp)
   end
   return false
end

DefineSpell("spell-charm",
            "showname", _("charm"),
            "manacost", 50,
            "range", 10,
            "target", "unit",
            "condition", {"opponent", "only"},
            "action", {
               {"lua-callback", ChangeUnitOwner},
               {"spawn-missile", "missile", "missile-exorcism", "start-point", {"base", "target"}}},
            "sound-when-cast", "exorcism",
            "autocast", {"range", 10, "condition", {"organic", "only", "opponent", "only"}, "position-autocast", SpellDeathCoil},
            "ai-cast", {"range", 10, "condition", {"opponent", "only"}, "position-autocast", SpellDeathCoil}
)
```

**Comment by Erenussocrates** [comment]
Okay, so I'm going to put that extra line of code in the spells.lua just above the usual charm spell, right? (I mean, ofcourse also making edits to the original charm spell where it's due, like the lua callbacks) Not anywhere else?

**Comment by Erenussocrates** [comment]
@timfel thank you very much, friend. Thanks to you, I did it. The first block of codes does not work for some reason, though. The same problem persisted on that one, so I'm pretty much sure it's the built-in "capture" spelltag's fault. 
So I've tried 2nd one instead. It was all good, except that the captured units persisted having their previous commands. So for example, if computer opponent had a mage who is able to cast Charm, and when he took over your unit, if you've ordered your footman to attack that mage just before they got captured, they still went on killing the mage and computer does not stop the newly acquired unit. That was the problem. 
I've tried 3rd one, and that flatout just didn't work. Game didn't open at all. stderr file says I'm missing a ")" after the word "hp". I couldn't spot the problem.
So then instead I decided to try merging the 1st and 2nd methods together, and it has better results, but unfortunately it still isn't faultless.
When the enemy casts that spell on one of your units while that group of units are under your selection, you can still use them and issue commands to them until you deselect them yourself. Meaning, you can use them to move or attack, or anything basically. You can command them to attack the mage who casted that spell, they will go and kill the mage themselves after killing your units which are still under your control.

So yeah, there's still one remaining problem, and that problem is that the unit(s) affected by that spell should immediately be deselected for this spell to work as intended. Do you have any idea about how to accomplish that?
Btw, thank you very much for your help again, I really appreciate it.

**Comment by timfel** [comment]
There was a comma missing in the third one:
```lua
local function ChangeUnitOwner(spell, caster, x, y, target)
   if target ~= -1 then
      local hp = GetUnitVariable(target, "HitPoints")
      local id = GetUnitVariable(target, "Ident")
      RemoveUnit(target)
      local newunit = CreateUnit(id, GetUnitVariable(caster, "Player"), {x, y})
      SetUnitVariable(newunit, "HitPoints", hp)
   end
   return false
end

DefineSpell("spell-charm",
            "showname", _("charm"),
            "manacost", 50,
            "range", 10,
            "target", "unit",
            "condition", {"opponent", "only"},
            "action", {
               {"lua-callback", ChangeUnitOwner},
               {"spawn-missile", "missile", "missile-exorcism", "start-point", {"base", "target"}}},
            "sound-when-cast", "exorcism",
            "autocast", {"range", 10, "condition", {"organic", "only", "opponent", "only"}, "position-autocast", SpellDeathCoil},
            "ai-cast", {"range", 10, "condition", {"opponent", "only"}, "position-autocast", SpellDeathCoil}
)
```

**Comment by Erenussocrates** [comment]
@timfel that one now works, but still not as intendedly, unfortunately. When enemy casts the spell on my unit, I lose the ownership of my unit, but the unit is not removed, and a new unit of the same force as the enemy is created. The new created unit works as intendedly, but my own captured unit is not removed, even though I've lost it's ownership. And it's weird, the unit is not neutral neither, I cannot even target my other units to kill it neither. It's like, the spell is creating another unit of the same kind out of the targeted unit while rendering the target totally untouchable.

**Comment by timfel** [comment]
@Erenussocrates wait for the new build to run through, i just pushed a change

**Comment by Erenussocrates** [comment]
@timfel, alright, that sounds awesome. Where could I notice if there's a new version?

**Comment by timfel** [comment]
Replace your Wargus' stratagus.exe with the one from here: https://github.com/Wargus/stratagus/releases/download/master-builds/compiled-binaries.zip

**Comment by Erenussocrates** [comment]
@timfel you are very great! thank you very much, you rock, I really appreciate it, thank you so much friend, my spell finally works as how I've intended without any errors

**Comment by Erenussocrates** [comment]
btw that new patch you've released, by any chance could it also be a fix for btdp human mission 10 freezing?

**Comment by timfel** [comment]
@Erenussocrates no, the patch has nothing to do with freezing.
