### ISSUE TITLE
I have a problem creating a new building type that trains units

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#211]
Hello, I've created a duplicate Dark Portal unit called "unit-dark-portal-2" , and I'm trying to make it be able to train daemons, but no matter what I've done, I could not make it be able to train daemons. It does not have the train unit icon/order when you select the building.

http://pastebin.com/Ti1kYhT6

As you can see, the code I've written to create the duplicate dark portal should be okay. (it goes in "units.lua") And this is the code I've written for scripts/buttons: (this one goes in "buttons.lua")

http://pastebin.com/UDfj4Ah4

I've tried copying and pasting both the dark portal unit declaration and the train button declaration in scripts/orc , and commenting out the previous ones, but it still doesn't work. Btw, I want this to work in orc expansion mission 12. (don't worry, I actually replaced the default dark portal with the new one) Does anyone know how I could enable this building type unit to be able to train daemons? I really need help with this.

**Comment by Kintobor** [comment]
DefineAllow("unit-daemon", "AAAAAAAAAAAAAAAA")﻿

**Comment by Erenussocrates** [comment]
How could I forget something so simple? Dude I could kiss you right now, thank you very much, it works perfectly now
