### ISSUE TITLE
I need assistance with re-compiling action_train.cpp into wargus.exe

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#212]
Hello, in order to fix the alt+number selecting buildings in control groups problem, I modified action_train.cpp in stratagus directory, using Visual Studio. And I guess I need CMake gui as well, for the next step. But I don't know what to do in next step to re-compile this edited action_train.cpp into wargus.exe, and I might need assistance. Could someone give me step by step instructions?

Edit: btw, I also made the buildings that trains units selectable by rectangle in units.lua. I also want to make the buildings be able to train the same units when you select a number of them. But I don't know what line I should add/remove in order to accomplish that in action_train.cpp. Could someone lend me a hand at that as well?

**Comment by timfel** [comment]
You can look at the appveyor script to see how the visual studio project is prepared: https://github.com/Wargus/stratagus/blob/master/appveyor.yml. It's basically downloading the dependencies, running cmake to prepare the visual studio project, and then uses visual studio to compile the new stratagus binary

**Comment by DinkyDyeAussie** [comment]
I did all of that earlier to stratagus mate. It's all working now. Thanks to help from Andrettin.
