### ISSUE TITLE
2.4.1 release

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#215]
Always wondered... do we just s/2015/2016/ for all on the list below? I just care about the startup of wargus and I don't like it saying -2015. 

I understand stratagus 2.4.1 will be also released, since debian requires it during installation. 

When it comes to the changelog I think it is worth noting that network out-of-sync is finally fixed, as it is the biggest bugfix!

./scripts/stratagus.lua:	wargus.Copyright = _("(c) 2012-2015 by The Stratagus Project.")
./scripts/stratagus.lua:	wargus.Copyright = _("(c) 1998-2015 by The Stratagus Project.")
./scripts/wc2.lua:--      (c) Copyright 2001-2015 by Lutz Sammer, Jimmy Salmon and Kyran Jackson.
./scripts/guichan.lua:--      (c) Copyright 2006-2015 by Jimmy Salmon, Pali Rohár and cybermind
./scripts/menus/campaign.lua:--      (c) Copyright 2006-2015 by Jimmy Salmon, Pali Rohár and cybermind
./scripts/menus/options.lua:--      (c) Copyright 2006-2015 by Jimmy Salmon, Pali Rohár, Kyran Jackson and cybermind
./scripts/menus/network.lua:--      (c) Copyright 2005-2015 by François Beerten, Jimmy Salmon, Pali Rohár
./scripts/menus/credits.lua:--      (c) Copyright 2006-2015 by Jimmy Salmon, Pali Rohár and cybermind
./scripts/translate/ru_RU.po:msgid "(c) 2012-2015 by The Stratagus Project."
./scripts/translate/ru_RU.po:msgstr "(c) 2012-2015 by The Stratagus Project."
./scripts/translate/ru_RU.po:msgid "(c) 1998-2015 by The Stratagus Project."
./scripts/translate/ru_RU.po:msgstr "(c) 1998-2015 by The Stratagus Project."
./scripts/ai.lua:--      (c) Copyright 2000-2015 by Lutz Sammer, Jimmy Salmon, 
./wartool.cpp://      (c) Copyright 1999-2015 by Lutz Sammer, Nehal Mistry, Jimmy Salmon,
./wargus.nsi:!define COPYRIGHT "Copyright (c) 1998-2015 by The Stratagus Project"
./wartool.h://      (c) Copyright 1999-2015 by Lutz Sammer, Nehal Mistry, Jimmy Salmon,

**Comment by timfel** [comment]
Yes, lets just update the year. The 2.4.1 release was also a test of the
new releases pipeline for our builds. I'm hoping to automate that some
more, so we can have smaller, more frequent releases.

mimooh <notifications@github.com> schrieb am Di., 8. Nov. 2016, 17:38:

**Comment by mimooh** [comment]
@timfel, you're aware that stratagus 2.4.1 needs to be released as well, right?

apt-get install wargus
Reading package lists... Done
The following packages have unmet dependencies:
 wargus : Depends: stratagus (>= 2.4.1~0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by timfel** [comment]
Yeah, sorry, there was a build issue with the packages. It should be fixed now, and the packages have just rebuilt and 2.4.1 was uploaded.
