### ISSUE TITLE
The new installer

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#218]
After apt-get install wargus:

Template #1 in /var/lib/dpkg/info/wargus.templates does not contain a 'Template:' line
dpkg: error processing package wargus (--configure):
 subprocess installed post-installation script returned error exit status 255
Errors were encountered while processing:
 wargus
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by timfel** [comment]
Sorry, I left master in a broken state. This should be fixed by now, but now the ppa is down... :(

**Comment by mimooh** [comment]
> Sorry, I left master in a broken state. This should be fixed by now,
> but now the ppa is down... :(
I prefer to have those new features for testing, so do commit to master! :)


-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment]
it works
