### ISSUE TITLE
https://launchpad.net/~stratagus/+archive/ppa not found

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#219]
And it used to be the place for ubuntu builds:

Nightly builds are available:

    Windows Installer: https://github.com/Wargus/wargus/releases/tag/master-builds
    Ubuntu/Debian Packages: https://launchpad.net/~stratagus/+archive/ubuntu/ppa
    OS X App Bundle: https://github.com/Wargus/stratagus/wiki/osx/Wargus.app.tar.gz

**Comment by timfel** [comment]
Yeah, i just noticed that an hour ago, no idea what happened, I sent an email to the launchpad admins of the stratagus team :(

**Comment by timfel** [comment]
maybe @pali knows

**Comment by pali** [comment]
No idea, even me as admin does not see that ppa -- which means somebody must have delete it. I have not done anything. You need to ask other admins: https://launchpad.net/~stratagus/+members

**Comment by timfel** [comment]
It should be back, I think cybermind re-enabled it

pali <notifications@github.com> schrieb am Mo., 21. Nov. 2016, 12:48:

**Comment by mimooh** [comment]
it works
