### ISSUE TITLE
Farms calculated wrong

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/wargus#220]
It seems to be the case that farms are not calculated accurately in Wargus, It seems to be the same Supply: 4 and Demand 0 error.

**Comment by mimooh** [comment]
I don't quite understand. I believe there's always one farm per 5 units. Is it otherwise in your games?

**Comment by Zombie-Ryushu** [comment]
You need a Rescue Active ally to see the bug, Supply will always be 4, Demand will always be 0 regardless of what units you or your enemy has.

**Comment by mimooh** [comment]
What is "Rescue Active ally"? I play multiplayer mostly. Is it some
single player mission?

-- 
Karol Kreński
tel. 517-302-055

**Comment by Zombie-Ryushu** [comment]
Yes, but its not unique to one mission.

**Comment by mimooh** [comment]
I start single player > campaign and then where do I look for this bug?

**Comment by Zombie-Ryushu** [comment]
Click on a farm. Demand will be 0, Supply willbe 0

**Comment by timfel** [comment]
Fixed in https://github.com/Wargus/wargus/commit/932c4974dfea9805f6710f254de191e65dadb50d
