### ISSUE TITLE
status bars under units gone under linux

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#221]
I removed my ~/.stratagus/wc2/preferences.lua, but still I don't have the status bars under peasants that chop wood, or under buildings producing units and elsewhere. Under windows the status bars are present. It is either my setup or some last commits. Any idea?

**Comment by timfel** [comment]
None of my commits in the last few months should have anything to do with that.

**Comment by timfel** [comment]
I'm closing this now, because it's been a long time and I haven't seen this on any installation since
