### ISSUE TITLE
New Segfault under Linux with latest git pull scripts

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/wargus#222]
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt full
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00000000006f954d in LoadShaders(int, char*) ()
No symbol table info available.
#2  0x00000000006f6e05 in SwitchToShader() ()
No symbol table info available.
#3  0x0000000000730970 in tolua_stratagus_SwitchToShader00(lua_State*) ()
No symbol table info available.
#4  0x0000003ab680c3f9 in ?? () from /usr/lib64/liblua.so.5.1
No symbol table info available.
#5  0x0000003ab6816a6a in ?? () from /usr/lib64/liblua.so.5.1
No symbol table info available.
#6  0x0000003ab680c82d in ?? () from /usr/lib64/liblua.so.5.1
No symbol table info available.
#7  0x0000003ab680bb4b in ?? () from /usr/lib64/liblua.so.5.1
No symbol table info available.
#8  0x0000003ab680c99b in ?? () from /usr/lib64/liblua.so.5.1
No symbol table info available.
#9  0x0000003ab680883c in lua_pcall () from /usr/lib64/liblua.so.5.1
No symbol table info available.
#10 0x000000000064bd98 in LuaCall(int, int, bool) ()
No symbol table info available.
#11 0x000000000064c1a3 in LuaLoadFile(std::string const&, std::string const&) ()
No symbol table info available.
#12 0x0000000000655413 in LoadCcl(std::string const&, std::string const&) ()
No symbol table info available.
#13 0x0000000000661ee5 in stratagusMain(int, char**) ()
No symbol table info available.
#14 0x0000000000645686 in main ()
No symbol table info available.

This happened after the latest git pull.

**Comment by timfel** [comment]
Sorry, this has been fixed.
