### ISSUE TITLE
http://forums.stratagus.com/ not working

### ISSUE THREAD

**Issue by Phantomb** [Wargus/wargus#227]
The forums is not working for me. I get this message:
"The web service to this account has been limited temporarily!
There is a server resource overage report open for this account in the User area. To remove the limits, please log into your User area and consider the options available to resolve the case."

**Comment by Kintobor** [comment]
Posted on 16 Jan, 2017, 10:03

Your account stratagus.com has reached 100% of the monthly quota of 300000 program executions and your web service is limited for the calendar month. The limit will be removed automatically at 00:10 a.m. CDT on the first day of the next calendar month and service will be fully restored.

Allowed Quota: 300000 script executions/mo
Your Current Usage: 301429 script executions/mo

The web service limit means you might be having problems accessing your website, but all other services such as email, cPanel or else are active and available for you.

To reactivate service and resolve the high usage, please consider the following options:

1. Optimize your website to decrease number of script and program executions. We have noticed that the majority of the causes for increased executions are easy to prevent by optimizing the code of your website. If you need assistance, our technicians are available to help you. You can also find more information here:

https://www.siteground.com/tutorials/cpanel/statistics.htm
http://www.siteground.com/tutorials/websiteperformance/reduce-executions.htm

2. Upgrade your account to a plan with a higher monthly number of executions allowed. We recommend this option if your account is going to need more resources on a regular basis.

**Comment by Kintobor** [comment]
We're too popular for our own good.

**Comment by Phantomb** [comment]
Oh wow that's pretty annoying. I assumed it was abandoned or something. I tried accessing forum posts through archive.org, but far from everything was on there. Are there any other places I can go to ask questions / find the community?

**Comment by Phantomb** [comment]
@Kintobor Could you direct me to where I can ask questions / get help if the forum is not working? I feel like the issuetracker is not the appropriate place for that.
I've got questions about using wargus for AI research (which I know has been done a lot):
- In the .lua ai scripts: can I use other functions than only the 'game-commands'? Such as saving float variables / arrays / calculations? Or would I need to get in to the source for that? (If so, some pointers would be appreciated).
- Can the game run computer vs. computer (or even only a single computer)?
- Can the game run without rendering, fast forwarding the timesteps?
Thanks!

**Comment by mimooh** [comment]
This paper covers some of your questions:
http://www.cc.gatech.edu/~surban6/publs/IJCAI05.pdf

Also, the github's issue tracker served as a place for some lenghty discussions before, so you are welcome.

**Comment by Kintobor** [comment]
You can make your own functions.
You can run the game as computer vs. computer.
I know running the game without rendering has been discussed either here or at the forums.

**Comment by Kintobor** [comment]
I've purchased a new rack server. I may move the forum to it if this continues.

I found the following advice: "Couple of things to reduce executions in phpbb is to disable the search, and turn stuff off in acp on server load, and optimize mysql in phpmyadmin, use a robots.text file to get rid of robots/spiders etc, also ban ips that appear in honeypot also dont have gzip compession enabled in acp, turn off robots/spiders in the forum acp as well."

**Comment by mimooh** [comment]
We have a VPS for stratagus. It is ubuntu with root access, not sure
about network traffic limits. Just in case.

-- 
Karol Kreński
tel. 517-302-055

**Comment by Phantomb** [comment]
From that paper you shared, I read the following quote:

>  _Fast mode:_ Stratagus includes a fast forward mode
where graphics are partially turned off, resulting in
fast games. This is particularly useful for expediting
experiments.

So apparently it should be possible. Could you instruct me how I can do that in Wargus?

I also haven't been successful in starting a computer vs. computer match. Can that maybe only be done with a specific game mode? Could you tell me where to start that?

Thanks for the replies, all. I hope the forums come online again soon!

**Comment by mimooh** [comment]
I know very little of stratagus internals, I cannot help you. Perhaps
you could reach the authors of the paper?

-- 
Karol Kreński
tel. 517-302-055

**Comment by Phantomb** [comment]
re: addressing paper authors: Unfortunately, I've already mailed the authors of a few papers who have used Wargus in recent years, and have not been able to get a hold of anyone.

re: AI vs AI play: If anyone can direct me how to start a game without a human player (preferably both the case of two AI's and the case of a single AI (e.g. just doing some resource gathering)), that would greatly be appreciated. Or is the 'solution' something as mundane as starting with a human player, and then let that do nothing?

re: Fast forwarding without rendering, can I still fast forward gameplay, even if I can't turn off rendering? If so, how?

And just so I understand it correctly: the forum will go online again at the start of the next month? And it is still active there with either information or people willing to help? Thanks for the assistance!

**Comment by Kintobor** [comment]
You can have Ai vs Ai by allying yourself with both Ais.

In the options there is a control for the game speed. You can manually set this higher via scripts.

The forum has plenty of old discussions talking about exactly what you want to do. It should be up at the start of next month.

**Comment by Phantomb** [comment]
Okay, thanks for the quick replies. Just waiting on the forum now :)

**Comment by Kintobor** [comment]
What is the VPS used for?

**Comment by mimooh** [comment]
It was supposed to be a testing and then production environment for the metaserver
so that players could join online wargus games. But people are currently
busy, so there's not much progress in metaserver. The VPS can be used
for other Wargus purposes.

-- 
Karol Kreński
tel. 517-302-055

**Comment by Kintobor** [comment]
Okay, I think I've fixed the servers load problems. I've disable guests from being able to read the forums.

Also, I've announced a little something here: http://forums.stratagus.com/viewtopic.php?f=42&t=3735
