### ISSUE TITLE
Is there a way to make the in-game "Scenario Objectives" window scrollable?

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#229]
As the title asks.

This is a minor thing, but would definitely be helpful if we could somehow solve this issue, so it would give me more writing space when I'm writing the mission objectives.

**Comment by timfel** [comment]
Sure, take a look at how the help menu uses a ScrollArea around its text.

**Comment by Erenussocrates** [comment]
Okay, where do I look at that?

**Comment by Erenussocrates** [comment]
Umm?

**Comment by timfel** [comment]
Not copy and pasting. I'd recommend you play with the screen you want to change. Get a feel for what does what. Then play with the scroll area in the credits. See how it wraps the text widget in the scroll area. Then apply one to the other by playing with it.

**Comment by timfel** [comment]
I guess playing is a bit ambiguous in this context. I mean it in the "playing with the code" way
