### ISSUE TITLE
Issue installing v2.4.1 on macOs Sierra

### ISSUE THREAD

**Issue by ahelal** [Wargus/wargus#230]
Not sure if it's an issue trying to Install on Mac. 
Always gives ```Wargus data was not extracted, is corrupted, or outdated.
You need to extract it from original Warcraft II DOS REZDAT.WAR or BNE Battle.snp file. Please select the Warcraft II DOS REZDAT.WAR or BNE Battle.snp file``` Tried to use the GUI file location  to select *rezdata.war* I get ```There was an unrecoverable error copying the data```. 

If i use ```./wartool /path/data ./data```  it does a bunch of archive and ignore then says Done, but still games fails to load with same error ```Wargus data ...``` not sure where the data dir should be?
Any idea  what did I do wrong.

**Comment by timfel** [comment]
Hi, sorry for not getting back. The data should be extracted to $HOME/Library/Stratagus/data.wc2. Can you also post username and location of the Wargus.app? Tracking what might be the same bug in #252

**Comment by timfel** [comment]
Another question, did you try launching from the Downloads folder? If yes, try moving the Wargus.app explicitly into the Applications folder. The app doesn't work correctly with the sandbox feature of newer macos releases.

**Comment by vladimirponomarev** [comment]
I managed to run the game after copying the data directory to $HOME/Library/Stratagus/data.Wargus (not data.wc2). But still had to use Wine and the Windows version to extract data from a Warcraft 2 Image.

**Comment by Njordy** [comment]
"There was an error copying the data, could not discover contributed directory path."

**Comment by ChiefPoints** [comment]
Seeing the same issues on MacOS Sierra 10.12.6 through the latest version. The latest package for Wargus was showing as corrupt, I had to view the contents and pull the Wargus.app from there. Looks like it was double packaged maybe. Once I got it pulled out of there I'm seeing the same thing everyone else is when run from the Applications direction. It creates the Stratagus directory under $HOME/Library, but that's as far as it gets. I've got a test VM running Windows10 and was able to extract data that way to toss into retropie. I had to the the same with Warcraft 1. Sure looks a lot that bug similar report for El Capitan that's referenced above. Compatibility seems to be quite the headache with Mac these days.

**Comment by benhbell** [comment]
Confirmed that adding the extracted data to 
`$HOME/Library/Stratagus/data.Wargus`
will allow the game to run on Mac 10.13.16

**Comment by SimoneStarace** [comment]
Shouldn't this issue be closed since it was confirmed by @benhbell himself?

> Confirmed that adding the extracted data to
> `$HOME/Library/Stratagus/data.Wargus`
> will allow the game to run on Mac 10.13.16

Did you also test on **Version 3.0.0**?

**Comment by timfel** [comment]
Yes, this issue should be closed, since we cannot support macOS right now.
