### ISSUE TITLE
Stratagus  2.4.1 Fresh install won't let me select Campaign maps.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/wargus#231]
Stratagus  2.4.1 Fresh install won't let me select Campaign maps. Only "For the Motherland"  is accessible.  all other games simply kick you back to the main menu.

**Comment by Zombie-Ryushu** [comment]
It just sort of started partly working after copying over the LUA Scripts.

**Comment by Kintobor** [comment]
Some campaigns are only supposed to work with Wargus. If the Aleona's Tales flag is set, those campaigns kick you back to the main menu.
