### ISSUE TITLE
RangeTargetFinder::FillBadGood.Compute out of Range

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/wargus#233]
RangeTargetFinder::FillBadGood.Compute out of Range errors will absolutely innundate the terminal screen and cause 20% CPU Utilization of a 4 Core system on a complex map.

**Comment by timfel** [comment]
Fixed with https://github.com/Wargus/stratagus/commit/b18818d8a88798a5e71ed1a7f8398ce1918f9abe
