### ISSUE TITLE
Upgrade sounds?

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#234]
In the game, when an upgrade is done, a notification sound does not play, unlike when you are being attacked or if a unit is trained. How to implement that?

**Comment by doomguy** [comment]
I guess you need to look into the code of building/upgrading and catching the 100% complete event to play your sound. Not sure where to look for this, though.

**Comment by timfel** [comment]
Take a look at https://github.com/Wargus/wargus/blob/master/scripts/sound.lua#L816. You have to define a research-complete sound. See here for the kinds of sounds you can define: https://github.com/Wargus/stratagus/blob/1e798a7309aa2c1dc4b2ef1c1498864d4fa3ab73/src/sound/script_sound.cpp#L273

**Comment by timfel** [comment]
Related: #173

**Comment by timfel** [comment]
Fixed in trunk, the research upgrade sound is now set to work completed, and for humans building the sound is the "jobs done" from the peasants
