### ISSUE TITLE
Installing and Compiling Wargus and Stratagus on lubuntu 16.04

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#236]
I installed lubuntu on an old laptop. It's running great, but I really have no idea on what to do when it comes to compiling and installing libraries for linux so I can compile the game on linux. I am a COMPLETE NOOB with linux. I have NEVER used it.

Does anyone have a complete zip file of all the libraries I need to compile? Also could someone give me a detailed list of instructions on how to get this stuff working please?

**Comment by mimooh** [comment]
You may find this site useful:
http://wargus.github.io/faq.html

-- 
Karol Kreński

**Comment by DinkyDyeAussie** [comment]
I'm sure I checked that out yesterday and tried to do it. I will try again later on. I managed to install quite a few libraries for the compiling process when I went to try and install Wyrmgus and Wyrmsun on my laptop, so I will try again later with Wargus and Stratagus.

Cheers :+1:

**Comment by timfel** [comment]
Since more concrete problems are tracked in other issues, I'm closing this.
