### ISSUE TITLE
lua files incompatable

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#239]
Running 2.4.1 on two seperate laptops, I managed to get them connected and fired up wargus on both, using the latest version. I had a go at setting up a network game and was only able to get a game working once, when I deleted both 'preference.lua' files on each laptop. Now it won't work again because it says the "LUA files incompatible"

What else do I do besides delete preferences every time? I copied the campaign and script files over from one to the other too, so they're all the same now...

**Comment by DinkyDyeAussie** [comment]
So I did some more testing on this. I re-edited the mission files and got rid of the `local cycle2win` and reset the `return ActionVictory() end)` to default like they are on a fresh install. Fired up Wargus on both laptops and created a game on one then tried to join on the other. No go, as I got the 'lua files incompatible' message again. 

I then swapped them, creating on the other one and joining on the first one. Did it again. So I reinstalled the same version of stratagus and deleted 'preferences.lua' from `%appdata%/roaming/stratagus/wc2` on both machines. Fired up the game again on both, and it worked! Created a game, joined it on the other laptop and it went in. So I thought "Sweet!, I'll just put the game into fullscreen native resolution on both laptops and try it again...

...Didn't work after that. For some reason stratagus stuffs something up when you change a small detail. I made sure my video settings and my preferences were all identical on both machines and I am definitely NOT using the wrong I.P numbers for the appropriate system.

I cannot figure out... I checked stderr.txt and it said this...

`Incompatible Lua files version 206415742 <-> 187934585`

So somewhere in some file, changing your video and preference setting mcuks around with the lua compatability. I swear this never happened before, not even in 2.4.0

**Comment by timfel** [comment]
This sounds like this issue: https://github.com/Wargus/stratagus/issues/196

**Comment by timfel** [comment]
Are you sure you're using the latest version on both systems? Using the same version if those versions did checksumming will not be enough

**Comment by DinkyDyeAussie** [comment]
Positive I am using the same version. I installed wargus/stratagus on one laptop and then copied those files onto the other alptop and did the same thing.

**Comment by mimooh** [comment]
You need to use the latest version. Not just the same version. As @timfel said. The checksuming went wrong and was disabled at some point in v2.4.1.

**Comment by DinkyDyeAussie** [comment]
I ended up downloading the master-build. Will see how that goes.

**Comment by DinkyDyeAussie** [comment]
So I installed the Master-Build of wargus and stratagus and instead of extracting all the warcraft data during the install, it now does it afterwards and also installs that gay freecraft media. Can you change it back to the way it installs with the release version of 2.4.1 please? I want pure warcraft 2 thankyou.

**Comment by DinkyDyeAussie** [comment]
Also the wargus data isn't in the wargus directory natively now, but resides in the %appdata%/roaming/stratagus folder now? Also there is no music for warcraft 2 anymore. I mean there are midi tracks but no ogg music...

**Comment by timfel** [comment]
I forgot to include the -r flag for wartool in wargus.cpp to make it extract the music. I'll fix that.

Regarding the extraction process, I would prefer to leave it this way. The extra 50 or so MB for Aleonas Tales don't hurt, and people who just want to play and don't have the War2 data can and don't get confused. You get a separate executable, so it's clear that it is two games. Extracting to the user folder takes care of people wanting to mod their installation or re-extract without admin rights. And finally, the new mechanism is consistent across all platforms, so less maintenance.

We had issues open for all of these things, and the current solution isn't perfect, but it ticks more boxes than before.

**Comment by DinkyDyeAussie** [comment]
No worries man I understand now. Thanks for the heads up. It would make it easier yes. Thanks again.

**Comment by timfel** [comment]
The updated Wargus is in the nightly builds.

**Comment by Erenussocrates** [comment]
When you run Wargus, does it automatically link to here and update itself? Because my previously completely fine and working missions started to not working, and I haven't even done anything to them myself. What the hell?

**Comment by mimooh** [comment]
You mean wargus finds out that there's a new version and auto downloads
it and installs it on your system? Wargus doesn't do such thing.

**Comment by Erenussocrates** [comment]
But a bunch of things just got broken in my wargus suddenly and completely out of blue, and I didn't even touch it, WHY

**Comment by timfel** [comment]
@Erenussocrates nobody changed anything, and there is no auto-update. It must be something on your end that changed.

**Comment by timfel** [comment]
@DinkyDyeAussie did you try again with the latest nightly? The lua issue should not occur and it should attempt to rip the CD music. Can you confirm?

**Comment by DinkyDyeAussie** [comment]
@timfel Yes Ii tried with the latest nightly and from memory it works. I haven't played it for a while but last time I did it ran fine.

One thing tho. On multuplayer maps that have more than 2 players (I am testing for 2 players atm), the game adds bots in to fill the available spaces.

Is it possible to have it, that if 2 players play a map with more than 2 start positions, and there are NO bots and the starts are random? Same goes for any map that has more starts than players. But I hope you get what I meana...

**Comment by DinkyDyeAussie** [comment]
Sorry I meant to say *that* there are NO bots and start positions are random
