### ISSUE TITLE
Multiplayer does not connect at all

### ISSUE THREAD

**Issue by hopeabandoner** [Wargus/wargus#240]
After the recent commit, I installed the binary due to needing a fix for #239. Using stable 2.4.1, when I tried to set up a game of multiplayer with a friend, we'd get the "incompatible lua files" error and I'd get the same result trying to connect to myself on the same machine. However, now using the most recent unstable commit, we can't even connect at all and attempting to connect to myself fails as well. Unless we're mistaken, we need to use the "Local Game" option to connect to a port-forwarded game, correct?

**Comment by DinkyDyeAussie** [comment]
What are your IPV4 network settings? Are they auto or do you have a custom ip address set for each pc? I use a custom ip address for each of my laptops and I have no problems with the lua incompatability issue now.

**Comment by hopeabandoner** [comment]
A while back I used a static IP address to make game server hosting easier without worrying about the IP changing, but turned it off recently (which was before I ever installed Wargus) and I am just using an auto-obtained IP address. Now regarding IP addresses, my ISP gives me an IPV6 address when googling my IP, however I lookup my IPv4 address and use that one instead. Does that matter at all? I'm assuming Wargus is only able to use IPv4, of which we've only used to attempt connection.

Side note, I just now am able to connect to myself on the same machine (with the Lua file problem gone 😁 ) by adding 127.0.0.1 instead of localhost, but have yet to test an online game. Oddly enough, the client joined the server without hitting "Connect" but ended up never going to the game setup screen at first, but it appears to work for a localhost game.

**Comment by DinkyDyeAussie** [comment]
Yeah 127.0.0.1 is localhost from memory. Try typing in 'ipconfig /all' in the command prompt  and finding the IPV4 address of both machines and use that to create a local game instead of an online game. If that doesn't work just use the IPV6 one....but I've never used that one for local lan games before.

**Comment by mimooh** [comment]
From my experience on linux and windows, wargus multiplayer works pretty
well. Use IPv4. It is irrelevant whether your network card also has IPv6.

If you want to connect to an IPv4 server outside your LAN, say a friend
in another country, I am pretty much sure that's possible. However in a
typical scenario your friend (server) must configure his firewall
accordingly. 

-- 
Karol Kreński
tel. 517-302-055

**Comment by 77Mynameislol77** [comment]
What is the last version with working multiplayer? Both the "stable" version and the unstable version has bugged multiplayer

**Comment by DinkyDyeAussie** [comment]
Incompatible LUA files is something I experienced too. Just need to reinstall wargus with the latest LUA files and it should fix it.

I've had no problems usibg IPV4 for LAN games. What else is happening for you guys to make it not work?

**Comment by 77Mynameislol77** [comment]
I've uninstalled it, and reinstalled it i don't know how many times. It simply refuses to work.

**Comment by DinkyDyeAussie** [comment]
Have you uninstalled both wargus AND stratagus? Also I find placing them in 'games/wargus' instead of 'program files/wargus' helps with the reading of files. 

Even though the latest version of wargus places the warcraft data in 'users/documents/wargus/data' or something like that.

Try and find every file related to wargus and stratagus and delete it and start fresh just once more, on all of the machines you are trying to get multiplayer working on.

I can't remember the last version I had stable MP. I think it was 2.4.0. Try the latest experimental build too. Alot of lag fixes are in that build.

**Comment by 77Mynameislol77** [comment]
I tried the experimental build. the experimental build doesn't work at all, refuses to connect, while the "stable" version has lua errors. But i don't think i've tried installing stratagus and then wargus in the same folder.

**Comment by DinkyDyeAussie** [comment]
Give that a go, it can't hurt to try. I'll do the same tomorrow and let you know how it goes on my end.

**Comment by 77Mynameislol77** [comment]
Didn't work, for a while i thought it actually worked, but turns out it was simply the meta-server that made it work

**Comment by timfel** [comment]
With the new online networking code (coming in the upcoming 3.0.0 release) I was also able to discover and establish connections to machines across the internet, but also on the same local network as me
