### ISSUE TITLE
Support explicitly setting the number of AI players

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#243]
@DinkyDyeAussie in issue #239 asked if it's possible to leave open slots empty, rather than fill them with AI players. As of commit 7473676 is should be possible to select explicitly how many AI players are desired. This also means closing off games to human players - if the server wants 3 AI players, there are 3 fewer slots after all.

For now we default to zero AI players.

Let's keep this issue open until we had some people try it out.

**Comment by timfel** [comment]
Note that this also means that we can now play a single player game through the multiplayer screen, by simple adding AI players and clicking "Start". Not sure if that is desired.

**Comment by timfel** [comment]
@DinkyDyeAussie if you could do me a favor, if you have a chance to try the nightly 2.4.2 build in multiplayer, it has some fixes to make the metaserver connection work in more situations and also the support for explicitly telling how many AI players you want. The default is none.

I want to tag 2.4.2 as release some time, but I've only tested multiplayer games locally myself.

**Comment by timfel** [comment]
@DinkyDyeAussie btw, did you also want to add the 2 seconds delay in action victory / defeat to this release? If yes, now is the chance :)

**Comment by DinkyDyeAussie** [comment]
Yes to the delay for victory please. I will test the 2.4.2 soon.

**Comment by DinkyDyeAussie** [comment]
So I tested the changes today. Works great! Can have the option of NO A.I yet the starts are still random! Thanks Tim 👍

**Comment by timfel** [comment]
The starts should already be random, no idea why it doesn't work for you (I'm tracking this in #242)

**Comment by DinkyDyeAussie** [comment]
Yeah don't know. Perhaps they always were and for some reason I always ended up being player one.

But now we can dictate how many A.I players there can be, it makes it easier to see the results of the random start location.
