### ISSUE TITLE
Metaserver hangs and does not allow starting any more multiplayer game

### ISSUE THREAD

**Issue by mimooh** [Wargus/wargus#244]
As http://wargus.github.io/ says on the left, the metaserver allows now for playing online wargus games! :) The game can be joined from wargus menu, but what is the preferable way to start the game?

**Comment by timfel** [comment]
Just start a multiplayer game the normal way. In the preparation menu's bottom left, there is an input field for the metaserver address and port and a checkbox to connect to it. By default, all games are announced online right now.

**Comment by mimooh** [comment]
I see :) Unfortunately I cannot go any further after 
Multiplayer > Create Game > Choose map. I can see the MetaServer
checkbox but then the game freezes :(

-- 
Karol Kreński
tel. 517-302-055

**Comment by timfel** [comment]
Interesting ... it shouldn't freeze, but I just noticed the same thing happening on the website with the stats... It looks like the metaserver leaks "something" (I would guess file descriptors) and then eventually hangs on the server :(

**Comment by timfel** [comment]
I restarted it now, and I will investigate

**Comment by wolfen351** [comment]
Please restart again, it's down :(

**Comment by timfel** [comment]
We're about to switch to battle.net protocol support in the upcoming 3.0 release, and then we can just use any compatible server like pvpgn.pro
