### ISSUE TITLE
Catapult Trajectory bugs.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/wargus#245]
:FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3,*** Error in `/usr/games/stratagus': free(): invalid pointer: 0x0000000003bf0bb0 ***
 xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0BUG: RangeTargetFinder::FillBadGood.Compute out of range. size: 18, pos: -6, x: 3, xx: 0, y: -1, yy: 0Thanks for playing Stratagus.

**Comment by timfel** [comment]
Fixed with https://github.com/Wargus/stratagus/pull/207
