### ISSUE TITLE
Where is  CanGroundAttack?

### ISSUE THREAD

**Issue by eolandro** [Wargus/wargus#248]
Hi i've just wondering what about CanGroundAttack? what was his replace?

**Comment by timfel** [comment]
Do you mean `CanTargetLand`?

**Comment by timfel** [comment]
See for an example https://github.com/Wargus/stargus/blob/f9ca02e8a620bfbe3322525deca6c9b4f4b35201/scripts/zerg/unit-zerg-scourge.lua#L78

**Comment by eolandro** [comment]
I'm sorry. i didn't realize about "CanGroundAttack" was changed to "GroundAttack" some versions ago.
