### ISSUE TITLE
Wargus.app Not Extracting Files (Mac OS X 10.11.6 El Capitan)

### ISSUE THREAD

**Issue by dpmayer** [Wargus/wargus#252]
I can't seem to get Wargus 2.4.1 to extract the game files it needs from my Warcraft 2 CD-ROM. I have the retail version that came with a hybrid Mac/Windows CD. Wargus seems to want the DOS *.WAR files so first I mount the Windows partition of the CD:

`sudo mount_cd9660 -o nodev,nosuid,rdonly /dev/disk3s1 ~/Desktop/Warcraft2`
The disk mounts normally and I can see it in the Finder.

Upon opening Wargus.app, I get the dialog box saying "Wargus data was not extracted, is corrupted, or outdated. You need to extract it from original Warcraft II DOS REZDAT.WAR or BNE Battle.snp file. Please select the Warcraft II DOS REZDAT.WAR or BNE Battle.snp file"

I click OK and proceed through the file select dialog that pops up to select REZDAT.WAR on the CD.
I click Choose and then get an error dialog that says "There was an unrecoverable error copying the data"
I click OK and get another error dialog saying "Wargus data was not extracted, is corrupted, or outdated. You need to extract it from original Warcraft II DOS REZDAT.WAR or BNE Battle.snp file."

I also tried copying the contents of the CD onto my computer and pointing Wargus.app to the local copy of REZDAT.WAR, but get the same error.

Is this a known issue? Am I doing something incorrectly? This seems remarkably similar to #230

**Comment by timfel** [comment]
Sorry, just back from holiday... There was an unrecoverable error, let me see. Can you give me the full path to Wargus.app and the full path to your user home? The error indicates that the app couldn't find its own scripts folder.

**Comment by timfel** [comment]
Another question, did you try launching from the Downloads folder? If yes, try moving the Wargus.app explicitly into the Applications folder. The app doesn't work correctly with the sandbox feature of newer macos releases.

**Comment by dpmayer** [comment]
The full path to Wargus is /Applications/Wargus.app
The user home is /Users/dpmayer

**Comment by timfel** [comment]
Can you try with the nightly app bundle I just pushed?

**Comment by timfel** [comment]
Is there a directory name in the title of that error window?

**Comment by dpmayer** [comment]
No there isn't. The title of the error dialog just says "Error"

**Comment by timfel** [comment]
Damn, I don't have a sierra mac available, so I'm just guessing blindly :( I will try to find one that I can use (+ time) and look into this. Sorry.

**Comment by lacombar** [comment]
looking at it quickly, it would seem that `wartool` is not properly invoked. Running `/Applications/Wargus.app/Contents/MacOS/wartool  /Volumes/WARCRAFT2/DATA' seems to extract the data properly. I'll keep digging.

**Comment by lacombar** [comment]
I've finally been getting some success tonight. I was able to run `stratagus` with a mix of manually data and automatically extracted data, so something related to the invocation of `wartool` might not be right.

Hopefully, I can get everything sorted out tomorrow.

**Comment by you-fail-me** [comment]
@lacombar I'm facing the very same issue. Could you pls share, how did you get it working?

**Comment by sjaak8000** [comment]
> Did anybody ever figure this issue out?

Yes, running into the same issue here. So would also be interested to know if this issue can be fixed.

**Comment by benhbell** [comment]
replicated the issue on mac too

**Comment by benhbell** [comment]
One way to get this to work is to use the linux or windows version in a virtual machine or wine to extract the data needed in the data.wargus folder. Then move the contents of that extract folder to
`$HOME/Library/Stratagus/data.Wargus`

I was able to get this to work on Mac OSX 10.13

**Comment by benhbell** [comment]
> Damn, I don't have a sierra mac available, so I'm just guessing blindly :( I will try to find one that I can use (+ time) and look into this. Sorry.

Is there any logging or an experimental build I can use on my machine to show you whats going on? Happy to help test it

**Comment by jarroda** [comment]
> One way to get this to work is to use the linux or windows version in a virtual machine or wine to extract the data needed in the data.wargus folder. Then move the contents of that extract folder to
> `$HOME/Library/Stratagus/data.Wargus`
> 
> I was able to get this to work on Mac OSX 10.13

@benhbell  What specific data needs to be copied into the `data.Wargus` folder?  I have done the extraction on a Windows machine and copied the `campaigns`, `graphics`, etc folder into the `data.Wargus` folder, but I continue to get the same error when starting Wargus.  (Wargus data was not extracted, is corrupted...)

![image](https://user-images.githubusercontent.com/1840003/99153942-a0734180-2671-11eb-8631-0996a946b892.png)

**Comment by ryaneroth** [comment]
Here is the output when running wargus from the cli.  These files do exist, in the location logged:
`$ ./wargus
Supported sound decoders: WAVE AIFF VOC MOD MID OGG
Supported music decoders: CMD WAVE OGG MODPLUG NATIVEMIDI MOD MIDI
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/turalyon/selected/3.wav'
Can't load the sound 'human/units/turalyon/selected/3.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/deathwing/selected/1.wav.gz'
Can't load the sound 'orc/units/deathwing/selected/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/dentarg/selected/1.wav.gz'
Can't load the sound 'orc/units/dentarg/selected/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/grom_hellscream/selected/1.wav.gz'
Can't load the sound 'orc/units/grom_hellscream/selected/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/korgath_bladefist/selected/1.wav.gz'
Can't load the sound 'orc/units/korgath_bladefist/selected/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/teron_gorefiend/selected/1.wav.gz'
Can't load the sound 'orc/units/teron_gorefiend/selected/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/basic_voices/annoyed/1.wav.gz'
Can't load the sound 'human/basic_voices/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/basic_voices/annoyed/1.wav.gz'
Can't load the sound 'orc/basic_voices/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/death_knight/annoyed/1.wav.gz'
Can't load the sound 'orc/units/death_knight/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/dwarven_demolition_squad/annoyed/1.wav.gz'
Can't load the sound 'human/units/dwarven_demolition_squad/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/elven_archer-ranger/annoyed/1.wav.gz'
Can't load the sound 'human/units/elven_archer-ranger/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/gnomish_flying_machine/annoyed/1.wav.gz'
Can't load the sound 'human/units/gnomish_flying_machine/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/goblin_sappers/annoyed/1.wav.gz'
Can't load the sound 'orc/units/goblin_sappers/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/goblin_zeppelin/annoyed/1.wav.gz'
Can't load the sound 'orc/units/goblin_zeppelin/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/knight/annoyed/1.wav.gz'
Can't load the sound 'human/units/knight/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/paladin/annoyed/1.wav.gz'
Can't load the sound 'human/units/paladin/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/ogre/annoyed/1.wav.gz'
Can't load the sound 'orc/units/ogre/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/ogre-mage/annoyed/1.wav.gz'
Can't load the sound 'orc/units/ogre-mage/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/ships/annoyed/1.wav.gz'
Can't load the sound 'human/ships/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/ships/annoyed/1.wav.gz'
Can't load the sound 'orc/ships/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/ships/gnomish_submarine/annoyed/1.wav.gz'
Can't load the sound 'human/ships/gnomish_submarine/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/troll_axethrower-berserker/annoyed/1.wav.gz'
Can't load the sound 'orc/units/troll_axethrower-berserker/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/mage/annoyed/1.wav.gz'
Can't load the sound 'human/units/mage/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/peasant/annoyed/1.wav.gz'
Can't load the sound 'human/units/peasant/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/alleria/annoyed/1.wav.gz'
Can't load the sound 'human/units/alleria/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/danath/annoyed/1.wav.gz'
Can't load the sound 'human/units/danath/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/khadgar/annoyed/1.wav.gz'
Can't load the sound 'human/units/khadgar/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/kurdan/annoyed/1.wav.gz'
Can't load the sound 'human/units/kurdan/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/turalyon/annoyed/1.wav.gz'
Can't load the sound 'human/units/turalyon/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/deathwing/annoyed/1.wav.gz'
Can't load the sound 'orc/units/deathwing/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/dentarg/annoyed/1.wav.gz'
Can't load the sound 'orc/units/dentarg/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/grom_hellscream/annoyed/1.wav.gz'
Can't load the sound 'orc/units/grom_hellscream/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/korgath_bladefist/annoyed/1.wav.gz'
Can't load the sound 'orc/units/korgath_bladefist/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/units/teron_gorefiend/annoyed/1.wav.gz'
Can't load the sound 'orc/units/teron_gorefiend/annoyed/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/misc/explosion.wav.gz'
Can't load the sound 'misc/explosion.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/misc/building_explosion/1.wav.gz'
Can't load the sound 'misc/building_explosion/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/missiles/sword_attack/1.wav.gz'
Can't load the sound 'missiles/sword_attack/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/misc/tree_chopping/1.wav.gz'
Can't load the sound 'misc/tree_chopping/1.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/units/peasant/work_complete.wav.gz'
Can't load the sound 'human/units/peasant/work_complete.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/basic_voices/work_complete.wav.gz'
Can't load the sound 'orc/basic_voices/work_complete.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/basic_voices/work_complete.wav.gz'
Can't load the sound 'human/basic_voices/work_complete.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/basic_voices/work_complete.wav.gz'
Can't load the sound 'orc/basic_voices/work_complete.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/human/capture.wav.gz'
Can't load the sound 'human/capture.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/orc/capture.wav.gz'
Can't load the sound 'orc/capture.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/ui/highclick.wav.gz'
Can't load the sound 'ui/highclick.wav': Mix_LoadWAV_RW with NULL src
Can't open file '/Users/User/Library/Stratagus/data.Wargus/sounds/ui/statsthump.wav.gz'
Can't load the sound 'ui/statsthump.wav': Mix_LoadWAV_RW with NULL src
Can't open file 'scripts/missiles.lua': Too many open files
Can't open file 'scripts/constructions.lua': Too many open files
Can't open file 'scripts/spells.lua': Too many open files
Can't open file 'scripts/units.lua': Too many open files
Can't open file 'scripts/upgrade.lua': Too many open files
Can't open file 'scripts/fonts.lua': Too many open files
Can't open file 'scripts/buttons.lua': Too many open files
Can't open file 'scripts/ui.lua': Too many open files
Can't open file 'scripts/commands.lua': Too many open files
Can't open file 'scripts/cheats.lua': Too many open files
/Users/travis/build/Wargus/stratagus/src/ai/script_ai.cpp:334: CclDefineAiHelper: unknown unittype: unit-town-hall
unknown unittype: unit-town-hall
stack traceback:
	[C]: in function 'DefineAiHelper'
	[string "scripts/stratagus.lua"]:532: in main chunk`

**Comment by timfel** [comment]
hm. Just guessing wildly here since I don't have a mac .... something to do with permissions? IIRC I heard that macOS started to not allow filesystem access in general to downloaded apps unless some quarantine bits are cleared.

**Comment by ryaneroth** [comment]
Wargus is actual able to copy the files to that location without issue. Also, to verify disk access wasn’t the case, I gave stratgus, and wargus, full disk access. I should also mention that it appears that it is only audio files that are affected, as if you run with the debug arg, you can see that other resources load.

**Comment by timfel** [comment]
Ah, interesting, I hadn't noticed. There's actually multiple issues here, too. The game would start just fine without the sound files, but it's also saying this at the very end: `Can't open file 'scripts/constructions.lua': Too many open files`

**Comment by ryaneroth** [comment]
I've got it working now, but I'm not sure what fixed it :/

**Comment by timfel** [comment]
@ryaneroth can you post which version of macOS and what steps you took that worked? That might help the next one.

**Comment by ryaneroth** [comment]
Big Sur.  Not sure what fixed it as I had been compiling it locally, and the last thing I changed was installing SDL2 from mac ports instead of brew,

**Comment by maizy** [comment]
`Can't open file 'scripts/constructions.lua': Too many open files` error triggered because of low file handlers limit in macOS.

In macOS 10.15.7 defaults are:
```
ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       4176
-n: file descriptors                256
```

I've solved it with extending limit and launching wartool & wargus manually from terminal.
But I still have problems with launching game.

```
ulimit -S -n 1024
cd /Applications/Wargus.app/Contents/MacOS

./wargus --version
# Stratagus v3.0.0-git185f90da58430c51d3fd56bf68ae391614bc2442

./wartool -V
# 3.0.0

./wartool -v '/path/to/Warcraft II BNE' /path/to/wargus-data  # BNE GOG version 
# convertion is seems to complete successfully

./wargus -v 1920x1080 -d /path/to/wargus-data -u /path/to/saves
# ...
# Can't open file: No such file or directory
# Can't load the graphic 'ui/black_title.png
```

**Comment by stcollins** [comment]
Following on from those commands, the quickest way to fix the `Can't load the graphic 'ui/black_title.png` error is to duplicate the existing `title.png`:

```bash
cd /Users/$USER/Library/Stratagus/data.Wargus/graphics/ui # or wherever your wargus data is
cp title.png black_title.png # duplicate the existing title.png
```

After that, the game runs as above.

**Comment by timfel** [comment]
I had to drop support for macOS, because Apple seems to be actively making it harder and harder for cross-platform software to build, test, and ship without buying any Apple dev tools or licenses :(

**Comment by dowobeha** [comment]
I'm having similar issues on macOS 11.6

I tried copying the data.Wargus folder from a Windows Wargus install to ~/Library/Stratagus, but I get a different error then.

If you need a macOS tester to help figure out what's going on, I would be interested in helping.

**Comment by YunaBraska** [comment]
Tel me how I can setup my dev environment and how I can test things. As I know how to code and have a macOs, I probably can help you. What's the issue with MacOs? How can I get logs?

**Comment by dowobeha** [comment]
Thanks, @YunaBraska! I can't access things right now, but I really appreciate the offer to help. I'll work on getting you logs, etc, and I'll post here again when I do.
