### ISSUE TITLE
videos are in black and white with red band

### ISSUE THREAD

**Issue by legluondunet** [Wargus/wargus#254]
Hello,
videos are not played with the corrects colors, they are in black and white with a red band
![capture d ecran de 2017-09-15 23-56-30](https://user-images.githubusercontent.com/325405/30505329-4a4d4120-9a74-11e7-8c74-05cdb3a56109.png)
Thank you for your help.
LGDN

Config:
Ubuntu 17.10
Nvidia

**Comment by timfel** [comment]
I have seen this issue with some versions of ffmpeg. We need to experiment with different versions and settings for ffmpeg when converting the smk files.

**Comment by doomguy** [comment]
If I open those files with e.g. totem or vlc it will play just fine on my side. I guess the framework got some problems with the playback. However, I stumpled upon this SE entry; https://stackoverflow.com/questions/15265505/ffmpeg-x264-mp4-encoding-all-grey

As I'm currently out of town, can someone please try the following conversion command and see if this helps?
> ffmpeg -i video.smk -c:v libx264 -pix_fmt yuv420p video.ogv

**Comment by legluondunet** [comment]
> If I open those files with e.g. totem or vlc it will play just fine on my side.
Same result here.

**Comment by mathgamain** [comment]
Same happens to me, plays fine on mpv

My ffmpeg is:
ffmpeg version 2.8.5 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.5.4 (GCC)
  configuration: --prefix=/usr --bindir=/bin --mandir=/usr/man --libdir=/usr/lib --disable-debug --enable-static --disable-stripping --enable-pic --enable-pthreads --enable-postproc --enable-avfilter --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-libfreetype --enable-libfribidi --enable-libopus --enable-libspeex --enable-libtheora --enable-libmp3lame --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-zlib --enable-shared --enable-version3 --enable-x11grab --enable-libpulse
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100

**Comment by timfel** [comment]
This has taken me a long time to test, but @doomguy gave me the cmdline options that fix the colours in game for me:
```
ffmpeg -i video.smk -codec:v libtheora -qscale:v 7 -codec:a libvorbis -qscale:a 5 -pix_fmt yuv420p video.ogv
```

**Comment by wolfen351** [comment]
confirmed! this command will fix the already extracted video:

    ffmpeg -i video.ogv -codec:v libtheora -qscale:v 7 -codec:a libvorbis -qscale:a 5 -pix_fmt yuv420p video.ogv
