### ISSUE TITLE
Not launching on windows 7

### ISSUE THREAD

**Issue by ChefKeeper** [Wargus/wargus#255]
App crashes on startup "wargus has stoped working"
I tryed to compile stratagus myself in debug mode and it works, will test in release tomorow to see if thats causing the problem.

**Comment by ChefKeeper** [comment]
Some update : I did compile in release mode but still no crash, I used visual 2017 community version. What could be the problem ?

**Comment by ChefKeeper** [comment]
Update : some progress here, it's a problem in SetupConsole() https://github.com/Wargus/stratagus/blob/add0ee52651a527d6dbca7edb4544ce1d5b64b35/src/win32/SetupConsole_win32.cpp#L153

**Comment by pali** [comment]
Can you debug it, on which line in that file it crashes?

**Comment by ChefKeeper** [comment]
It crashes on this line : https://github.com/Wargus/stratagus/blob/master/src/win32/SetupConsole_win32.cpp#L223

**Comment by pali** [comment]
So there is missing some check if attaching were successfull... :-( And it would be needed to debug SetStreamAndFdFromStdConsole function.

And do you see some output in cmd.exe?

**Comment by ChefKeeper** [comment]
No nothing at all.
But isn't the problem that when compiling with WIN32 there is no console ?
Because when runing in with visual it just works fine but it crashes outside visual (either debug or release).
What is SetupConsole() supposed to do, create a console ?

**Comment by pali** [comment]
> But isn't the problem that when compiling with WIN32 there is no console ?

Why? Console is provided by parent process (if any).

> What is SetupConsole() supposed to do, create a console ?

If stdin/stdout/stderr is not initialized and parent process has a console, then stdin/stdout/stderr is attached to that console. Basically same what is done automatically for application compiled as Console (when WIN32 is not set in cmake).

**Comment by ChefKeeper** [comment]
_fileno(srteam) returns -2 at line : https://github.com/Wargus/stratagus/blob/master/src/win32/SetupConsole_win32.cpp#L112

It says from msdn :  If stdout or stderr is not associated with an output stream (for example, in a Windows application without a console window), the file descriptor returned is -2. In previous versions, the file descriptor returned was -1. This change allows applications to distinguish this condition from an error.
But in this case it always return -2 even with stdin, and msdn says also : "There is no error return." so I don't know what's wrong ... ?

**Comment by pali** [comment]
> _fileno(srteam) returns -2

For which stream? There is standard input, standard output and error output.

As you wrote above it is expected that for GUI application without assigned console there is no file descriptor.

Try to figure out which FILE*, fd or HANDLE or when stop working and crash.

**Comment by ChefKeeper** [comment]
It's -2 for all 3 calls : 
```
if (!stdin_ok)
    stdin_console = SetStreamAndFdFromStdConsole(stdin, 0, STD_INPUT_HANDLE, true);
if (!stdout_ok)
    stdout_console = SetStreamAndFdFromStdConsole(stdout, 1, STD_OUTPUT_HANDLE, false);
if (!stderr_ok)
    stderr_console = SetStreamAndFdFromStdConsole(stderr, 2, STD_ERROR_HANDLE, false);
```

**Comment by pali** [comment]
That is expected, right?

**Comment by pali** [comment]
> I tryed to compile stratagus myself in debug mode and it works

Does it mean that problem is just when debug mode is turned off and optimizations on?

**Comment by ChefKeeper** [comment]
problem is only in windows 7 when launching outside debuger (either release or debug it doesn't matter)

**Comment by pali** [comment]
Looking at code, and there is a problem with fclose which closes file descritor associated.

Try following patch:
```
--- SetupConsole_win32.cpp.orig	2017-10-29 17:04:32.815130269 +0100
+++ SetupConsole_win32.cpp	2017-10-29 19:02:56.461640225 +0100
@@ -28,6 +28,7 @@
 
 #include <windows.h>
 #include <stdio.h>
+#include <stdbool.h>
 #include <io.h>
 #include <errno.h>
 #include <fcntl.h>
@@ -110,35 +111,37 @@ bool SetStreamAndFdFromStdConsole(FILE *
 
     /* Retrieves existing file descriptor from FILE* stream */
     int fd_old = _fileno(stream);
-    if (fd_old >= 0 && fd_old != fd_new) {
-        /* Reassigns new file descriptor to existing one from FILE* stream */
-        if (_dup2(fd_new, fd_old) < 0) {
-            _close(fd_new);
-            return false;
-        }
-    }
+
+    /* Backup old file descriptor to have it after fclose */
+    int fd_old_dup = -1;
+    if (fd_old >= 0)
+        fd_old_dup = _dup(fd_old);
 
     if (fd_new != fd) {
         /* Reassigns new file descriptor to one provided by function arg */
         if (_dup2(fd_new, fd) < 0) {
             _close(fd_new);
+            if (fd_old_dup >= 0)
+                _close(fd_old_dup);
             return false;
         }
-    }
-
-    /* Clean up */
-    if (fd_old < 0 || fd_old != fd_new)
         _close(fd_new);
+    }
 
     /* Allocates new FILE* stream and associates it with file descriptor */
     FILE *stream_new = _fdopen(fd, (input ? "r" : "a"));
     if (!stream_new) {
         _close(fd);
+        /* Restore old file descriptor if possible */
+        if (fd_old_dup >= 0) {
+            _dup2(fd_old_dup, fd_old);
+            close(fd_old_dup);
+        }
         return false;
     }
 
-    /* Close old FILE* stream */
-    fclose(stream);
+    /* Clean up backup */
+    close(fd_old_dup);
 
     /* Set new FILE* stream */
     *stream = *stream_new;
```

And here is simple test application:
```
#include "SetupConsole_win32.cpp"

int main() {
    SetupConsole();
    printf("FILE * stdout\n");
    fflush(stdout);
    fprintf(stderr, "FILE * stderr\n");
    fflush(stderr);
    write(1, "fd 1\r\n", 6);
    write(2, "fd 2\r\n", 6);
    printf("FILE * stdout\n");
    fflush(stdout);
    fprintf(stderr, "FILE * stderr\n");
    fflush(stderr);
    write(1, "fd 1\r\n", 6);
    write(2, "fd 2\r\n", 6);
    return 0;
}
```

**Comment by ChefKeeper** [comment]
No still the same, even with your testing main. Besides even on windows 8 when I start stratafus from console I got no output, do you have something ?

Just show me the whole modified func next time, I don't have a patching tool on win7 :(

**Comment by pali** [comment]
I tested it on winxp and working fine. when started from cmd.exe there is output.

**Comment by pali** [comment]
Tested on win10 and no crash. Above main test (compiled as GUI application) working fine and when started from cmd.exe it prints output to current console window.

**Comment by ChefKeeper** [comment]
Actually I think I do have some output on w8, like 2 new lines should there be something else ?
Will try compile on w8 tomorow to confirm that.

**Comment by timfel** [comment]
Trunk builds now always redirect stdio, and I've also merged the fix for Windows when stdio is not redirected, that we compile as a console app so that the standard descriptors work
