### ISSUE TITLE
can not extract data from wc2 BNE

### ISSUE THREAD

**Issue by unxed** [Wargus/wargus#262]
Extractor could not find BNE's dataset.

File list in wc2 BNE folder:

-rw-r--r-- 1 unxed unxed    426238 май 11  2001 battle.snp
-rwxr-xr-x 1 unxed unxed    200704 ноя 23  2011 BNUpdate.exe
-rw-r--r-- 1 unxed unxed      5632 дек 12  2015 ddraw.dll
-rw-r--r-- 1 unxed unxed      2668 мар 10 19:03 instlog.txt
drwxr-xr-x 5 unxed unxed      4096 мар 10 18:56 Maps
-rw-r--r-- 1 unxed unxed      1766 ноя 23  2011 patch.txt
-rw-r--r-- 1 unxed unxed      2622 мар 10 19:03 release.rtf
-rw-r--r-- 1 unxed unxed     95232 ноя 23  2011 Smackw32.dll
-rw-r--r-- 1 unxed unxed    266299 ноя 23  2011 storm.dll
drwxr-xr-x 7 unxed unxed      4096 мар 10 18:56 SUPPORT
drwxr-xr-x 2 unxed unxed      4096 мар 10 19:03 uninstall
-rw-r--r-- 1 unxed unxed     61440 ноя 23  2011 W2Local.dll
-rwxr-xr-x 1 unxed unxed    111861 ноя 23  2011 W2SOUNDS.EXE
-rw-r--r-- 1 unxed unxed  30261389 мар 10 19:03 War2Dat.mpq
-rw-r--r-- 1 unxed unxed 717159106 мар 10 19:03 War2.mpq
-rw-r--r-- 1 unxed unxed   1350293 фев 20  2017 War2Patch.mpq
-rwxr-xr-x 1 unxed unxed    712704 ноя 23  2011 Warcraft II BNE.exe
-rwxr-xr-x 1 unxed unxed    544768 ноя 23  2011 Warcraft II Map Editor.exe
-rw-r--r-- 1 unxed unxed     64299 ноя 23  2011 Warcraft II Map Editor.hlp

**Comment by timfel** [comment]
I only realised now - this is an installation. The extractor only works from the BNE CD, not the installed thing, afaict
