### ISSUE TITLE
Minimap not updating correctly after buildings destroyed (Wargus 2.4.2)

### ISSUE THREAD

**Issue by Regelink** [Wargus/wargus#266]
I noticed that the little squares representing opponent buildings in the minimap do not vanish when they are destroyed (at least not in the multiplayer game I played today).

**Comment by timfel** [comment]
I haven't noticed that before, I'll check.

**Comment by BoNT325** [comment]
This occurred during a single player mission I did, on the orc campaign, mission 7. Something was preventing me from winning the mission, and I checked the minimap to see that there was supposedly an oil platform still there after being destroyed. Nothing removed it. I attacked the area where it was supposed to be and built over it, it didn't disappear. I think it may have something to do with destroying buildings that have not yet completed construction.

Not sure which build this was in exactly, but it was version 2.4.2.

**Comment by timfel** [comment]
The fix that was merged for this will be in the upcoming 3.0 release
