### ISSUE TITLE
Use OpenGL / OpenGL ES 1.1 crashes the game (after restart)

### ISSUE THREAD

**Issue by Regelink** [Wargus/wargus#267]
When I tick the "Use OpenGL / OpenGL ES 1.1" option from the video options in Wargus 2.4.2, it gives me the following error after restarting:
![wargus error](https://user-images.githubusercontent.com/1665817/39217339-d6b00dd8-481f-11e8-935b-fd5c800d9633.png)

**Comment by timfel** [comment]
Can you provide the contents of the stdout and stderr file in `C:\Users\Bert\AppData\Roaming\Stratagus`?

**Comment by Regelink** [comment]
[stderr with OpenGL.txt](https://github.com/Wargus/wargus/files/1956588/stderr.with.OpenGL.txt)
[stderr without OpenGL.txt](https://github.com/Wargus/wargus/files/1956589/stderr.without.OpenGL.txt)
[stdout with OpenGL.txt](https://github.com/Wargus/wargus/files/1956590/stdout.with.OpenGL.txt)
[stdout without OpenGL.txt](https://github.com/Wargus/wargus/files/1956591/stdout.without.OpenGL.txt)

**Comment by damobeanrod** [comment]
same here

**Comment by timfel** [comment]
Should be fixed in the current nightly builds. When it fails to create an OpenGL context, it reverts automatically back to Software rendering
