### ISSUE TITLE
Failed To Connect most of the time in multiplayer

### ISSUE THREAD

**Issue by 77Mynameislol77** [Wargus/wargus#271]
Hello, me & my friend is getting Failed To Connect to our multiplayer games most of the time, but sometimes it works

**Comment by 77Mynameislol77** [comment]
I'm also getting "network out of sync" quite often, that results in me & my friend having to start over the match.

**Comment by 77Mynameislol77** [comment]
I am now crashing after changing the IP address & port at the meta server..

**Comment by 77Mynameislol77** [comment]
Turns out it was the meta server that made it work, without the meta server, not even port-forwaring makes the connection work

**Comment by benhbell** [comment]
I was able to set up a lan game with someone in a different city using zerotier. Both of us were on linux. Metaserver has never worked for me.

**Comment by timfel** [comment]
We're moving to battle.net protocol support instead of metaserver, and establishing a connection should work better then
