### ISSUE TITLE
Crashing on Orc Expansion Mission 8, attempt to call global AiUpgradeCatapult3

### ISSUE THREAD

**Issue by 77Mynameislol77** [Wargus/wargus#272]
Here's the log 

> Failed to load the SoundFont: music/Arachno.sf2
[string "C:/Users/Joakim/AppData/Roaming/Stratagus/d..."]:78: attempt to call global 'AiUpgradeCatapult3' (a nil value)
stack traceback:
	[string "C:/Users/Joakim/AppData/Roaming/Stratagus/d..."]:78: in function '?'
	[string "scripts/ai.lua"]:903: in function <[string "scripts/ai.lua"]:875>
	(tail call): ?
	[C]: in function 'StartMap'
	[string "scripts/guichan.lua"]:824: in function 'RunMap'
	[string "scripts/menus/network.lua"]:764: in function 'callback'
	[string "scripts/guichan.lua"]:335: in function <[string "scripts/guichan.lua"]:333>
	[C]: in function 'run'
	[string "scripts/menus/network.lua"]:863: in function 'RunServerMultiGameMenu'
	[string "scripts/menus/network.lua"]:920: in function 'callback'
	...
	[string "scripts/menus/network.lua"]:986: in function 'callback'
	[string "scripts/guichan.lua"]:335: in function <[string "scripts/guichan.lua"]:333>
	[C]: in function 'run'
	[string "scripts/menus/network.lua"]:993: in function 'RunMultiPlayerGameMenu'
	[string "scripts/guichan.lua"]:1523: in function 'callback'
	[string "scripts/guichan.lua"]:335: in function <[string "scripts/guichan.lua"]:333>
	[C]: in function 'run'
	[string "scripts/guichan.lua"]:1537: in function 'BuildProgramStartMenu'
	[string "scripts/guichan.lua"]:1549: in function 'RunProgramStartMenu'
	[string "scripts/guichan.lua"]:1671: in main chunk

**Comment by timfel** [comment]
Fixed
