### ISSUE TITLE
Feature Request - Add "Skirmish Modern" to multiplayer

### ISSUE THREAD

**Issue by 77Mynameislol77** [Wargus/wargus#273]
Hello, i've made a coop mappack of the campaign, and i have one tiny little issue.

There is no difficulty settings for the AI.

I saw that in single player, theres something called "Skirmish Modern", and the features from that would be PERFECT for use in this mappack i made, as some missions on the default multiplayer diffculty  (unknown what difficully that is) are simply too hard, even for two players.

**Comment by Kintobor** [comment]
You could manually embed the difficulty setting into each of the maps.

**Comment by 77Mynameislol77** [comment]
Interesting, how would i go about doing that?

**Comment by 77Mynameislol77** [comment]
It'd be great to have some form of documentation on what you can do, it'd make alot of things easier

**Comment by timfel** [comment]
You could set the AiType to the appropriate value in your maps directly. There's some documentation e.g. here: https://github.com/Wargus/stratagus/blob/master/doc/scripts/mapsetup.html

**Comment by timfel** [comment]
Or just set `GameSettings.Difficulty` to 1 in your map setup.

**Comment by 77Mynameislol77** [comment]
Ah, thank you! I'll keep this in mind :)
