### ISSUE TITLE
2.4.2 No Music?

### ISSUE THREAD

**Issue by kernelk** [Wargus/wargus#274]
Hi, was having the mouse issue with 2.4.1, so I tried 2.4.2. Mouse issue fixed, thanks! but I have no music now. Looks like no option for midi music either.

Thanks.

**Comment by timfel** [comment]
This should be fixed, there was an issue with the midi soundfont not being copied to the right location. The 2.4.2 release is now tagged, can you try with that? If it isn't fixed, please reopen this issue
