### ISSUE TITLE
Wargus AI

### ISSUE THREAD

**Issue by 2mg** [Wargus/wargus#276]
In Expansion campaign, Orc mission 6 and 7, the AI is insane and assaults aggressively if set to Normal, and almost passive with Easy setting.

Try playing mission 7 with Wargus 2.4.1: two archers will attack from the north, a small group will immediately come from the south. In videos posted below, this doesn't happen that early, new enemy waves are less frequent, and there ARE roaming enemy Copters.

Videos for comparison:
https://tinyurl.com/y93lhqng
https://tinyurl.com/yce9ktfg

I'm using Wargus 2.4.1, W7 x64.

Ps: if you play mission 6, you'll notice that the location of a blue Lumber Mill is different from videos in playlist that in linked.

**Comment by 2mg** [comment]
Bump?

**Comment by timfel** [comment]
I tried to work around by making the normal ai sleep a little more between attacks, hope that helps
