### ISSUE TITLE
Orcx mission 8, always crashes after some time

### ISSUE THREAD

**Issue by 2mg** [Wargus/wargus#277]
[stdout.txt](https://github.com/Wargus/wargus/files/2170337/stdout.txt)
[stderr.txt](https://github.com/Wargus/wargus/files/2170338/stderr.txt)

**Comment by 2mg** [comment]
I'm 2.4.1 if it matters, and 2.4.2 won't work for me...

**Comment by DinkyDyeAussie** [comment]
I have had no issues with 2.4.2 except with the opengl problems.

What is 2.42 doing....or not doing?

**Comment by 2mg** [comment]
1. When I install Wagus 2.4.2 - Missing data window pops up. `Wargus data was not extracted, is corrupted or outdated. You need to extract it from original Warcraft II DOS REZDAT or BNE Battle.snp file. Please select the Warcraft II DOS REZDAT or BNE Battle.snp file.`
2. After extracting/converting, it asks for Expansion, which I agree to.
3. After it finished, it asks the same question again (over and over).
4. When I click cancel, Wargus.exe has stopped working.
5. When I launch it, same error. Stratagus.exe launches Aleona's Talse fyi.
5a. It seems Wargus extracts some files into installation dir, and leaves some in AppData...

stderr = https://pastebin.com/BxxndauN
stdout = https://pastebin.com/01hjvuKD
 
I am extracting from two working base and expansion cue/bin disks that work properly in DOS & W9x. I also have to bump this - https://github.com/Wargus/war1gus/issues/120 since we're talking unpatched CD versions as extraction source.

PS: wargus.github.io has outdated links to unstable builds (ala 2.4.2).

**Comment by timfel** [comment]
Fixed in trunk.
