### ISSUE TITLE
Feature Request - Difficulty Setting of AI

### ISSUE THREAD

**Issue by timfel** [Wargus/wargus#28]
It would be really ideal to have a difficulty setting for the AI, there are some maps where it is impossible to beat the AI the way they are currently programmed. So I was thinking maybe there is a way to put in some variables to alter how they function when you select it, then maybe later on you can set the difficulty of each individual AI when you are able to select the colors. So my basic rundown of how this could work is:

Easy = -10-15% on rate of micro managing. This would essentialy make the AI not build up their base so darn fast and Gruntman rush you to death. Also will make them not rush early in general.

Medium = Basicaly the current programming is kept the way it is now, except their micro managing should be toned down 5% of what is now to keep them from dominating the player in a 1v1 match in open field.

Hard = All this will do is keep the current AI setting the way they are currently (2.2.5), and add some more attack strategies and possibly early expanding.

These will definantly make the game far more enjoyable, I hope you will consider this in the future, thanks for reading. :-)

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-12-27T06:13:26Z
 * owner: enkerzan
 * assignee: iddqd-mail
 * the launchpad url was https://bugs.launchpad.net/bugs/908953

**Comment by timfel** [comment]
(by iddqd-mail)
You've got AI difficulty selection in Wargus trunk version

**Comment by 77Mynameislol77** [comment]
There's no AI difficulty in multiplayer i see
