### ISSUE TITLE
Sound stop working and error

### ISSUE THREAD

**Issue by CosmeFC** [Wargus/wargus#282]
Hi,

just stop after some time.
There is a connection with "Full screen" option.
Error message during the game.

Windows 10.
Stratagus and Wargus - new version
![capture](https://user-images.githubusercontent.com/4854932/47240406-98774380-d3be-11e8-9a0d-e916fd42d891.PNG)

**Comment by DinkyDyeAussie** [comment]
What version are you using? From what I have read of the fixes that Tim has added, this should be fixed in version 2.4.2.1.

**Comment by timfel** [comment]
This should be fixed on master with the migration to SDL2 and SDL2_mixer and will be in the upcoming 3.0.0 release
