### ISSUE TITLE
LAN NOT WORKING WINDOWS 10 ultimate 64 pro.

### ISSUE THREAD

**Issue by EFREET14689** [Wargus/wargus#283]
Hello Everyone, i'll start with a BIG THANK YOU to all peps who worked on this project. This is awesome to be able to play Warcraft2 which is on of my childhood games (along with wc1; C&C; RedAlerts, etc...)

I want to play LAN games with my lil bro which has a PC with the same OS as me, Win10 ultimate 64 Pro.

I installed Wargus 2.4.2 which doesn't work at all... Dunno why but wc2 files are not asked for.
ERROR ! Game not loading, files missing etc.. (Another issue)

So as 2.4.2 did not work I downloaded 2.4.1 to test, and then Install works on both PC, I have images of WC2 and WC2x CDs so I was able to get the files from the CDs at the end of the Setup.

Now Warcraft 2 wargus.exe launches. Good !
Full screen ! Awesome ! 
Now let's try Campaigns : Hmm I don't know why but motherland thing crashes the game and Only WC2 and WC2x campaigns work ! At least that's what I wanted !

Now comes the time of the LAN game ! Eventually We'll feast in each other's skull.

I set up my Local IP as I always do (setup on 192.168.1.29)
And my bro's local IP (------.28)

And then ... when I try to connect, I have the message telling me LUA FILES problem...

I don't know what LUA files are for, and I don't really care, I just use to mess around until games eventually work ! 

I lack your computer literacy so I'll just ask if someone can Send me HIS LUA files if they can, and If these files are compatible with my version of the game/PC/OS/other 

THANK YOU VERY MUCH BY ADVANCE 
Keep up ! 
Cheers !

**Comment by EFREET14689** [comment]
I read about issue #239 and Am waiting for informations as I don't understand passed the first post.

**Comment by timfel** [comment]
Please try to use 2.4.2. It asks to extract the data files on first launch, not in the installer. The 2.4.1 lua files problem is fixed there.
