### ISSUE TITLE
SetDiplomacy doesn't work for players in multiplayer

### ISSUE THREAD

**Issue by 77Mynameislol77** [Wargus/wargus#284]
Tried this, and it doesn't do anything.

`Triggers = [[
SetDiplomacy(1, "allied", 6)
SetDiplomacy(6, "allied", 1)
SetSharedVision(1, true, 6)
SetSharedVision(6, true, 1)
]]`

**Comment by 77Mynameislol77** [comment]
Sorry, i'm completely stupid. Noticed that it isn't implemented yet. Any ETA when?

**Comment by timfel** [comment]
This is not how you define triggers. Also, there's no reason to use triggers for this, you can just call the lua functions.

**Comment by 77Mynameislol77** [comment]
could you please help me then? This is my first time even touching LUA, and i am amazed i got this far

**Comment by 77Mynameislol77** [comment]
Hello again, i've been trying to do this again, but i still don't quite understand what i need to do.

**Comment by timfel** [comment]
For posterity, we have solved this on Discord and the approach has been documented here: https://stratagus.com/mapbuilding.html
