### ISSUE TITLE
Windows and Linux PPA releases dont match up

### ISSUE THREAD

**Issue by wolfen351** [Wargus/wargus#288]
Hey guys, thanks for an awesome project! Just a quick one - the release for linux is using a newer 20501 vs 20500 (just 1 ahead) compared to the release for windows. So we can't play across the 2 platforms. Please consider upgrading the windows release?

**Comment by timfel** [comment]
Hi, we had some trouble with Launchpad and how the Debian packages are built. Can you use the latest packages (latest deb package and windows nightly?)

**Comment by wolfen351** [comment]
Great, thanks!
