### ISSUE TITLE
Opening multiplayer for a local game, as soon as I select a map and proceed, it freezes

### ISSUE THREAD

**Issue by wolfen351** [Wargus/wargus#290]
Hi there

Small but game destroying bug! As soon as I select a map (for a local multiplayer session) and proceed to the next screen, it shows the multiplayer screen with "waiting for players" and the mouse freezes. I have done it on both pc's here :(

Please help?

**Comment by wolfen351** [comment]
Ok, late breaking news on this one, after waiting about 2-3 mins it wakes up again and the mouse is responsive. I assume something is tying up the UI thread (perhaps it is doing some networking thing that eventually times out)

**Comment by timfel** [comment]
This should be fixed in the latest nightly builds, there used to be a blocking connection attempt to the default metaserver, now that's gone.
