### ISSUE TITLE
wartool: Support extracting data from Warcraft 2 Combat

### ISSUE THREAD

**Issue by baco** [Wargus/wargus#291]
Add support for extracting data from binaries provided by the [Warcraft II: Combat Edition](http://en.war2.ru/) team.

Those custom-made binaries have bundled the sprites, audios, videos and music, in different languages and are free (of charge) to [download](http://en.war2.ru/downloads/#Warcraft-II).

**Comment by timfel** [comment]
Those binaries also have very unclear legal status. I could not find any official statement from Blizzard that says that these are legal to share. Until such time, no.
