### ISSUE TITLE
Green "X" not showing in unexplored areas

### ISSUE THREAD

**Issue by OrinVukelic** [Wargus/wargus#294]
When ordering units to move into unexplored areas, green "X" doesn't appear like it does in the original.

**Comment by DinkyDyeAussie** [comment]
Are you using 2.4.2 or 2.4.1?

**Comment by OrinVukelic** [comment]
2.4.2, was it present in 2.4.1?

**Comment by DinkyDyeAussie** [comment]
I am using 2.4.1 and I haven't had any issues.

**Comment by OrinVukelic** [comment]
Tested 2.4.1 right now both with OpenGL / OpenGL ES 1.1 enabled and disabled and the same issue occurs. X actually appears beneath the black area; if you order someone to explore area near to that unit, you can see it happening after it gets into unit's LOS. Seems to me like Stratagus engine perceives it that way.

**Comment by DinkyDyeAussie** [comment]
So if you click on a black area there is no cross? Am I percieving that right?

I will try to see if mine does it both video modes today after work.

**Comment by OrinVukelic** [comment]
Yes, it is a little bit confusing without "show unit orders".

**Comment by timfel** [comment]
Fixed in Stratagus master, will be in the next nightly rebuild of wargus

**Comment by timfel** [comment]
Fix is now in the nightly
