### ISSUE TITLE
Crash, MacOS, Tyr's Hand

### ISSUE THREAD

**Issue by Marcus10110** [Wargus/wargus#295]
I'm playing the 2.4.2 release on MacOS 10.14.2. 

(I was able to extract the files from the Warcraft II BNE purchased from Good Old Games on a Windows box, and then transferred over the `~/Library/Stratagus/data.Wargus` directory.)

All is well, except the game crashes repeatedly just a minute or two into Tyr's hand.

I could not find any std out or std error logs like there are on Windows. Here is the stack trace from the Mac crash file:

[tyrs_hand.txt](https://github.com/Wargus/wargus/files/3119920/tyrs_hand.txt)

I've had it crash several times, each time with a similar trace.

Hope this helps! And totally understand if there won't be time to look into this, or if nobody is manning the store. Regardless, thanks for the absolutely amazing piece of work! I'm going to try and skip the level for now.

**Comment by DinkyDyeAussie** [comment]
To me that stack trace seems a bit cryptic. Surely the strerr and stdout files get generated on MacOS?

**Comment by Marcus10110** [comment]
I'll try again when I have time. I do know that getting standard out from a *.app package is a challenge on Mac, but I can try running the binary directly instead of launching the app.

**Comment by Marcus10110** [comment]
whoops

**Comment by timfel** [comment]
@Marcus10110 this particular crash I recently fixed on master, but I have to kick off the CI to rebuild Mac binaries. I'll try to do it later today (travelling atm)

**Comment by timfel** [comment]
(by recently, I mean two days ago)

**Comment by timfel** [comment]
The fix is in the nightly
