### ISSUE TITLE
Latest version of CMAKE not finding Windows 8.1 SDK, only using Windows 10 SDK

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#298]
I have been trying to make the source into a Visual Studio 2017 project file, but the process stops when it tries to find the SDL library.

```
Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17763.
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SDL (missing: SDL_LIBRARY) (found version "1.2.11")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindSDL.cmake:191 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:634 (find_package)


Configuring incomplete, errors occurred!
See also "C:/Games/Stratagus/build/CMakeFiles/CMakeOutput.log".
See also "C:/Games/Stratagus/build/CMakeFiles/CMakeError.log".
```

I don't know how to make CMAKE target the 8.1 SDK, if that is what is causing the problem.

I never had this issue with VC 2015. I can still install that and use it, but I thought I would try the later 2017 version first.

If anyone can help I would appreciate it very much.

**Comment by timfel** [comment]
Did you get it working in the end (with the help in the other issue on stratagus?)

**Comment by DinkyDyeAussie** [comment]
Yes thank you Tim, all sorted now.

As soon as I got the Win32 libs from the repo and compiled the CMakeList script it worked perfectly, both in CMake and when I compiled the project in Visual Studio 2017.

Thanks for your help. It's great.

Now I can modify the code as I please and not have to stress about whether I can compile the code or not.
