### ISSUE TITLE
Multiplayer not working

### ISSUE THREAD

**Issue by ghost** [Wargus/wargus#303]
Cant connect to servers.

**Comment by Schnibbsel** [comment]
also you should consider having a discord

**Comment by timfel** [comment]
Multiplayer works here. What servers do you mean? There are no official servers you have to run your own.

**Comment by timfel** [comment]
If someone who uses discord wants to set that up, sure. I don't use it, so I won't be available there. There's a Gitter channel to discuss development that can be used for async chat

**Comment by benhbell** [comment]
hey @timfel Maybe you can explain what you mean that lan multiplayer works. I am unable to get Multiplayer working either. 

For me, I am able to select a map and make some config changes, but there is no option to create the game for the other computer to join.
![image](https://user-images.githubusercontent.com/966644/64068984-8c7b2580-cc0e-11e9-8257-3be3ce22b18d.png)

**Comment by benhbell** [comment]
Also tried a two games on the same machine with the ports set. 
![image](https://user-images.githubusercontent.com/966644/64069015-29d65980-cc0f-11e9-9ef6-047401dd3f2e.png)

**Comment by timfel** [comment]
@benhbell this looks broken, there should be buttons on the right of the window.

Anyway, in the terminal on the RHS, you are not setting the port correctly, it says the port is occupied by the first instance

**Comment by benhbell** [comment]
If there is no button available to create the multiplayer game then using the correct port wouldn't matter right?

**Comment by benhbell** [comment]
@timfel Just wanted to share that I do not think this is resolved as of version 2.4.2 release. I reproduced it today on latest

**Comment by timfel** [comment]
@benhbell hi, I haven't made a release since fixing this, it would only be fixed in the nightly
