### ISSUE TITLE
Wargus 2.4.2 crashing on certain maps

### ISSUE THREAD

**Issue by rav3nclaw3** [Wargus/wargus#309]
Basicly i have a problem running For the motherland maps, and Frontier map 2, map 1 played out normally.

I have tried extracting from GOG DOS and BNE version. Also iam on the Windows platform.
 any idea what could be wrong?

**Comment by Kintobor** [comment]
But that's the best part!

**Comment by timfel** [comment]
I have moved these maps/campaigns out of the game. No one is maintaining them.
