### ISSUE TITLE
Windows, No sound or music?

### ISSUE THREAD

**Issue by PizzaLawyer420** [Wargus/wargus#311]
2.4.1
No sounds, save for the initial click on buildings and moving through menus, play. I can't even switch the game to MIDI. Not sure if I have to re-install or re-extract the sound and music files. If I have to, then cdda2wav does not work as I've tried to use it.

**Comment by timfel** [comment]
We have migrated to SDL2_mixer on master, which completely replaces our custom music playing code with a library that many projects use. The upcoming 3.0.0 release should have this fixed
