### ISSUE TITLE
Russian font not working

### ISSUE THREAD

**Issue by ilwar2** [Wargus/wargus#312]
When i just try to use the original data from original english war2bne or from original english war2TD from DOS, i can build all the wargus data.
But when i switch the language in options menu from english to russian, all the menu bars become empty.
As i understand, that is because i have no russian chars in fonts: C:\Wargus\graphics\ui\fonts 

I tried to select russian SPK version as a data source on unpacking stage. But wargus can't handle it properly: REZDAT.WAR file is corrupted or w/e.
There's no any official russian version of war2, only unofficial translations.

I also found russian fonts built somehow for version 2.3 (no idea how they built it), 2.4.2 failed to start with error:
Invalid graphic (width, height) graphics/ui/fonts/game.png
Expected: (13,14) Found: (210,196)
I manually edited width 210 to 208 in paint, it have been started, but font became broken and russian chars haven't been appear in menus.

How to resolve that? How to make proper russian font or where to download it?

**Comment by tyusha0** [comment]
В данном случае подрезка холста не поможет: ширину и высоту холста делим на количество столбцов и строк символов (в том числе пустых) соответственно. Правим fonts.lua:  вводим полученную ширину и высоту для каждого шрифта отдельно.
   Есть идея попросить Тима сделать генератор шрифтов из ttf, но для этого надо закончить переводить в вектор хотя-бы один.

**Comment by ilwar2** [comment]
Спасибо, приятно видеть русскую речь!
На самом деле достаточно конвертера шрифтов из вар2-шных .fnt, только чтобы на вход подавать сами файлы .fnt, а на выходе были бы .png правильного вида. Тем более, шрифты в вар2 аутентичные, и в ttf таких не найти.
Как я понимаю, сейчас именно это и делается, только сейчас fnt-файлы автоматически ищутся в недрах mpq или war-файлов... и в случае русской сборки ищутся неуспешно.
А разобраться в wartool не разработчику проекта - сходу непросто, хотя идея понятна: вызвать несколько фукнций вроде ConvertFont, передав им правильные данные и получить файлы png.

А вообще - возможно у Вас уже есть сконвертированные русские шрифты (5 штук), которые бы давали возможность видеть русские буквы в меню и в остальных местах? И при этом совместимые с 2.4.2. Если я правильно понял, что все русские буквы в игре берутся именно из этих шрифтов в png-файлах.

Я сейчас поправил fonts.lua, задав ширину символов, ничего не изменилось, пункты меню по-прежнему пустые, без надписей на месте русских букв.

**Comment by tyusha0** [comment]
А да, вспомнил! Win 10 использует utf-8, похоже проблема в этом. Я сразу и не подумал, т.к. виндой редко пользуюсь. В какой кодировке ru_RU.po? 
  Шрифты с поддержкой utf могу скинуть на почту

**Comment by ilwar2** [comment]
У меня win7, запускаю на ней.
ru_RU.po и остальные переводы - в cp866.
на почту - было бы супер! Почта ilwar2@mail.ru

**Comment by timfel** [comment]
I don't speak russion - but I assume since @ilwar2 closed this you figured out a solution? Should we update code in the project?

**Comment by GeforsiK2022** [comment]
Russian Russian fonts were able to solve the problem, the same trouble with me, I changed the fonts and but the game does not understand Cyrillic, Russian letters in English -_-
