### ISSUE TITLE
Lastest wargus/stratagus problems with starting campaigns

### ISSUE THREAD

**Issue by ilwar2** [Wargus/wargus#313]
I use windows 7, night build of both wargus and stratagus.

Tried to start campaings, and got different errors:
From the motherland (alliance):
mission 1,2,3:
tried to start, got stratagus closed with errors: 
Can't load the graphic 'ui/scroll.png'
Can't load the graphic 'ui/scrolltall.png'
Can't load the graphic 'ui/kindland.png'
After i created these 3 files i can see a briefing, but when i try to click Exit or Continue, i return back to main menu.

For the motherland (Horde):
closes after i try to start with errors:
error in error handling
error in error handling
.......
error in error handling
Can't open file 'campaigns/human-ftm/0.smp': No such file or directory
error in error handling
g
error in error handling
error in error handling
......
Can't open file 'campaigns/human-ftm/0.smp': No such file or directory
error in error handling
[string "./campaigns/orc-ftm/level01o.sms"]:66298: attempt to call global 'AiRedRibbon_Define_Unit_2014' (a nil value)
stack traceback:
	[string "./campaigns/orc-ftm/level01o.sms"]:66298: in main chunk
	[C]: in function 'StartMap'
	[string "scripts/guichan.lua"]:824: in function 'RunMap'
	[string "scripts/menus/campaign.lua"]:180: in function '?'
	[string "scripts/menus/campaign.lua"]:329: in function 'RunCampaign'
	[string "scripts/menus/campaign.lua"]:223: in function <[string "scripts/menus/campaign.lua"]:218>
	(tail call): ?
	[string "scripts/guichan.lua"]:335: in function <[string "scripts/guichan.lua"]:333>
	[C]: in function 'run'
	[string "scripts/menus/campaign.lua"]:308: in function 'RunCampaignSubmenu'
	...
	[string "scripts/guichan.lua"]:1034: in function 'callback'
	[string "scripts/guichan.lua"]:335: in function <[string "scripts/guichan.lua"]:333>
	[C]: in function 'run'
	[string "scripts/guichan.lua"]:1039: in function 'RunSinglePlayerTypeMenu'
	[string "scripts/guichan.lua"]:1547: in function 'callback'
	[string "scripts/guichan.lua"]:335: in function <[string "scripts/guichan.lua"]:333>
	[C]: in function 'run'
	[string "scripts/guichan.lua"]:1576: in function 'BuildProgramStartMenu'
	[string "scripts/guichan.lua"]:1588: in function 'RunProgramStartMenu'
	[string "scripts/guichan.lua"]:1710: in main chunk

I tried to start Aleona instead of wargus (these are Aleona's campaigns, aren't them?). Also not working with lots errors.
Should that be fixed any way to work?

**Comment by timfel** [comment]
I've removed those campaigns for now. If there's interest we can get them to work again in the future

**Comment by majintorrinco** [comment]
Hey, unrelated, but I saw someone with your name (ilwar2) in the Warcraft 2 GOG forums, looking for rare versions/languages of the game. Was that you?

**Comment by ilwar2** [comment]
> 
> 
> Hey, unrelated, but I saw someone with your name (ilwar2) in the Warcraft 2 GOG forums, looking for rare versions/languages of the game. Was that you?

Yes, that's me, do you have some more languages or versions?

**Comment by majintorrinco** [comment]
Yes! I do have brazilian versions of both ToD and BtDP, in return I was hoping to make this language work with GOGs version, could you help me with that? Email me at andremaajin @ gmail.com

**Comment by timfel** [comment]
@ilwar2 do you have the chinese version, yet? it's different enough that we cannot quite extract all the data, yet. (i was looking into it, but alas, there's never enough time)

**Comment by Kintobor** [comment]
I was in the middle of updating them when Wargus was transferred from Launchpad to Github. Never figured out Github so never fixed them.

Maybe one day. :D

**Comment by ilwar2** [comment]
Yes, i looked into chinese version, i didn't understand what to to with FONTBIG.CFN FONTMED.CFN files, looks like should extract chinese fonts from it some way..

Also i have korean version for dos also, it requires the same chinese exe and uses it's own korean data and font files as i understand. Though i didn't check it carefully...
