### ISSUE TITLE
Add resources income

### ISSUE THREAD

**Issue by Morkatos** [Wargus/wargus#314]
Hello everybody, and happy new year 2020 !

I am working on a mod for Wargus to modify Warcraft II gameplay (add new upgrades to buy, put shield/sword/axe upgrades on 5 levels instead of 2, possibility to upgrade guard/cannon towers to increase its strengh up to have a level 3 tower, the possibility to upgrade spells...), but there is something I can't do.

Can someone tell me how to add the possibility for a building to produce resources over time (like in Total Annihilation) ?
If I want for example that the town hall produces 1 gold every 5 seconds, what should I add in scripts > human > units in the town hall section ?

I already know for example that if I add a line with "RegenerationRate = 1,", I give to the unit/building the capacity to regenerate Hitpoints, but if I want resources over time ?

In Bos Wars, the function is "MagmaProductionRate = 12," (for magma pump) and "EnergyProductionRate = 20," (for power plant), but how can I have the same thing in Wargus (with gold/wood/patrol) ? I have been trying to have the same for 2 weeks in Wargus with gold in Town hall, without succes.

I am sure there is a way to do it, I know that in the "For the Motherland" campaigns, we earn permanently resources over time (100 gold, 50 wood and 50 patrol every 30 steps, to be exact), it is in \scripts\ai\ai_redribbon_2014.lua, but the function does not works with an unit/building.

Can anybody help me ?

**Comment by Andrettin** [comment]
You can use a custom Lua function that is called every second for units of that type.

In the unit type definition, add:
```
OnEachSecond = IncreaseGold
```

And then define the IncreaseGold function elsewhere, e.g.:

```
function IncreaseGold(unit) -- this is called every second
	-- code here
end
```

**Comment by Morkatos** [comment]
OK, thanks for your answer, I understood now that I must add this function to make it possible.

But do you know what I exactly should enter as a function to do this (I have to add it in Wargus > scripts > human/orc >units, isn't it ?) ? I don't know how to program in C++, I hope it's not too complicated.

In fact, if I managed to modify the game until now, it is mainly because I know well Warcraft2 (I had the PsOne version), and because I can understand what in Wargus files changes what. I learn fast, but I don't know everything.
I added new upgrades by taking again those already existing in the files of the game. For example, I added an upgrade allowing ships to autorepair in foundry, through "berserker regeneration" upgrade, I just had to add the information about the new upgrade (cost, time...) in the "upgrade" and "button" files.

Do you know how i should go about it ?

**Comment by Andrettin** [comment]
It would be similar to what is in the FtM function you mentioned, the main difference being that you need to get the player from the unit (which is given as a parameter in the function).

Something like this:
```
function IncreaseGold(unit) -- this is called every second
	local player_index = GetUnitVariable(unit, "Player")
	local current_gold = GetPlayerData(player_index, "Resources", "gold")
	SetPlayerData(player_index, "Resources", "gold", current_gold + 100) -- +100 gold every second
end
```

**Comment by Morkatos** [comment]
I am sorry, but it does not work.
I added your function (the 5 lines you just gave me) in Wargus>scripts>human, in "units.lua", at the very bottom of the file, and I added  "OnEachSecond = IncreaseGold," somewhere under "DefineUnitType("unit-town-hall", { Name = _("Town Hall")," (where you have informations, like Hit points) to have a Town Hall providing gold over time.

I launched the game. It works (it usually does not launch if I add in a game file a function that it does not recognize), but I have no gold income with town hall when I start the first mission Humain campaign.

I probably missed something, but what ?

**Comment by Andrettin** [comment]
Could you post your code? That would make it easier to see if something is wrong.

**Comment by Morkatos** [comment]
OK, here is a copy of the file, it's a txt because i can't put the original LUA file :
[units.txt](https://github.com/Wargus/wargus/files/4483604/units.txt)

**Comment by Andrettin** [comment]
Thanks! The issue is that the function needs to be defined in the file before you use it at the town hall's definition. Try putting the function definition at the top of the file and see if it works (I tested and it did for me).

**Comment by Morkatos** [comment]
Great !!! It works !
Thank you very much, you're a genius !

Now, I will try to reduce the amount of gold earned, and make the same thing for wood and patrol (with lumber mills and refineries), it will be easy, I'm just going to redo a slightly modified version of your code !

**Comment by Andrettin** [comment]
You're welcome, I'm glad it's working fine now :)
