### ISSUE TITLE
Define Group Keystroke doesn't work

### ISSUE THREAD

**Issue by Go-rom** [Wargus/wargus#317]
Hello,

i can't use [CTRL ##] keystroke in order to define groups, it just doesn't work. No problem with the other keystrokes.

Wargus 2.4.2
Linux Mint 19.2 Cinnamon 64 bits

**Comment by benhbell** [comment]
Unable to replicate your issue on ubuntu 19.04 or mac osx 11.13

Is there any chance that you have a program interfering with that shortcut?

**Comment by Go-rom** [comment]
Hello,

i'll look into that and let you know.
Maybe some cinnamon spices, i'll do the tests.

Thank you

**Comment by Go-rom** [comment]
Despite the upgrade to 2.4.3 and the background applications closed, i'm still encountering the issue.
The next release of Linux Mint is close, i'll run a new test with a clean install.

**Comment by benhbell** [comment]
I might download a release just to replicate it too.

**Comment by timfel** [comment]
Not sure what the issue was with 2.4.2 and 2.4.3, but there was a bug with this in the rewritten input code in 3.0.0 on master, which I now fixed.

**Comment by Go-rom** [comment]
Ok thank you for keeping me updated on this matter.

When 3.0.0 will be available through the PPA, i'll run a test and get back to you.

**Comment by Go-rom** [comment]
Hello @timfel 
First, let me wish you an happy new year.

The previous faulty keystroke is working now with 3.0.0 so thank you very much.
But the behavior is strange :  
- If i want to define a group with "CTRL + #", i have to use the inline numbers on my keyboard above the letters. (can't define with the numpad)
- If i want to select a group with "#", i have to use the numpad (can't select with inline numbers even with caps lock enabled)

I also tested the "## - center on group" keystroke but i didn't succeed in using it.

**Comment by timfel** [comment]
Hm, not sure how that can happen. I don't have any keyboards with numpads, and all of the behaviours your describe work exactly as they should. I can define with number keys and select with them. I jump to groups by double tapping a number key.

I actually think we don't support using the numpad keys for this at all, but I'll see if i can find anything in the code that sticks out.
