### ISSUE TITLE
Fmv streched

### ISSUE THREAD

**Issue by pelupessy** [Wargus/wargus#330]
![Screenshot_2020-06-14_14-22-07](https://user-images.githubusercontent.com/5619600/84585657-02264a00-ae4d-11ea-9eee-57e14a3a8da7.png)
Latest version from launchpad on Ubuntu 20.04 on 1080p monitor. (image windowed, but fullscreen has the same problem)

FMV's are stretched only horizontally.

Expected behaviour: vertical stretch to keep the original aspect ratio for fmv.

Edit: aspect ratio of background artwork is also wrong (eg: menu and mission briefings).

**Comment by timfel** [comment]
With widescreen resolutions, this is expected. The UI doesn't keep the aspect ratio of the original. This was (and still is) the desired behaviour for some people. Aspect ratio correct scaling is implemented and default in master and will be in the next release, with an option to go back to the old behaviour of stretching to fill the screen.

**Comment by pelupessy** [comment]
Hmmm, is this implemented separately for fmv's?

Looking at the fmv files (in .stratagus), they seem a bit strange: they are all in 4:3 aspect ratio, but, other than the intro, they look squeezed horizontally. The intro looks correct, but has black bars, resulting in it looking squeezed vertically when it is played in wargus. I would expect the intro to be cropped to remove the black bars, then scaled to full 16:9, the other fmv's stretched to full 16:9, but the other artwork merely scaled while preserving their aspect ratio.

**Comment by timfel** [comment]
The fmv's between the DOS and Battle.net versions have different aspect
ratio, which we try to account for in the extraction tool. It's possible,
though, that something is broken there. The intro does indeed have a
different aspect ratio. It should 320x160, whereas the other videos are
320x144

**Comment by pelupessy** [comment]
Thanks for the info!
