### ISSUE TITLE
Defining Wargus data and save location?

### ISSUE THREAD

**Issue by mgtroyas** [Wargus/wargus#333]
Wargus seeks Warcraft 2 extracted data, on Windows, on path "%appdata%\Stratagus\data.Wargus"

I'm trying to run Wargus as a portable application, so I'd need to store the data on a folder alongside the executable. But I haven't found a way to tell Wargus to seek the data on another path. Stratagus "-d" command line parameter isn't finding it either.

**Comment by timfel** [comment]
If you use the stratagus.exe, you can just use `-d` to point to the location of the data.Wargus folder.
