### ISSUE TITLE
"There was an error copying the data, could not discover contributed directory path" MacOS Big Sur

### ISSUE THREAD

**Issue by apachey** [Wargus/wargus#337]
Hello,

I was trying to install Wargus, but every time I got this error:
`There was an error copying the data, could not discover contributed directory path.`
Continued by: 
`Wargus data was not extracted, is corrupted, or outdated. You need to extract it from original Warcraft II DOS REZDAT.WAR or BNE INSTALL.MPQ/INSTALL.EXE file.`

Launching the app from the Applications folder

**MacOS Big Sur 11.0.1**
**Wargus.app 3.0.0**

**Comment by timfel** [comment]
Hi,
I'm sorry, but unfortunately there are no Stratagus developers that have a Mac anymore, so we cannot test or fix issues on macOS. The last few issues I fixed by just guessing and hoping for the best and when the person reporting an issue didn't reply back, I didn't know if it worked. Unless someone who can help with development on Mac joins the team, we will just drop support for macOS in the 3.0.0 release.

**Comment by timfel** [comment]
The unfortunate problem is that Apple is making it hard to impossible for developers on other platforms to build and test something for macOS. I am not allowed to have a virtual machine with macOS on my Linux machine unlike with Windows, so I would have to buy a Mac to test anything.

**Comment by apachey** [comment]
Oh, I see... Can I help somehow with it? I have no coding experience, though. Maybe I can try previous versions? Wargus is just the only option to play Warcraft on Mac natively.

**Comment by timfel** [comment]
Well, there's unfortunately not much to help with unless you know how to compile and experiment with the code on a Mac ☹️

**Comment by apachey** [comment]
Got it. Thank you anyway.

**Comment by msikma** [comment]
I'm also having problems with this. macOS 10.14.6 Mojave, still trying to figure out how to solve it. Using the version downloaded off the site and `wartool` says it's version 3.0.0.

There's no documentation of how to use wartool manually properly that I can find, so I don't know if I'm doing it correctly, but when I tried to use it the following happened:

```
$ pwd
/Applications/Wargus.app/Contents/MacOS
$ ./wartool -v ~/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2/

Detected UK/Australian original DOS CD
Extract from "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data" to "data"
Please be patient, the data may take a couple of minutes to extract...
Archive "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/rezdat.war"
mkdir data
Copied /Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/rezdat.war->data/rezdat.war
Archive "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/strdat.war"
mkdir data
Copied /Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/strdat.war->data/strdat.war
Archive "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/maindat.war"
Ignore entry 25 in archive (invalid uncompressed length)
Ignore entry 32 in archive (invalid uncompressed length)
Ignore entry 68 in archive (invalid uncompressed length)
Ignore entry 431 in archive (invalid uncompressed length)
Ignore entry 437 in archive (invalid offset)
mkdir data
Copied /Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/maindat.war->data/maindat.war

ffmpeg -y -i "data/videos/logo.smk" -codec:v libtheora -qscale:v 31 -codec:a libvorbis -qscale:a 15 -pix_fmt yuv420p "data/videos/logo.ogv"
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, smk, from 'data/videos/logo.smk':
  Duration: 00:00:11.67, start: 0.000000, bitrate: 544 kb/s
    Stream #0:0: Video: smackvideo (SMK2 / 0x324B4D53), pal8, 320x160, 12 tbr, 12 tbn, 12 tbc
    Stream #0:1: Audio: smackaudio (SMKA / 0x414B4D53), 22050 Hz, mono, u8
Stream mapping:
  Stream #0:0 -> #0:0 (smackvideo (smackvid) -> theora (libtheora))
  Stream #0:1 -> #0:1 (smackaudio (smackaud) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
Output #0, ogv, to 'data/videos/logo.ogv':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: theora (libtheora), yuv420p(progressive), 320x160, q=2-31, 200 kb/s, 12 fps, 12 tbn, 12 tbc
    Metadata:
      encoder         : Lavc58.91.100 libtheora
    Stream #0:1: Audio: vorbis (libvorbis), 22050 Hz, mono, fltp
    Metadata:
      encoder         : Lavc58.91.100 libvorbis
frame=  140 fps=0.0 q=-0.0 Lsize=     529kB time=00:00:11.66 bitrate= 371.4kbits/s speed=16.6x    
video:396kB audio:122kB subtitle:0kB other streams:0kB global headers:7kB muxing overhead: 1.961796%
Archive "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/sfxdat.sud"
mkdir data
Copied /Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/sfxdat.sud->data/sfxdat.sud
Archive "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/rezdat.war"
Archive "/Users/msikma/Files/Games/DOSBox/Chicago/Mount/C/Games/WAR2//data/snddat.war"
Wrong type 00000fa0, expected 000007d0
```

And then it exited with an error and a pop-up "This version of the data is not supported". [It seems to have extracted a bunch of files.](https://gist.github.com/msikma/3177e4a95bb3e6aaad0b8229226c91bb) But unfortunately, still the same error when I try to run the game with `./wargus -d ./data`.

So maybe there's something wrong with this particular DOS Warcraft 2 CD, and this might be causing problems for people? I'll see if I can try with a different version of the game. Also, if you have any other suggestions for things I can try on the command line, let me know and I'll give them a try.

**Comment by timfel** [comment]
@msikma did you compile yourself? The latest binaries are some random state before the actual release, because we dropped support for macOS entirely, due to the reason above (Apple making it impossible to develop for macOS without buying their hardware).

The error looks like the version of the CD is simply not supported, you could try a different version.

**Comment by timfel** [comment]
I had to drop support for macOS, because Apple seems to be actively making it harder and harder for cross-platform software to build, test, and ship without buying any Apple dev tools or licenses :(
