### ISSUE TITLE
[War1gus] Hallfiry's MacWar1 data converters -- possibly useful?

### ISSUE THREAD

**Issue by SenhorFlibble** [Wargus/wargus#344]
The War1gus page mentions that extraction and use of MacOS resources is not fully supported yet. Since the recent GOG release of Warcraft 1 provides the hybrid CD ISO with both DOS and Mac data, the latter is now available to non-Mac users so it'd be pretty nice to have full support of Mac resources.

A while ago <b>Hallfiry</b> made a set of converter tools for both DOS and Mac data files, perhaps these could be of use to you?<br>
<a href="http://www.blizzardarchive.com/pub/index.php?id=war1">http://www.blizzardarchive.com/pub/index.php?id=war1</a>

**Comment by timfel** [comment]
I've seen those. Unfortunately, there's no source code for the tools themselves, they only work on windows, and the documentation is a little too incomplete to build the extraction from scratch for me :(

**Comment by timfel** [comment]
I actually started working on the Macintosh version extraction a few years ago: https://github.com/Wargus/war1gus/issues/78
