### ISSUE TITLE
Should the game start right after entering multiplayer session?

### ISSUE THREAD

**Issue by SpiReCZ** [Wargus/wargus#346]
Hey,
me and my brother started playing wargus MP and we noticed that if you first run the game and create multiplayer session that the game is stuck.
You are not able to move your peon or anything at all untill you click on diplomacy and click OK (we usually ally ourselves).

version: 3.0.0

We usually play 2 players against 2 AI's. The issue only occurs at first start of the game (not sure if first start of the player with the server or the client player).

**Comment by timfel** [comment]
I'm not sure what the issue is ;) For these questions, maybe it'd be better to join our discord. But to answer the question: no, it shouldn't, every player needs to click the ready button first

**Comment by SpiReCZ** [comment]
I accidentally submitted the issue before added the description. But it should be clearer now.

**Comment by benhbell** [comment]
I've encountered this issue sporatically. More often when fog of war is turned on. Music plays, and it is possible to select units, but not give them commands. I will keep and eye out to see if I can reproduce it better.

**Comment by timfel** [comment]
Fixed

**Comment by SpiReCZ** [comment]
awesome
