### ISSUE TITLE
Map Editor Issues

### ISSUE THREAD

**Issue by sblatnick** [Wargus/wargus#349]
The In-Game Map Editor has various usability issues.

Specifically:

- [x] - Under "Units", the 2 cancel buttons at the first of both human and orc lists actually places an X for start position.  When playing the game, the X becomes permanently shown on the map and is attackable.
- [x] - There is no way I could figure out to delete Units once placed other than Ctrl + Z.
- [x] - The select box item for "Start Position" doesn't seem to do anything.
- [x] - Setting a player's properties to human vs orc does not filter the Units.  That might be okay if you want to allow one player to have both types.  However, I think it would be beneficial to place the units within their own section, so you don't have to scroll through all of them together.
- [x] - Units only display 9 items and scroll horizontally.  It would work better to use the full vertical space for higher resolution screens, and to scroll vertically with the scroll wheel.
- [x] - Gold Mines are owned by players.  Neutral units like gold mines should not be owned.  When playing, after I destroyed all enemy units, I still had to attack the gold mines.  I was unable to harvest their gold myself.  I think there should be 3 sections of units: Human, Orc, Neutral  (Incidentally, my game randomly froze every unit while I was trying to finish destroying the enemies mines.  Only the music kept playing and I could scroll around but not click on anything, even the menu.  I do not know if destroying the mines would have resulted in a victory.  I checked and memory usage was still quite low despite the frozen units.)

Nitpicks:

- [ ] - I noticed that the max 200 units is enforced differently than the original game.  If you were training simultaneously from multiple buildings, you could exceed the max.  That strategy proved ineffective in Wargus.  I wonder if we could allow the map creator to specify a max or make it limitless?  I also noticed the farms could create food for >200, which made me think I could create more units until I tried and couldn't.
- [ ] - Setting to fullscreen the game wouldn't persist between plays until I manually edited the config file.
- [x] - Saving your progress on a map requires you to enter the name manually again and doesn't prompt to warn you are overwriting an existing file.  I suggest "Save" and "Save As" functionality.  Also, the main menu doesn't need this functionality.

Desktop:
- OS: Linux Debian Bullseye/Sid
- Version 3.0.0-0202012191004ubuntu21.04.1

PS: I LOVE Wargus.  Brings back all of the nostalgia and allows me to run on linux without using wine, plus adds features!  Great project!  I hope this feedback helps!

**Comment by timfel** [comment]
Thank you for those detailed issues. Some of them we can fix easily, some of them not. Especially since Stratagus is a generic engine for different strategy games and Wargus is just one of them, some Warcraft specific things cannot be easily integrated in the map editor. But I will try to go through the list and comment on what will be fixed how and why :)

Also, I'm glad you like Wargus :)

**Comment by timfel** [comment]
* I removed the "units" start locations, they are not to be used in Wargus
* You can use backspace to delete units - I added an F1 help menu to say that
* The "Start position" select box item now works
* (Unit filtering is not done)
* In higher resolutions, the sidebar is now filled: 
![image](https://user-images.githubusercontent.com/46235/119250800-deae6800-bba2-11eb-8e39-5e2abb64fdf4.png)
* (Gold mines still have to be manually set to neutral. But the help menu shows you that you can just hover over a gold mine and press the "0" key)

**Comment by timfel** [comment]
> Saving your progress on a map requires you to enter the name manually again and doesn't prompt to warn you are overwriting an existing file. I suggest "Save" and "Save As" functionality. Also, the main menu doesn't need this functionality.

At least now it will remember the map name, so you can quickly press F11 and "S" to save

**Comment by timfel** [comment]
* scrolling with the scroll wheel now also works to change the slider

**Comment by timfel** [comment]
Units are still all offered for all players, but there's now additional spacing between orcs, humans, and neutral, to make it easier to see which belongs where

**Comment by timfel** [comment]
Closing this now, since the fullscreen issue and unit limit issues need to be dealt with separately.

**Comment by sblatnick** [comment]
Awesome!  Thank you so much!

**Comment by timfel** [comment]
I just realized there is already a lua function to change the unit limit, just no UI for it: https://stratagus.com/lua_bindings.html
```
SetAllPlayersUnitLimit
SetAllPlayersBuildingLimit
SetAllPlayersTotalUnitLimit
```
