### ISSUE TITLE
The Skeleton isn't using it's legacy sounds "Skeleton Death" & "Skeleton Move"

### ISSUE THREAD

**Issue by 77Mynameislol77** [Wargus/wargus#352]
Basically, the Skeleton isn't using it's proper sounds and are just using the generic Orc sounds

I've managed to fix it myself by simply adding

`MakeSound("skeleton dead", "neutral/units/skeleton/dead.wav")
MakeSound("skeleton-acknowledge", "neutral/units/skeleton/acknowledgement/1.wav")`

To "sounds.lua", &

`  Sounds = {
    "selected", "skeleton-selected",
    "acknowledge", "skeleton-acknowledge",
    "help", "basic orc voices help 1",
    "dead", "skeleton dead"} } )`

to the unit in "units.lua", i also had to manually extract the sounds myself.

It's a simple fix, but i don't know how i would go about making the extract script extract these sounds, otherwise i would've done it myself and put up a pull request.

**Comment by timfel** [comment]
Thanks for the issue report. Where did you find the skeleton wav files? I assume somewhere in the War2Dat.mpq? Do you know their names in those files? Then I can add them to the extraction tool (at least for BNE)

Basically, we need a couple of lines here: https://github.com/Wargus/wargus/blob/master/wartool.h#L1719
Something like:
```
{Q,8,"sounds/neutral/units/skeleton/dead.wav",             1, 1, 0, 0, "War2Dat.mpq", "??? what goes here ???"},
{Q,8,"sounds/neutral/units/skeleton/acknowledgement/1.wav",              1, 1, 0, 0, "War2Dat.mpq", "??? what goes here ???"},
```

And then also here: https://github.com/Wargus/wargus/blob/master/wartool.h#L1266

**Comment by 77Mynameislol77** [comment]
Yes, their names are 

"Gamefx\misc\Skeleton Death" & "Gamesfx\misc\Skeleton Move"

I found them using WinMPQ on the Battle.Net Edition MPQ's.

**Comment by 77Mynameislol77** [comment]
While we're at it, the Daemon death sound is actually supposed to be just "Explosion"

**Comment by 77Mynameislol77** [comment]
In the latest version of Wargus, the issue remains, it appears that they aren't extracted.
