### ISSUE TITLE
Peasants cutting invisible tree

### ISSUE THREAD

**Issue by SimoneStarace** [Wargus/wargus#354]
**Bug description**
I was testing my custom map and I simply send my peasants to cut some trees because I needed lumber. For some strange reason some peasants started to cutting a tree where there weren't any trees.

**How to reproduce this bug**
1. Just send peasants/peons

**Expected behavior**
They shouldn't cut trees where there aren't any,

**Screenshots and Logs**
![Cut1](https://user-images.githubusercontent.com/52276600/143302842-9fa9511e-742b-417e-8e30-797354373821.gif)
![Cut2](https://user-images.githubusercontent.com/52276600/143302870-23740688-bf25-4549-8c43-a9d7016711c1.gif)

**Desktop:**

- OS: Ubuntu 20.04.2 LTS x86_64
- Version: 3.1.2

**Comment by abenedic** [comment]
Hi, I am very sorry, but I cannot see any picture. Could you try it again from a later build and upload it again?

**Comment by SimoneStarace** [comment]
> Hi, I am very sorry, but I cannot see any picture. Could you try it again from a later build and upload it again?

I have uploaded two gifs related to the problem.

**Comment by timfel** [comment]
This shouldn't happen anymore (unless forest regeneration is on). We now use a counter to check a field is empty.
