### ISSUE TITLE
[BDP] Wrong units on Human mission 7

### ISSUE THREAD

**Issue by elrandira** [Wargus/wargus#358]
**Describe the bug**
You are supposed to start the mission with 3 paladins with exorcism and healling instead you have knights lvl 1.

**To Reproduce**
Play mission 7 of human campaign in expension Beyond the dark portal.

**Expected behavior**
Start the mission with 3 paladins lvl 4 with healing and exorcism

**Screenshots and Logs**
This video shows what is expected: https://youtu.be/TB9ByMHXtzM?t=2933
This is from Wargus:
![image](https://user-images.githubusercontent.com/82774041/115155864-03825d80-a082-11eb-9bee-b59464dc3977.png)

**Desktop (please complete the following information):**
- OS: Windows 10 v. 20H2
- Wargus stable v3.0.0 dec 2020

**Comment by elrandira** [comment]
Oops, sorry duplicate of https://github.com/Wargus/wargus/issues/341

**Comment by elrandira** [comment]
I was curious and end up digging into the code. In pud.cpp::UnitScriptNames there are few unknown units and wonder if it could be  these missing paladins..
Are there any shareable documentations on the content of install.exe from the BNE or how PUD are written?

**Comment by timfel** [comment]
i don't think its the unknown units. the upgrades already researched are stored in the mission and read out from there, but the way the paladin upgrade works in wargus is different from the original game, so we need a bit of extra code in Lua to fix this

**Comment by Erenussocrates** [comment]
All you need to do is change the corresponding Knight unit into paladin in the .sms file.

**Comment by timfel** [comment]
it's not that simple, the sms file is extracted, and the original wc2 map has knights there. the way it mus work is when the paladin upgrade is researched already, we should trigger replacement of the knights upon game start.
