### ISSUE TITLE
War1gus extraction doesn't work on GOG version default installation folder due to the '&' in the path

### ISSUE THREAD

**Issue by sickchicken** [Wargus/wargus#366]
Finished installing it, executed it and it says 'stratagus failed to load data(War1gus)' 'Wargus data was not extracted(Wargus)' or something like it. I have no CD of course.

**Comment by timfel** [comment]
You have to extract the gog installer and point Wargus to the extracted install.exe. I think it also works from the installation folder, but I'm not on my computer and cannot check right now

**Comment by timfel** [comment]
the error message that it failed to load the game data is expected, that's what it always says on first launch :)

**Comment by sickchicken** [comment]
I did what it tell me to do, but didn't work. 
War1gus : It points data.mpq and it does some extracting stuff in cmd, but does no good. Still, same message and won't work.
Only Wargus works so far.

**Comment by timfel** [comment]
ah, this issue is about war1gus? I assumed wargus, because you opened the issue here and not on war1gus :)

i forgot how it was with war1gus, but it should work, since i extract from the gog version every few weeks during development. Make sure that none of your paths have anything funny in them (your username, the data path of warcraft 1, and the installation path of war1gus) - all of these should only be letters or numbers, everything else can cause issues during extraction

**Comment by sickchicken** [comment]
It works! appreciate it. Probably, It's because GOG version has "&" in its folder name.
I think it would be wonderful if you put that info on War1gus main page(to change folder name like that)

**Comment by sickchicken** [comment]
If another question doesn't bother you, is there unit lua for War1gus too? I can find unit data in Wargus, but can't find one in War1gus.

**Comment by timfel** [comment]
yes, just in the scripts folder in your documents\Stratagus\data. War1gus folder :)

**Comment by sickchicken** [comment]
Oh crap, I should've edited my comment, not deleting it. I mean, can I edit human and orc unit seperately? I think I could do that in old retro unit editor.

**Comment by timfel** [comment]
no, you cannot. well, you can if you learn how to write the lua code for it, but it's not set up the same way as in Wargus :)

there's a discord if you want to learn more about it with people who can help :)

**Comment by sickchicken** [comment]
I appreciate that.

**Comment by timfel** [comment]
After a little bit of work, I can now successfully extract from the default installation folder
