### ISSUE TITLE
We need a new Tutorial video on how to install wargus

### ISSUE THREAD

**Issue by Erenussocrates** [Wargus/wargus#367]
The video tutorial on stratagus.net seems to be way outdated by now, and some of my friends seem to be having problems installing the newer version. We need an updated thorough tutorial.

**Comment by timfel** [comment]
Yes :) If you feel like making one, I can upload it to the Stratagus YouTube channel and link it from the website :) Otherwise, I'll do it sometime

**Comment by Erenussocrates** [comment]
And also a tutorial on how to mod wargus. Seems like the file paths were changed somewhere along the line on the newer version.

**Comment by timfel** [comment]
@SimoneStarace is making a video :)

**Comment by SimoneStarace** [comment]
Hi everyone.
@timfel the video I sent to you on discord is the complete one.

@Erenussocrates 
> And also a tutorial on how to mod wargus. Seems like the file paths were changed somewhere along the line on the newer version.
If you can do a video on how to show how to mod Wargus it would be helpful for anyone.

**Comment by timfel** [comment]
The release video for 3.1.0 has extensive demo of the extraction process: https://youtu.be/6a4dy16q49c
