### ISSUE TITLE
How to extract music from CD

### ISSUE THREAD

**Issue by andmarti1424** [Wargus/wargus#368]
Hello. I managed to get wargus running, but I dont have music.
I have retried trying to get the files in music folder with:
` ./wartool -r $HOME/virtual-drives/1 $HOME/.stratagus/data.Wargus`
but output is:
``Please be patient, the data may take a couple of minutes to extract...
Archive "/home/mongo/virtual-drives/1/data/rezdat.war"
Archive "/home/mongo/virtual-drives/1/data/strdat.war"
Archive "/home/mongo/virtual-drives/1/data/maindat.war"
Ignore entry 25 in archive (invalid uncompressed length)
Ignore entry 32 in archive (invalid uncompressed length)
Ignore entry 68 in archive (invalid uncompressed length)
Ignore entry 431 in archive (invalid uncompressed length)
Ignore entry 437 in archive (invalid offset)
Archive "/home/mongo/virtual-drives/1/data/sfxdat.sud"
Archive "/home/mongo/virtual-drives/1/data/rezdat.war"
Archive "/home/mongo/virtual-drives/1/data/snddat.war"
Ignore entry 46 in archive (invalid uncompressed length)
Archive "/home/mongo/virtual-drives/1/data/muddat.cud"
Found CD-ROM device: fuseiso
cdparanoia III release 10.2 (September 11, 2008)

Using cdda library version: 10.2
Using paranoia library version: 10.2
Checking fuseiso for cdrom...
        Could not stat fuseiso: No such file or directory
Done.
Extracting from expansion subdir
``
btw i have fuseiso installed on my system.
in music folder I have some midi files, but music shoulnt be wav or ogg or something like that?
`ls
 .                    'Human Battle 4.mid'  "I'm a Medieval Man.mid"  'Orc Battle 4.mid'
 ..                   'Human Battle 5.mid'  'Main Menu.mid'           'Orc Battle 5.mid'
'Human Battle 1.mid'  'Human Briefing.mid'  'Orc Battle 1.mid'        'Orc Briefing.mid'
'Human Battle 2.mid'  'Human Defeat.mid'    'Orc Battle 2.mid'        'Orc Defeat.mid'
'Human Battle 3.mid'  'Human Victory.mid'   'Orc Battle 3.mid'        'Orc Victory.mid'
`
Thanks for your help.

**Comment by timfel** [comment]
The midi files also work, provided you have the appropriate midi libraries installed. Are you extracting from a mounted ISO? In that case, you will only get midi files, afaik you need a cue/bin mounted device or a real CD to extract the CD audio tracks.

To know if midi libraries are installed, check the output when starting wargus. It should say something like:
```
Supported sound decoders: WAVE AIFF VOC MOD MID OGG OPUS MP3 FLAC
Supported music decoders: WAVE FLAC OGG OPUS MPG123 MODPLUG NATIVEMIDI MOD MIDI MP3
```

If `MIDI` is missing here, you need to install a midi library supported by SDL2.
