### ISSUE TITLE
GOG WC1 & WC2 support?

### ISSUE THREAD

**Issue by 2mg** [Wargus/wargus#370]
I can't seem to make both games work, are GOG versions supported?

Both war1gus and wargus just get "application has stopped working". Are there any logs to check why?

**Comment by timfel** [comment]
Yes, the GoG versions are supported. What operating system are you on?

**Comment by 2mg** [comment]
Win 7x64. Did you deprecate it?

**Comment by timfel** [comment]
No. We still support XP

**Comment by timfel** [comment]
but "application has stopped working" seems weird. Anything in `My Documents\Stratagous\stdout.txt` or `My Documents\Stratagous\stderr.txt`?

**Comment by 2mg** [comment]
Waiting until new versions, current have issues with extractors (war1gus/wargus), thank you!
