### ISSUE TITLE
Windows and Linux Lua files differ slightly for same version

### ISSUE THREAD

**Issue by benhbell** [Wargus/wargus#375]
**Describe the bug**
Extracting the game content for wargus on windows creates a slightly different `wc2-config.lua` file that on linux. This causes cross-platform multiplayer to break.

**To Reproduce**
1. Install wargus on linux
2. Install wargus on windows 10
3. Run them the first time to extract game content
4. wc-config.lua files will be slightly different sized
![Screenshot from 2021-07-13 12-12-53](https://user-images.githubusercontent.com/966644/125501175-99bc8a21-29c5-4957-9557-733b1cafedef.png)

**Expected behavior**
Files should be the same, or lua checks when playing multi-player should ignore file ends

**Desktop:**
 - OS: Windows, Ubuntu and Pop_OS
 - Version 3.1.0

**Comment by timfel** [comment]
Fixed with https://github.com/Wargus/stratagus/pull/353
