### ISSUE TITLE
Can't extract english GOG version of the game with build 3.1.1.

### ISSUE THREAD

**Issue by stunner345** [Wargus/wargus#378]
I can't extract WC1 or WC2 data from english GoG versions with the new version 3.1.1. It fails everytime. With 3.1.0 it works normal.
System: Windows 10

**Comment by ThunderDragonRandy** [comment]
I'm having this problem too. I thought it was just me.

**Comment by MSTVD** [comment]
Same

**Comment by timfel** [comment]
Yes, the 3.1.1 release is bugged in that regard on Windows. But there's no real difference between 3.1.0 and 3.1.1, it's really just a fix for older Linux versions

**Comment by timfel** [comment]
Fixed in 3.1.2
