### ISSUE TITLE
Aleona's Tales in 2.4.3 does not see game data?

### ISSUE THREAD

**Issue by SenhorFlibble** [Wargus/wargus#383]
I downloaded Wargus 2.4.3 for Windows (I'm running Windows 8.1) - which appears to be the latest release to support Aleona's Tales - and installed it in a non-Program Files folder on a non-system partition (D:\Programmes\Wargus). I have not installed or converted any actual Warcraft II BNE files.

I run aleonas_tales.exe and can access the menu (although there is no music playing, only the sound click when pressing menu buttons), however any attempts to run a scenario or campaign end with a crash back to desktop, and a message which says:

"Stratagus failed to load game data. If you just launched the game without any arguments, this may indicate a bug with the extraction process."

As far as I can tell, the libre game data of Aleona's Tales are present in the correct folders where they were put by the installer.

BTW, has Aleona's Tales been dropped from Wargus? Versions 3.0.0 and above appear to no longer include it.

**Comment by SenhorFlibble** [comment]
So far I've been only able to run [Wargus 2.3](https://launchpad.net/wargus) on my system (not counting the stand-alone Aleona's Tales Release Candidate from 2012). I installed both Stratagus 2.3 and Wargus 2.3 (selected to install Aleona's Tales in the installer, an option not provided in later versions) in the default Program Files (x86) location, but it only works when I run Wargus as an admin, not from my user account.

Perhaps there's an account permissions conflict that prevents the game from working properly?

**Comment by timfel** [comment]
Hi, yes, Aleona's Tales has been dropped since it was already partially broken in 2.4 and no one wanted to fix it. The old versions needed Admin, if I remember correctly. (It's been a long time, sorry)
