### ISSUE TITLE
Very slow mana generation

### ISSUE THREAD

**Issue by Bomfunk** [Wargus/wargus#384]
**Describe the bug**
In 3.1.2 I started noticing that the mana of paladins/ogres sometimes is generating incredibly slowly.

This might have something to do with this, as I have noticed this in release notes (of 3.1.1):
* Slow down regeneration rate for berserkers to 1hp every 2 seconds

Additionally, I have found a workaround - simply saving and loading immediately seems to fix this.

**To Reproduce**
I could not figure out what could be causing this, so this is the best I can describe the steps to reproduce the behavior:
1. Play some map with AI normally
2. Reach paladins/ogre-magi
3. Notice that their mana is generating very slowly (probably less than 1 per second)

**Expected behavior**
Mana is generating quickly, perhaps about 2 per second or so.

**Screenshots and Logs**
The logs do not seem to contain much relevant, but please let me know if you still wish me to provide any info.

**Desktop:**
 - OS: Windows 10
 - Version 3.1.2

**Comment by Bomfunk** [comment]
I also noticed that saving and loading speeds up the berserker regeneration, too. Seems this might be the same thing in the code?

**Comment by timfel** [comment]
@Bomfunk thanks for the report. We have already fixed this almost immediately after the 3.1.2 release, but since then work's been completely bonkers for me, so I haven't managed to do another release. The latest "master-build" of what will become 3.1.3 should have this fix.
