### ISSUE TITLE
Fix for Aleona's Tales 2.4.3

### ISSUE THREAD

**Issue by SenhorFlibble** [Wargus/wargus#386]
Previously I reported that the latest release of Aleona's Tales failed to work for me on Windows 8.1, and after some fiddling with it I figured out the solution.

It appears that the problem was in PNG files, or to be more precise in a combination of faulty PNGs and missing or incorrectly arranged files. I've been able to fix these errors, and also made a few updates to some sprites using Nikita Sadkov's unused contributions and my own work. Skirmish works with all terrain types, as well as the campaign and the new game modes, although at least one map from the For the Motherland set failed to load, but it seems to be related to the map itself, not other game data.

I zipped up the fixed files and uploaded them here: [aleonas-tales-2.4.3-fix.zip](https://mega.nz/file/LdZG2JgL#BV0vEdFvF15t6-3p6C0AJfmlbNDJQu7pP5Yt9qG8-q8)

Here's the entire changelog:

General fixes
-------------
- fixed Windows crashes caused by faulty PNG files by rolling back to versions
  from Timeless Tales (https://github.com/Wargus/Timeless-Tales)
- fixed Windows crashes caused by missing or incorrectly named PNGs

Tileset fixes
-------------
- fixed tileset scripts
- rolled back to the old summer tileset, but fixed problematic water tiles using Nikita Sadkov's work
- added proper fog of war to all tilesets based on Wyrmsun's fog of war

Graphical updates
-----------------
- added updated Castle sprites by Nikita Sadkov from https://forums.stratagus.com/viewtopic.php?f=33&t=3624
- added updated Wild Blacksmith sprites by Nikita Sadkov
- added updated Battleship sprites by Nikita Sadkov
- added updated small and large fire sprites by Nikita Sadkov
- added updated lightning sprites by Nikita Sadkov
- added updated fireball sprites by Nikita Sadkov
- added updated explosion sprites by Nikita Sadkov
- added updated cannonball explosion sprites by Nikita Sadkov
- added updated cannon tower cannonball explosion sprites by Nikita Sadkov
- added updated Whirlwind effect by Nikita Sadkov
- updated shading on Footman sprites using ESRGAN upscale-downscale

Graphical fixes
---------------
- restored original Great Hall and Fortress sprites to get back missing pixels
- fixed Peasant remap colours
- cleaned up Death Knight sprites and restored proper remap colours
- fixed Troll Axethrower remap colours
- fixed Skeleton remap colours
- fixed Ogre remap colours

Sound fixes
-----------
- the main menu theme now plays in Aleona's Tales menus

**Comment by timfel** [comment]
Hi,
thanks for linking this here. I am going to close the issue, since there's nothing to be done for Wargus here. Personally, I prefer the Warcraft 2 sprites, but there's not arguing about taste :)
