### ISSUE TITLE
Game is frozen at start until menu is opened and closed

### ISSUE THREAD

**Issue by Bomfunk** [Wargus/wargus#388]
**Describe the bug**
This seems to be reproducible on Windows only. Most likely has something to do with the "Pause on leave" function, as the issue is no longer there when this is disabled.

When Wargus is started and any mission is launched, the game is frozen until menu is opened and closed. This happens only one time, to reproduce this again the game has to be restarted.

This is a very minor issue as it's easy to reproduce, however it took me months to figure out I can just open and close the menu. Before I was just restarting the scenario.

**To Reproduce**
0. Make sure "Pause on leave" is on in settings
1. Launch Wargus on Windows
2. Start any mission, no matter if campaign or skirmish
3. Observe the game being frozen, minimap should be completely black

**Expected behavior**
No freeze

**Screenshots and Logs**
I'll attach logs shortly.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.2

**Comment by Bomfunk** [comment]
Not sure if there is possibility to upload logs to github, so I uploaded them to gdrive: https://drive.google.com/file/d/1Oup5GBeXb32MK3dfGxD60h5agUjF050G/view?usp=sharing

**Comment by Bomfunk** [comment]
Unlikely, as in this case the game is responsive, and menu can be opened (which actually fixes the game). But I can't be sure, of course.

**Comment by timfel** [comment]
Fixed on master
