### ISSUE TITLE
"Player" has sent bad command - Network out of sync

### ISSUE THREAD

**Issue by Bomfunk** [Wargus/wargus#390]
**Describe the bug**
Sometimes after some time of playing multiplayer (local game) suddenly one of the players gets an "<Other player> sent bad command", which is followed by many "network out of sync" messages before and/or after. After this the game crashes for one of the players, leaving the other one alone playing.

**To Reproduce**
1. Set up a local multiplayer game (one player clicks "create", the other one joins).
2. Play for a while with some AI as enemies.
3. ? Not sure what exactly causes it - maybe the general "business" of the map. For me a big map with many enemies seems to have done it, but it also happens randomly.
4. Observe the messages and inability to play together any longer.

**Expected behavior**
The game is uninterrupted until the end of the scenario.

**Screenshots and Logs**
This is an archive of logs for the 2 most recent times I have reproduced this on the same map.
It is about 260 MB but be careful - it can extract to about 5 GB, as both Wargus instances were launched with "-i -p".
https://drive.google.com/file/d/11X759nNDQ5XHlUym7n2UuTQPYQogB8Mp/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: One player on Windows 10, another one on Arch Linux
 - Version 3.1.2
 - Played over Wireguard (VPN), but this also happens on a local network over WiFi.

**Comment by timfel** [comment]
I got further with this, it seems I can reproduce this bug now. It's something to do with pathfinding back from a goldmine to the town hall.

**Comment by timfel** [comment]
This specific issue is fixed.
