### ISSUE TITLE
Mac OSX Data Install Issue

### ISSUE THREAD

**Issue by jupera** [Wargus/wargus#404]
**Describe the bug**
Cannot Install Data on Mac OSX 12.0.1
My Original Disk is: WAR2_122 : Warcraft II Tides of Darkness

**To Reproduce**
Upon Launching I get the message:
Wargus data was not extracted, is corrupted, or outdated.
You need to extract it from original Warcraft II DOS REZDAT.WAR or BNE INSTALL.MPQ/INSTALL.EXE file. Please select the Warcraft II DOS REZDAT.WAR or BNE INSTALL.MPQ/INSTALL.EXE file

I select DATA/REZDAT.WAR

Result:
There was an error copying the data, could not discover contributed directory path.

**Screen Captures**
<img width="429" alt="Screen Shot 2021-11-28 at 10 07 12 AM" src="https://user-images.githubusercontent.com/15862978/143780820-902d3454-8178-4178-b94c-d2bb6129ab23.png">
<img width="1356" alt="Screen Shot 2021-11-28 at 10 17 05 AM" src="https://user-images.githubusercontent.com/15862978/143780826-23bd614e-30d8-41e9-8954-58a57650a513.png">

<img width="429" alt="Screen Shot 2021-11-28 at 10 11 48 AM" src="https://user-images.githubusercontent.com/15862978/143780829-ee0b0431-a391-4808-9a25-a42445f0f14b.png">
<img width="422" alt="Screen Shot 2021-11-28 at 10 18 44 AM" src="https://user-images.githubusercontent.com/15862978/143780835-a4c78d54-4df7-40c0-84fe-efa640ae42f2.png">

**Comment by abenedic** [comment]
Could you try running it in the terminal and pasting any output you get here?  You may also want to try building it from source if you are comfortable with that. I have some instructions on building it on macOS here: https://github.com/Wargus/stratagus/wiki/Building-on-macOS .

**Comment by macsobel** [comment]
I was able to get the script working in Terminal. It failed entirely at first until I installed Homebrew and FFMPEG for macOS. Running the script gave me a similar output to what I get in Windows but it created the files in a folder called "data" in my macOS user folder ("/data") instead of "/Library/Stratagus/data.Wargus/". Here is my log for running wartool in Terminal:

[Terminal Saved Output.txt](https://github.com/Wargus/wargus/files/7983369/Terminal.Saved.Output.txt)
<img width="400" alt="Screen Shot 2022-02-01 at 10 28 06 PM" src="https://user-images.githubusercontent.com/4029390/152089064-feeb5aa3-38e4-48c4-a6c4-c9888b9b0500.png">

Leaving the files there or moving them to proper location results in Wargus starting up and saying the Wargus format has changed, and then fails to fix it with the following messages when I try to launch:

<img width="1576" alt="Screen Shot 2022-02-01 at 10 36 05 PM" src="https://user-images.githubusercontent.com/4029390/152089380-5b890d61-7b95-416f-bf2b-398ff6195a67.png">

<img width="400" alt="Screen Shot 2022-02-01 at 10 30 47 PM" src="https://user-images.githubusercontent.com/4029390/152089120-7b2e5676-939f-48c9-8097-5357494b4ac3.png">

<img width="400" alt="Screen Shot 2022-02-01 at 10 30 52 PM" src="https://user-images.githubusercontent.com/4029390/152089158-5cccd9f3-870c-4a13-b3de-a45b5470d812.png">

<img width="400" alt="Screen Shot 2022-02-01 at 10 30 56 PM" src="https://user-images.githubusercontent.com/4029390/152089186-6a1e92e9-2546-4275-85e2-5533cc72b200.png">

**Comment by jupera** [comment]
In a last desperate attempt, I copied the Stratagus/data.Wargus from a working Windows installation and now I get the same error message as macsobel
<img width="431" alt="Screen Shot 2022-02-13 at 11 07 53 AM" src="https://user-images.githubusercontent.com/15862978/153770744-fb6aca25-4c93-4afc-8b00-56f2d7e6b1d0.png">
.

**Comment by praetorfenix404** [comment]
Running wartool manually to extract the data results in this:

./wartool -r -v /Volumes/Warcraft\ 2 ~/Library/Stratagus/data.Wargus
Please be patient, the data may take a couple of minutes to extract...
Archive "/Volumes/Warcraft 2/suPPORT/TOMES/TOME.2"
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file

MacBook Pro 16,1
Monterey 12.2.1
BNE CD

**Comment by praetorfenix404** [comment]
I'm not a developer, but I know enough to be dangerous. Looking through the logic to detect versions and paths for case sensitivity gave me the idea. I copied everything from the BNECD and wrote a small shell script to rename all files and folders to lower case. The GUI still failed to load after selecting install.exe, so no change there, however that allowed the wartool to work as expected when ran manually.

Placing the extracted data in ~/Library/Stratagus/data.Wargus resulted in "Stratagus failed to load game data" when launching the GUI and running via command line threw an error for missing images in a /ui folder. I was able to locate those files in "contrib" and put them in place. Still the GUI failed, but running via command line worked specifying the data and user paths.

 Finally able to somewhat launch the app, trying to start the campaign fails with the menu going in circles back to the beginning.

Hope this helps.

**Comment by JiLiZART** [comment]
I have compile stratagus 3.3.3 and wargus from source code.
Also Install ffmpeg theora codec `brew install ffmpeg2theora`.
Place compiled `stratagus  wargus  wartool` to `/Applications/Wargus.app/Contents/MacOS` also copied `campaigns  contrib  maps  scripts  shaders` folders from wargus to `/Applications/Wargus.app/Contents/MacOS`

After run
`/Applications/Wargus.app/Contents/MacOS/wartool -v -r '/path/to/original-warcraft2' '~/Library/Stratagus/data.Wargus'`

And run game.

I share precompiled binaries here https://github.com/JiLiZART/wargus-3.3.3-macos-m1-app (well tested on MacOS 12.4 M1 Chip)

**Comment by jupera** [comment]
Thank you for the binaries JiLiZART! 

I have downloaded your binaries, installed ffmpeg, and ffmpeg2theora.

And when I run 

/Applications/Wargus.app/Contents/MacOS/wartool -v -r '/path/to/original-warcraft2' '~/Library/Stratagus/data.Wargus'
(with path to my original)

I get the following:

MacBook-Pro:MacOS julio$ ./wartool -v -r /Users/julio/Documents/Development/WAR2_122 ~/Library/Stratagus/data.Wargus
Detected US original DOS CD
Extract from "/Users/julio/Documents/Development/WAR2_122/data" to "/Users/julio/Library/Stratagus/data.Wargus"
Please be patient, the data may take a couple of minutes to extract...
Archive "/Users/julio/Documents/Development/WAR2_122/data/rezdat.war"
Archive "/Users/julio/Documents/Development/WAR2_122/data/strdat.war"
Ignore entry 42 in archive (invalid uncompressed length)
Archive "/Users/julio/Documents/Development/WAR2_122/data/maindat.war"
Ignore entry 25 in archive (invalid uncompressed length)
Ignore entry 32 in archive (invalid uncompressed length)
Ignore entry 68 in archive (invalid uncompressed length)
Ignore entry 431 in archive (invalid uncompressed length)
Ignore entry 437 in archive (invalid offset)
ffmpeg -y -i "/Users/julio/Library/Stratagus/data.Wargus/videos/logo.smk" -codec:v libtheora -qscale:v 31 -codec:a libvorbis -qscale:a 15 -pix_fmt yuv420p "/Users/julio/Library/Stratagus/data.Wargus/videos/logo.ogv"
ffmpeg version 5.1.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/5.1.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, smk, from '/Users/julio/Library/Stratagus/data.Wargus/videos/logo.smk':
  Duration: 00:00:11.67, start: 0.000000, bitrate: 544 kb/s
  Stream #0:0: Video: smackvideo (SMK2 / 0x324B4D53), pal8, 320x160, 12 tbr, 12 tbn
  Stream #0:1: Audio: smackaudio (SMKA / 0x414B4D53), 22050 Hz, mono, u8
Stream mapping:
  Stream #0:0 -> #0:0 (smackvideo (smackvid) -> theora (libtheora))
  Stream #0:1 -> #0:1 (smackaudio (smackaud) -> vorbis (libvorbis))
Press [q] to stop, [?] for help
Output #0, ogv, to '/Users/julio/Library/Stratagus/data.Wargus/videos/logo.ogv':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: theora, yuv420p(tv, progressive), 320x160, q=2-31, 200 kb/s, 12 fps, 12 tbn
    Metadata:
      encoder         : Lavc59.37.100 libtheora
  Stream #0:1: Audio: vorbis, 22050 Hz, mono, fltp
    Metadata:
      encoder         : Lavc59.37.100 libvorbis
frame=  140 fps=0.0 q=-0.0 Lsize=     529kB time=00:00:11.66 bitrate= 371.4kbits/s speed=23.6x    
video:396kB audio:122kB subtitle:0kB other streams:0kB global headers:7kB muxing overhead: 1.961796%
Archive "/Users/julio/Documents/Development/WAR2_122/data/sfxdat.sud"

Ending with the popup error: 
INVALID TITLE WITH QUOTES
"/Users/julio/Documents/Development/WAR2_122/data/sfxdat.sud"

<img width="430" alt="Screen Shot 2022-09-14 at 6 23 36 PM" src="https://user-images.githubusercontent.com/15862978/190292444-c0bd00c7-c6e1-455d-a329-b85837d5faca.png">

**Comment by jupera** [comment]
Thank you for the binaries JiLiZART!

It's finally working, but not completely.  I'll explain.

After following your steps, if I try running the App from finder I get this error:

<img width="429" alt="Screen Shot 2022-09-14 at 7 00 33 PM" src="https://user-images.githubusercontent.com/15862978/190295621-2ebecfd3-ac00-48dd-880e-765f57f38e91.png">

But if I use terminal and go into the Package itself, into Contents/MacOS and run ./wargus it works great!

I'm sure it's something stupid, but what?

Thanks again for your help!

**Comment by praetorfenix404** [comment]
> This should be fixed now if you build Stratagus and Wargus yourself.
> 
> You should be able to launch by just opening the app now. No need to open through Terminal anymore.
> 
> Please retest.
> 
> [Stratagus macOS build instructions.txt](https://github.com/Wargus/wargus/files/10970765/Stratagus.macOS.build.instructions.txt)

Wartool ran as expected, however a new issue has crept up with the extraction process resulting in failure to launch. 

Couldn't load file /Users/..me../Library/Application Support/Stratagus/data.Wargus/graphics/ui/human/filler-right.png: Unsupported image formatCan't load the graphic '/Users/..me../Library/Application Support/Stratagus/data.Wargus/graphics/ui/human/filler-right.png

It appears all UI elements among other assets PNGs are 0 bytes.

<img width="686" alt="Screenshot 2023-03-17 at 1 59 43 PM" src="https://user-images.githubusercontent.com/4162437/225983751-f9188ea6-1de4-489b-9692-e13f2f0d0a67.png">

**Comment by shinra-electric** [comment]
> It appears all UI elements among other asset PNGs are 0 bytes.
Are you extracting from the DOS version or the GOG version?
I’m using GOG, I haven’t tried it with DOS…

**Comment by praetorfenix404** [comment]
> > It appears all UI elements among other asset PNGs are 0 bytes.
> 
> Are you extracting from the DOS version or the GOG version? I’m using GOG, I haven’t tried it with DOS…

The only copy I’ve got is an original Battle.net edition CD from ‘99

**Comment by shinra-electric** [comment]
It might be an issue specific to the CD version maybe? 

I'll see if I can dig up a copy to test on.

**Comment by shinra-electric** [comment]
I managed to get my hands on a BNE edition. I had to install it using Wineskin in order to get the "correct" `install.exe`, but I had no issued extracting it...

<img width="729" alt="Screenshot 2023-03-19 at 17 14 22" src="https://user-images.githubusercontent.com/50119606/226189331-7ca8b636-baac-4a5b-b68b-8575ddd8fd8e.png">
Not having the same zero size images that you were. 

Can you delete your `data.Wargus` folder and try again?

**Comment by shinra-electric** [comment]
I recently just discovered a few things that might help you: 

1: Wartool will fail if you delete the source code folder. See #438 for details.

2: The Windows BNE version comes on a CD that has an `install.exe` file, but this is *not* the one that wartool is looking for. Once WC2 has been installed there will be another `install.exe` file that is the right one. (It can be installed without Windows by using Wineskin).

3: It will complain when trying to extract from the BNE data, but it will actually open a Terminal window in the background and start working.
<img width="532" alt="Screenshot 2023-03-19 at 21 30 13" src="https://user-images.githubusercontent.com/50119606/226207544-b5a509d5-4e96-425a-a76f-fe1e2b8e053c.png">
4: It will ask if you want to install from the expansion CD, even though BNE and GOG versions already include it. Just select no.
<img width="532" alt="Screenshot 2023-03-19 at 21 31 55" src="https://user-images.githubusercontent.com/50119606/226207559-c38aa23b-1921-411c-b3ab-2012c482bf9c.png">

**Comment by praetorfenix404** [comment]
May have found something with wartool. Managed to get my hands on ancient DOS versions of the original and expansion. They both contain the same errors when extracting from tomes. The libpng warning repeats many times.

`Archive "/Users/esylvester/Documents/ISO/Games/WAR2BNECD/support/tomes/tome.1"
Ignore entry 25 in archive (invalid uncompressed length)
Ignore entry 32 in archive (invalid uncompressed length)
Copied /Users/esylvester/Documents/ISO/Games/WAR2BNECD/support/tomes/tome.1->/Users/esylvester/Desktop/test/support/tomes/tome.1
libpng warning: Application built with libpng-1.4.12 but running with 1.6.39`

**Comment by praetorfenix404** [comment]
I did indeed compile stratagus and wargus from source.

**Comment by shinra-electric** [comment]
Can you export your terminal output from when you build and post here as a text file? I might spot something. 

Actually, maybe we can chat in the discord channel so we don't pollute GitHub....

**Comment by shinra-electric** [comment]
This issue can likely be closed, unless other people are still having trouble. 

There is still a data extraction issue in #438 that is the cause of trouble for most people, but that is a separate issue.

**Comment by macsobel** [comment]
Years later, circling back... I am able to play a version of Wargus on my Mac. Thanks to everyone involved!

- Using the GoG version of WarCraft II
- Using the compiled macOS app version mentioned above: https://github.com/JiLiZART/wargus-3.3.3-macos-m1-app
- Extracting the data.Wargus files using the Windows version of Wargus (I used Crossover for this but Windows would work)
- Placing the data.Wargus folder inside ~/Library/Stratagus/ on my Mac
- Launching the Wargus.app displays an error but then runs just fine
