### ISSUE TITLE
[question] What's stormlib support good for?

### ISSUE THREAD

**Issue by AMDmi3** [Wargus/wargus#405]
I've built wargus without stormlib support, and it worked fine for me, e.g. converted game content successfully and there even were videos. I maintain FreeBSD port of wargus and I wonder whether I should enable stormlib support at all. What's it good for?

**Comment by timfel** [comment]
Sorry for the late reply. StormLib is needed to extract from the BattleNet edition, which is the one you also get from GoG, for example

**Comment by AMDmi3** [comment]
Got it. Thank you very much, I can now document this option for FreeBSD port.
