### ISSUE TITLE
Ability to order peasants to drop cargo (wood) at limber mill/townhall

### ISSUE THREAD

**Issue by AMDmi3** [Wargus/wargus#411]
**Describe the bug**
I'm pretty sure it was possible in the original game to order peasants holding cargo to drop it at the town hall/lumber mill. Would be nice to have it in wargus as well ( even if in fact original game didn't have it).

**To Reproduce**
- Pick a peasant holding wood
- Order it move to a town hall/limber mill
- See that it stops at the building without dropping a wood there

**Expected behavior**
A peasant would enter a building and drop its cargo there.

**Desktop (please complete the following information):**
 - Version 3.2.0

**Comment by timfel** [comment]
Fixed on master
