### ISSUE TITLE
Can't convert UTF8 char to Ascii 

### ISSUE THREAD

**Issue by jmunin** [Wargus/wargus#420]
**Describe the bug**
Using the Spanish version of the game (Battle.NET edition), on the introductory screen to each phase of the game, the text in Spanish is not displayed with their corresponding accented vowels (á,é,í,ó,ú, Á,É,Í,Ó,Ú, interrogation closing instead, see attached image), and in the terminal from which I execute Wargus, it shows the error messages indicated. 

**To Reproduce**
1. When i run wargus in linux terminal.
2. See error in terminal:
Can't convert UTF8 char to Ascii : '�' d=128 (0x0080)
Can't convert UTF8 char to Ascii : '�' d=129 (0x0081)
Can't convert UTF8 char to Ascii : '�' d=130 (0x0082)
Can't convert UTF8 char to Ascii : '�' d=132 (0x0084)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux 21.2.2]
 - Version [Wargus 3.2.0-1 Stratagus 3.2.0-1]
![Screenshot_20220127_130330](https://user-images.githubusercontent.com/10065513/151355607-8cd5f621-e89a-4239-a664-a399497f4264.png)
[log_of_stratagus_1_1643285080.log](https://github.com/Wargus/wargus/files/7950272/log_of_stratagus_1_1643285080.log)

**Comment by timfel** [comment]
I have a branch open already to fix this.

**Comment by jmunin** [comment]
ok, thanks for your work!

**Comment by timfel** [comment]
Fixed on master
