### ISSUE TITLE
Extraction fails on Linux - Pop!_OS, Manjaro, etc

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/wargus#421]
After I've installed Wargus 3.2.0 on Pop!_OS 21.10, I go to run it, and as per usual, first time run, it asks me to point to the data/exe files, so it can extract the data.

I do this, and all it does is spit out a message box with the title "Extraction Failed!" and a message saying "INVALID MESSAGE WITH QUOTES", and that's it.

**To Reproduce**
1. install the game on linux whichever way you can - manjaro, use add/remove software, ubuntu and dirivitives
, use the guide on stratagus.com 
2. Click on 'Wargus - Warcraft II'
3. See error popup when you go to extract the data! yew!

**Expected behavior**
I expected to have a fully operational game. I've never had an issue before playing on Linux, this is new...and annoying!

 - OS: Pop!_OS 21.10 Nvidia version
 - Version - 3.2.0

**Comment by timfel** [comment]
I just tried on a fresh VM with Ubuntu 21.10 and cannot reproduce your problem. Did you try running from the terminal and if yes, what's the output?

**Comment by DinkyDyeAussie** [comment]
No I didn't try using the terminal. You mean by typing in wargus and waiting for the prompt to extract data right?

**Comment by timfel** [comment]
> No I didn't try using the terminal. You mean by typing in wargus and waiting for the prompt to extract data right?

Yes

**Comment by DinkyDyeAussie** [comment]
That worked. Wargus installed successfully. Thankyou Tim for your help :+1:
