### ISSUE TITLE
Wargus - Translate to Czech

### ISSUE THREAD

**Issue by Arielistelos** [Wargus/wargus#422]
https://poeditor.com/join/project?hash=BVo8MAZuys
https://poeditor.com/join/project?hash=7myZPTmcqq

Hi, I just finished Czech translate for Wargus and Stratagus.
I used POEditor, but during the translation I did not notice individual scenarios and messages between missions, is there any way to translate it? I would like to finish it all :)

**Comment by timfel** [comment]
Thank you for the contribution! Czech will be included in the next release (summer).

The scenario texts cannot be translated, unfortunately, since they come from the game data. I will think a bit if we can somehow make that work, but not sure how.
