### ISSUE TITLE
Mission Alterac. Bug. There is no Alterac.

### ISSUE THREAD

**Issue by katastic** [Wargus/wargus#426]
Alliance campaign, normal difficulty

Objectives:
 - Free the Mages and Peasants
 - Destroy Alterac

![image](https://user-images.githubusercontent.com/11449593/160536006-e717a4a2-92d8-4391-b45d-fd1bbf0fdced.png)

Killing the final blimp ended the match though. So maybe he was there and died already? But then the map triggers are incorrectly set to "kill everyone" not "kill alterac"

**Comment by timfel** [comment]
Alterac is the nation. So destroy everything is what you need to do :)
