### ISSUE TITLE
Wargus 3.3.1 is unplayable

### ISSUE THREAD

**Issue by Shin-Aska** [Wargus/wargus#427]
**Describe the bug**
Attempting to play the game either via Single player skirmish or Campaign will freeze the game with noise audio that seems to like the engine is trying to play something but keeps on repeating.

**To Reproduce**
1. Open the game
2. Attempt to play
3. See problem

**Expected behavior**
The game should be able to play when going to the campaign

**Screenshots and Logs**
There are no errors but I did made a recording just so that everyone has an idea how it looks like https://youtu.be/_Rx4ztsyBmY

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 (Tried it on Windows as well and same issue)
 - Version: 3.3.1

**Comment by Shin-Aska** [comment]
Actually I tried just now turning off the audio completely from the settings and its works, the game plays (with no audio ofcourse). Could be an issue with the latest engine's audio handling?

**Comment by Northfear** [comment]
There's probably a problem with some `SDL_mixer` version. `Mix_PlayingMusic()` was always returning "false" for me in 2.0.4 on PS Vita

**Comment by Shin-Aska** [comment]
> There's probably a problem with some `SDL_mixer` version. `Mix_PlayingMusic()` was always returning "false" for me in 2.0.4 on PS Vita Just disabling music s enough btw.

I just checked and yes you're right, disabling music is indeed enough for it to be playable.

**Comment by timfel** [comment]
Hm, I cannot reproduce this. I tried Ubuntu 20.04, Ubuntu 18.04, Debian Bullseye, and Windows 11 :/

**Comment by Shin-Aska** [comment]
> Hm, I cannot reproduce this. I tried Ubuntu 20.04, Ubuntu 18.04, Debian Bullseye, and Windows 11 :/

This is how mine would be if it is on Windows: https://youtu.be/hd48O8Pe4Qc
Still  the same stuff, on Windows I went with the [Wargus-portable-3.3.1.exe](https://github.com/Wargus/wargus/releases/download/v3.3.1/Wargus-portable-3.3.1.exe)

**Comment by OndroNR** [comment]
3.3.1 freezes on my Windows 10. If I disable music in main menu and enable it during scenario, it works.

**Comment by timfel** [comment]
This is fixed in 3.3.2

**Comment by Shin-Aska** [comment]
Can confirm, it is now fixed including the music loop i described in 3.2.0

**Comment by Shin-Aska** [comment]
Closing this issue now
