### ISSUE TITLE
How do I download this game?

### ISSUE THREAD

**Issue by Winterwolf9729** [Wargus/wargus#435]
This isn't exactly an issue, but I require assistance. I got the app on my Android and I have Warcraft 2 + the expansion on GOG.com. But I have no idea how to download the proper files into the Stratagus app and I couldn't understand the instructions since I don't have an original Warcraft 2 + expansion CD. Can anyone here tell me how to download the game on my phone?

**Comment by timfel** [comment]
Sorry, the Android app is not done by the official team. Best to check the website of the person who does it https://drodin.com/stratagus/ or open an issue for @drodin at their fork https://github.com/drodin/Stratagus/

**Comment by Winterwolf9729** [comment]
Okay. Thanks for the help.

**Comment by timfel** [comment]
@Winterwolf9729 I honestly don't know, you'd probably have to match the version, but maybe @drodin also made changes to the extraction or expected data, I don't know. I would just try, worst thing you'll have spent a few minutes to learn that it doesn't work that way either.

**Comment by Winterwolf9729** [comment]
I'm sorry, I don't mean to ask pointless questions, but @drodin seems to
have disappeared off the face of the earth or something, and the only other
guy in the GitHub hasn't responded yet either even though I asked him for
help, too.

I really want to play Warcraft 2 on my phone, but if I can't get help from
the creator of the android version or the guy who was also trying to do the
same thing I am, then your team is the only one left I can turn to.

Even if you guys can't tell me how to move the game to my phone, I was
hoping that you might at least know how I can get it on my laptop first so
I can go from there. But it seems you're just as stumped as me.
Regardless of that, thank you for your time, anyway. I'll keep trying to
succeed at this.

**Comment by timfel** [comment]
@Winterwolf9729 well, https://youtu.be/6a4dy16q49c shows in the first 8 minutes how to install the game on Windows and Linux from different sources, so you can check if that works for you.
