### ISSUE TITLE
Questions and suggestions about War1gus and Wargus

### ISSUE THREAD

**Issue by SilentMRG** [Wargus/wargus#443]
Hello...

I see two installers: "Wargus-3.3.2.exe" and "Wargus-portable-3.3.2.exe". 
What is the difference between two? I assume the second "portable" will do a portable installation, is that it?

Can I copy the Warcraft 1 + 2 files myself and paste into the directory so that the source port is initialized? 
Yes, I know, Wargus automatically detects the installation, but I don't want to have to install Warcraft for that, I prefer (if possible) to copy the game files and paste them in the source port folder, just as DevilutionX allows : https://github.com/diasurgical/devilutionX

I want to make a suggestion: War1gus and Wargus would be better if they followed the DevilutionX files structure. It's strange, in my humble opinion, installers for source ports. Don't be offended... I don't want that, I'm just a guy who discovered your project yesterday, so I want to understand how things work. =)

Thank you for your attention in advance!

**Comment by timfel** [comment]
Hi, thanks for the suggestions.

> I see two installers: "Wargus-3.3.2.exe" and "Wargus-portable-3.3.2.exe". What is the difference between two? I assume the second "portable" will do a portable installation, is that it?

Yes.

> Can I copy the Warcraft 1 + 2 files myself and paste into the directory so that the source port is initialized?

No. Wargus needs to extract data files. You don't have to install Warcraft, just point Wargus to the DOS or Battle.net CD or the GoG installer, it will convert the data files to the Wargus format.

> I want to make a suggestion: War1gus and Wargus would be better if they followed the DevilutionX files structure. It's strange, in my humble opinion, installers for source ports.

I think the misunderstanding is that you call Wargus a source port. It is not. Wargus is not trying to completely recreate Warcraft 2. It is it's own game, built on the Stratagus strategy game engine. Wargus just uses the Warcraft 2 assets and converts them so they can be used with Stratagus. That gives you a game that is similar to Warcraft 2 and looks almost exactly like Warcraft 2, but it is very different and many mechanics are different (on purpose!). This project really isn't about making a true Warcraft 2 experience available on modern platforms. It's about making a game that feels a bit like Warcraft 2, to give you that nice nostalgia.

**Comment by SilentMRG** [comment]
I see... I thought it was a source port, given the fact that it was very similar to the original games. I have one last question: When the file conversion finishes (in Warcradt II), it asks me whether or not I want to extract more data, and in this case, it mentions a CD expansion of the MS-DOS version, so should I skip this step? I use the GOG version and I don't have any CD expansions for the MS-DOS version.

Thank you very much for all this information!
