### ISSUE TITLE
LUA error: attempt to call global 'SetFogOfWarEasingSteps' (a nil value)

### ISSUE THREAD

**Issue by etm** [Wargus/wargus#468]
I successfully extracted from setup_warcraft_ii_2.02_v4_\(28734\).exe which i downloaded from GOG.

When starting, the following error occurs. I have Fedora 40, lua 5.4.6

[string "/home/xxx/.stratagus/data.Wargus/scripts/stratagus.lua"]:204: attempt to call global 'SetFogOfWarEasingSteps' (a nil value)
stack traceback:
	[string "/home/xxx/.stratagus/data.Wargus/scripts/stratagus.lua"]:204: in main chunk

**Comment by ipochto** [comment]
Which version of stratagus ?

**Comment by etm** [comment]
Stratagus v3.3.2, Copyright (c) 1998-2020 by The Stratagus Project
  written by Lutz Sammer, Fabrice Rossi, Vladi Shabanski, Patrice Fortier,
  Jon Gabrielson, Andreas Arens, Nehal Mistry, Jimmy Salmon, Pali Rohar,
  cybermind and others.
	https://github.com/Wargus/stratagus
Compile options ZLIB BZ2LIB VORBIS THEORA LINUX

**Comment by ipochto** [comment]
Very strange, this method was added about 2 years ago.  Do you have this line?
https://github.com/Wargus/stratagus/blob/9a24853bd68d5e8fc97fec66e1a8cb4a543f999e/src/map/script_map.cpp#L1187

**Comment by ipochto** [comment]
Just chekked: this commit was merged after 3.3.2 release.
So, you should use same version of both wargus and stratagus. 3.3.2 is latest stable.
In your case, it seems  you use master for wargus and 3.3.2 for stratagus.

**Comment by etm** [comment]
You are right. Sadly i am not successful in compiling stratagus HEAD, i currently fail in editloop.cpp because guichan version seems different on fedora (and im am not sure what i need, vendored_guichan() cmake function is missing from my cmake and i am not sure how to get it). 

I had some success with the 3.3.2 version, but there is a consistent crash when clicking on victory in level 4 horde (ToD). I can provide the savegame 1 second before victory in a different issue, but as i said its from an old version.

**Comment by Jarod42** [comment]
Make sure you have (git) submodule updated, i.e stratagus\third-party should not be empty, and should also contains guichan directory.

**Comment by etm** [comment]
@Jarod42: yes i missed the submodule. With submodule guichan errors go away. It compiles till end. But then during linking: 

/usr/bin/ld: libstratagus_lib.a(interface.cpp.o): in function `HandleCommandKey(int)':
/home/mangler/Projects/_/stratagus/src/ui/interface.cpp:533:(.text+0x22f1): undefined reference to `lua_getglobal'. 

I assume the problem is that I have no lua 5.1 (although if have compat-lua-* for fedora which contains 5.1 things. Manually linking to -llua-5.4 (against better judgement) of course produces a thing which immediatly segfaults. hmmm.

**Comment by Jarod42** [comment]
Try to set BUILD_VENDORED_LUA option to ON (CMake) to used provided version instead of system one...

**Comment by etm** [comment]
Thanks, that was it. It works together with wargus appimage. I will try to compile wargus next.
